### ISSUE TITLE
知网部分硕博论文库无法直接下载的原因

### ISSUE THREAD

**Issue by DrLinZhang** [l0o0/translators_CN#100]
看这个例子
**Composition Design and Property Optimization of High Entropy Alloys Based on Machine Learning**
他可以搜索到两个连接
[https://oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1022015140.nh&uniplatform=OVERSEAS_EN&v=nifDaQvmFTEpsIltSXnnUYj7Tn4gshjGGGLyvZ6GY5VC3fM3tHsQFTEAi-P5iGka](https://oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1022015140.nh&uniplatform=OVERSEAS_EN&v=nifDaQvmFTEpsIltSXnnUYj7Tn4gshjGGGLyvZ6GY5VC3fM3tHsQFTEAi-P5iGka)

[https://oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2022&filename=1022015140.nh&uniplatform=OVERSEAS_EN&v=nifDaQvmFTEpsIltSXnnUYj7Tn4gshjGGGLyvZ6GY5VC3fM3tHsQFSraGcKQEA5u](https://oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2022&filename=1022015140.nh&uniplatform=OVERSEAS_EN&v=nifDaQvmFTEpsIltSXnnUYj7Tn4gshjGGGLyvZ6GY5VC3fM3tHsQFSraGcKQEA5u)

区别在于 dbname参数不同，一个是CDFDTEMP， 一个是CDFDLAST2022

而知网CNKI.js现在用的是旧版中文 REFworks API
在中文网站上 只能搜到一个结果
dbname参数为CDFDLAST2022

因此直接打开第一个连接报错的原因是数据库名字不同

临时规避办法就是  选择连接时，选择 不带  CDFDTEMP 参数的。

**Comment by l0o0** [comment]
我分析了第一篇的网页信息，发布在网页中是存在和URL中不同的dbname
![图片](https://user-images.githubusercontent.com/2743744/226934696-b43b45c9-c4a0-41ca-bbbb-90a384dd0a9f.png)

我觉得可以加个条件，当网址中的dbname含有temp时，可以采用HTML中隐藏的dbname。目前我们代码中也会从网页中获取dbname和filename参数，只是这种是在url中查询不到匹配的dbname和filename才会触发。后面我们会处理一下这种特殊的情况。

**Comment by l0o0** [comment]
新版转换器中，已经优先提取HTML网页中的dbcode等参数
```js
function getIDFromPage(doc, url) {
	return getIDFromHeader(doc, url)
		|| getIDFromURL(url)
		|| getIDFromURL(ZU.xpathText(doc, '//div[@class="zwjdown"]/a/@href'));
}
```
