### ISSUE TITLE
万方无法下载PDF附件，保存题目没有作者以及摘要字段

### ISSUE THREAD

**Issue by DrLinZhang** [l0o0/translators_CN#102]
### 测试例子
[https://d.wanfangdata.com.cn/periodical/zdhxb200001005](https://d.wanfangdata.com.cn/periodical/zdhxb200001005)

### 开发者工具输出
`22:15:14 Running doWeb

22:15:14 {
             "dbname": "journalArticle"
             "filename": "zdhxb200001005"
             "url": "https://d.wanfangdata.com.cn/https://oss.wanfangdata.com.cn/file/download/perio/zdhxb200001005.aspx"
         }

22:15:14 ---------------WanFang Data 20220405---------------

22:15:14 ===>undefined<=== (undefined)

22:15:14 Returned item:
           {
             "itemType": "journalArticle"
             "creators": [
               {
                 "firstName": "学工"
                 "lastName": "张"
                 "creatorType": "author"
               }
             ]
             "notes": []
             "tags": [
               {
                 "tag": "统计学习理论"
               }
               {
                 "tag": "支持向量机"
               }
               {
                 "tag": "机器学习"
               }
               {
                 "tag": "模式识别"
               }
               {
                 "tag": "张学工"
               }
               {
                 "tag": "自动化学报"
               }
               {
                 "tag": "ACTA AUTOMATICA SINICA"
               }
             ]
             "seeAlso": []
             "attachments": []
             "title": "关于统计学习理论与支持向量机"
             "extra": "清华大学自动化系,智能技术与系统国家重点实验室,北京,100084\n中国科学院资助项目\n2004-03-19 （万方平台首次上网日期，不代表论文的发表时间）"
             "publicationTitle": "自动化学报"
             "journalAbbreviation": "ACTA AUTOMATICA SINICA"
             "date": "2000"
             "volume": "26"
             "issue": "1"
             "pages": "32-42"
             "language": "zh_CN"
             "url": "https://d.wanfangdata.com.cn/periodical/zdhxb200001005"
             "libraryCatalog": "Wanfang Data"
             "accessDate": "2022-05-01T14:15:14Z"
           }

22:15:14 Translation successful`

### Zotero Debug 输出

`(3)(+0000001): [ "0": { "key": "9YYK7TGI" "version": 0 "itemType": "journalArticle" "url": "https://d.wanfangdata.com.cn/periodical/zdhxb200001005" "volume": "26" "issue": "1" "pages": "32-42" "publicationTitle": "自动化学报" "date": "2000" "extra": "清华大学自动化系,智能技术与系统国家重点实验室,北京,100084\n中国科学院资助项目\n2004-03-19 （万方平台首次上网日期，不代表论文的发表时间）" "journalAbbreviation": "ACTA AUTOMATICA SINICA" "accessDate": "2022-05-01T14:16:53Z" "libraryCatalog": "Wanfang Data" "language": "zh_CN" "title": "关于统计学习理论与支持向量机" "creators": [] "tags": [ "0": { "tag": "机器学习" "type": 1 } "1": { "tag": "模式识别" "type": 1 } "2": { "tag": "统计学习理论" "type": 1 } "3": { "tag": "张学工" "type": 1 } "4": { "tag": "支持向量机" "type": 1 } "5": { "tag": "自动化学报" "type": 1 } "6": { "tag": "ACTA AUTOMATICA SINICA" "type": 1 } ] "collections": [ "0": "9RW23CVL" ] "relations": {} "dateAdded": "2022-05-01T14:16:53Z" "dateModified": "2022-05-01T14:16:53Z" } ]

(3)(+0000000): Uploading 1 item

(3)(+0000001): Sending If-Unmodified-Since-Version: 7474

(3)(+0000001): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000001): HTTP POST "[{"key":"9YYK7TGI","version":0,"itemType":"journalArticle","url":"https://d.wanfangdata.com.cn/periodical/zdhxb200001005","volume":"26","issue":"1","pages":"32-42","publicationTitle":"自动化学报","date":"2000","extra":"清华大学自动化系,智能技术与系统国家重点实验室,北京,100084\n中国科学院资助项目\n2004-03-19 （万方平台首次上网日期，不代表论文的发表时间）","journalAbbreviation":"ACTA AUTOMATICA SINICA","accessDate":"2022-05-01T14:16:53Z","libraryCatalog":"Wanfang Data","language":"zh_CN","title":"关于统计学习理论与支持向量机","creators":[],"tags":[{"tag":"机器学习","type":1},{"tag":"模式识别","type":1},{"tag":"统计学习理论","type":1},{"tag":"张学工","type":1},{"tag":"支持向量机","type":1},{"tag":"自动化学报","type":1},{"tag":"ACTA AUTOMATICA SINICA","type":1}],"collections":["9RW23CVL"],"relations":{},"dateAdded":"2022-05-01T14:16:53Z","dateModified":"2022-05-01T14:16:53Z"}]" to https://api.zotero.org/users/6666666/items

(5)(+0000006): CookieSandbox: Being paranoid about channel for api.zotero.org

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to api.zotero.org

(5)(+0000518): CookieSandbox: Being paranoid about channel for api.zotero.org

(5)(+0000001): CookieSandbox: No Set-Cookie header received for api.zotero.org

(3)(+0000000): HTTP POST https://api.zotero.org/users/6666666/items succeeded with 200

(3)(+0000001): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(4)(+0000006): Tags haven't changed

(4)(+0000001): Relations have not changed for item 1/9YYK7TGI

(4)(+0000000): Field 'dateAdded' has not changed

(4)(+0000001): Field 'dateModified' has not changed

(3)(+0000000): Collections have not changed for item 9246

(3)(+0000002): Saving to sync cache:

(3)(+0000000): [ "0": { "key": "9YYK7TGI" "version": 7475 "library": { "type": "user" "id": 6666666 "name": "username" "links": { "alternate": { "href": "https://www.zotero.org/username" "type": "text/html" } } } "links": { "self": { "href": "https://api.zotero.org/users/6666666/items/9YYK7TGI" "type": "application/json" } "alternate": { "href": "https://www.zotero.org/username/items/9YYK7TGI" "type": "text/html" } } "meta": { "parsedDate": "2000" "numChildren": 0 } "data": { "key": "9YYK7TGI" "version": 7475 "itemType": "journalArticle" "title": "关于统计学习理论与支持向量机" "creators": [] "abstractNote": "" "publicationTitle": "自动化学报" "volume": "26" "issue": "1" "pages": "32-42" "date": "2000" "series": "" "seriesTitle": "" "seriesText": "" "journalAbbreviation": "ACTA AUTOMATICA SINICA" "language": "zh_CN" "DOI": "" "ISSN": "" "shortTitle": "" "url": "https://d.wanfangdata.com.cn/periodical/zdhxb200001005" "accessDate": "2022-05-01T14:16:53Z" "archive": "" "archiveLocation": "" "libraryCatalog": "Wanfang Data" "callNumber": "" "rights": "" "extra": "清华大学自动化系,智能技术与系统国家重点实验室,北京,100084\n中国科学院资助项目\n2004-03-19 （万方平台首次上网日期，不代表论文的发表时间）" "tags": [ "0": { "tag": "ACTA AUTOMATICA SINICA" "type": 1 } "1": { "tag": "张学工" "type": 1 } "2": { "tag": "支持向量机" "type": 1 } "3": { "tag": "机器学习" "type": 1 } "4": { "tag": "模式识别" "type": 1 } "5": { "tag": "统计学习理论" "type": 1 } "6": { "tag": "自动化学报" "type": 1 } ] "collections": [ "0": "9RW23CVL" ] "relations": {} "dateAdded": "2022-05-01T14:16:53Z" "dateModified": "2022-05-01T14:16:53Z" } } ]

(4)(+0000002): INSERT OR REPLACE INTO syncCache (libraryID, key, syncObjectTypeID, version, data) VALUES (?, ?, ?, ?, ?) [1, '9YYK7TGI', 3, 7475, '{"key":"9YYK7TGI","version":7475,"library":{"type":"user","id":6666666,"name":"username","links":{"alternate":{"href":"https://www.zotero.org/username","type":"text/html"}}},"links":{"self":{"href":"https://api.zotero.org/users/6666666/items/9YYK7TGI","type":"application/json"},"alternate":{"href":"https://www.zotero.org/username/items/9YYK7TGI","type":"text/html"}},"meta":{"parsedDate":"2000","numChildren":0},"data":{"key":"9YYK7TGI","version":7475,"itemType":"journalArticle","title":"关于统计学习理论与支持向量机","creators":[],"abstractNote":"","publicationTitle":"自动化学报","volume":"26","issue":"1","pages":"32-42","date":"2000","series":"","seriesTitle":"","seriesText":"","journalAbbreviation":"ACTA AUTOMATICA SINICA","language":"zh_CN","DOI":"","ISSN":"","shortTitle":"","url":"https://d.wanfangdata.com.cn/periodical/zdhxb200001005","accessDate":"2022-05-01T14:16:53Z","archive":"","archiveLocation":"","libraryCatalog":"Wanfang Data","callNumber":"","rights":"","extra":"清华大学自动化系,智能技术与系统国家重点实验室,北京,100084\n中国科学院资助项目\n2004-03-19 （万方平台首次上网日期，不代表论文的发表时间）","tags":[{"tag":"ACTA AUTOMATICA SINICA","type":1},{"tag":"张学工","type":1},{"tag":"支持向量机","type":1},{"tag":"机器学习","type":1},{"tag":"模式识别","type":1},{"tag":"统计学习理论","type":1},{"tag":"自动化学报","type":1}],"collections":["9RW23CVL"],"relations":{},"dateAdded":"2022-05-01T14:16:53Z","dateModified":"2022-05-01T14:16:53Z"}}']`

**Comment by l0o0** [comment]
同学好，我看到你提供的日志中，有creators 的字段，在保存的条目中没有对应的作者信息么？
