### ISSUE TITLE
在知网搜索界面无法提取PDF，显示 ×Full Text PDF

### ISSUE THREAD

**Issue by GuardKing** [l0o0/translators_CN#103]
之前在知网界面可以直接提取PDF，无论是期刊还是学位论文，现在不行了，显示×Full Text PDF。只有在详情界面可以成功提取到期刊的PDF，学位论文在详情界面只能提取CAJ文件。

但是在英文版知网入口，改为繁体字后，可以直接在搜索界面提取PDF，学位论文也可以直接提取PDF。

![1](https://user-images.githubusercontent.com/104762946/166222422-a5e20386-238e-4f65-8542-b6c17b3e41d3.jpg)

![2](https://user-images.githubusercontent.com/104762946/166222428-678d8ddb-18a0-484e-a306-8d43b4227418.jpg)

**Comment by spongyclam** [comment]
同

**Comment by hanliren** [comment]
是的，现在确实是这样，用不了了，但是我在海外版，用这个还是没问题的，学校的IP也能正常显示

**Comment by hanliren** [comment]
> 
忘记说了，不用改成繁体，我这就是简体中文，海外版就能用

**Comment by 049api** [comment]
我也是之前总是抓取不成功，各种方法都试了也没用，后来直接换成英文的，没想到就可以了。。。

**Comment by l0o0** [comment]
知网附件下载，有的同学能成功，有的失败。Zotero Connector 插件抓取时，除了下载链接，其他能修改的参数不多，代码里能处理地也就差不多这样了。造成这种情况还是因为知网那边修改了下载附件的请求参数，不适合 Zotero Connector 进行下载。

**Comment by kongdd** [comment]
相同的情况，没想到切换到海外版就能成功了。

**Comment by l0o0** [comment]
https://github.com/l0o0/translators_CN/commit/99508f5339bddff7e124e346bd5093c2f4c92430 搜索页面国内仅支持CAJ
