### ISSUE TITLE
百度学术期刊论文以外文献类型

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#105]
1、会议论文（百度学术和知网），未添加学术会议名称和会议地点，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=99d353b9677f0d0287e051e400aea729&site=xueshu_se)。

2、学位论文统一归类到博士论文，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=3f9bd602ac5e8d658307fd3708fed410)。

3、图书，没有添加ISBN，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=59a44b761c61d8a9033990e15aa8eca6)。

4、专利，未能识别，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=b11b0a933ef004fff0f56bf0e864b69e)。

5、标准，抓取失败，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=160v0040de7d06c0640g0g20ta759296)。

6、成果报告，无法识别，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=1b0d02509s6u0c80b77u0440h0651943)。

7、学术期刊或论文
7.1 学术期刊关键词，最好是 拆分，[例如](https://xueshu.baidu.com/usercenter/paper/show?paperid=9b812f6bf1f453284a1c72081c4bd18c&site=xueshu_se)
需要将 “沙尘天气 华北 遥感 GIS” 拆分成4个关键词

https://github.com/l0o0/translators_CN/blob/8ca7b74a5cdd811d7c2eecfd9042b97c39d9f86a/translators/Baidu%20Scholar.js#L116

替换成 
`newItem.tags = doc.querySelector("p.kw_main").innerText.split(" ");	`

似乎除了学术论文之外，其余的学位论文、会议论文都没有抓到关键词，估计要手动从网页抓取。
7.2 学术论文无 ISSN号

注：百度学术左侧可以选择文献的类型（期刊、学位、会议、图书、专利、标准、成果报告）。

**Comment by pixiandouban** [comment]
请求：

百度学术 增加识别 学者主页，类似 [Google Scholar profile](https://github.com/zotero/translators/blob/23b2f425845b7cb9ab1c4a3425ddaddaedb9d156/Google%20Scholar.js#L88-L101)，举例  [例1](https://xueshu.baidu.com/scholarID/CN-BL73V7NJ)

**Comment by pixiandouban** [comment]
同 #68

**Comment by yfdyh000** [comment]
以及[报刊文章](https://xueshu.baidu.com/usercenter/paper/show?paperid=f4423dadd27ee5bdf386006d0791548d)，似乎页面中无法辨别出类型。

**Comment by jiaojiaodubai** [comment]
以上讨论已在 #254 完成。
