### ISSUE TITLE
万方医学

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#110]
虽然最近修改（[1](https://github.com/l0o0/translators_CN/commit/2854fb195037438a5cc691ad032bc93e583063b0)、[2](https://github.com/l0o0/translators_CN/commit/006b7983d782a6fd6ea628eacebc09e81f8c7f42)）了，不过好像还是有文章无法抓取。见文章[1](http://med.wanfangdata.com.cn/Paper/Detail?id=PeriodicalPaper_zhyfyx201306003&dbid=WF_QK)、[2](http://med.wanfangdata.com.cn/Paper/Detail/PeriodicalPaper_PM21270037)。

似乎英文期刊URL与中文的不同。

**Comment by pixiandouban** [comment]
@l0o0 @l0o0 似乎“[jasminum](https://github.com/l0o0/jasminum)”下载器可能又问题，下载完之后本地文本内容变成“The content may contain violation information”，把脚本清空了。[这里](https://www.livejq.top/2022/building-code-hosting-with-docker-gitea)说 可能和 Gitee 有关？ 这段如果你看到可以删除，没看到你邮箱。

**Comment by l0o0** [comment]
我昨天也发现了，我一直以为当时我的网络不好。我回家后也发现这样，我怀疑 gitee 觉得我的代码可能有问题，不能公开。我准备换个源。

pixiandouban ***@***.***> 于2022年10月14日周五 17:11写道：
