### ISSUE TITLE
可能需要调整知网文献原文附件下载判断逻辑

### ISSUE THREAD

**Issue by tanchangde** [l0o0/translators_CN#111]
不同的用户在知网文献详情下可下载的原文类型是不一样的。就 PDF 与 CAJ 而言，有好几种组合。希望根据详情页面展示的可下载文件类型下载，比如同时有 PDF 与 CAJ，则优先下载 PDF，而只有 CAJ 则优先下载 CAJ，没有则直接不尝试下载附件。

但目前 CNKI.js 的附件下载逻辑似乎没有考虑这个情况，基本是直接尝试下载 PDF。

## 	10.27312/d.cnki.gshsu.2021.002419

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2jrxyv97nj21ez0u0gre.jpg)

## 基金经理变更的驱动机制与市场异质性——基于1726只公募基金的实证检验

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2jryujobzj21r70u0106.jpg)

**Comment by l0o0** [comment]
感谢同学的建议。目前我们这是默认PDF，因为之前知网的下载链接，PDF和CAJ的下载地址是可以互换的。不过现在详情页那里的下载链接已经更新过，并没有互换的可能。在搜索页面和海外知网页面，还是保留原来的下载链接。这个下载地址，确实应该重新考虑下。

**Comment by tanchangde** [comment]
> 感谢同学的建议。目前我们这是默认PDF，因为之前知网的下载链接，PDF和CAJ的下载地址是可以互换的。不过现在详情页那里的下载链接已经更新过，并没有互换的可能。在搜索页面和海外知网页面，还是保留原来的下载链接。这个下载地址，确实应该重新考虑下。

期待更新 :)
