### ISSUE TITLE
读秀支持期刊、报纸、学位论文等文献类型和校园外访问

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#114]
1、看了目前移植过来的读秀（Duxiu.com）的translator，只支持图书的题录信息，建议把常用的期刊、报纸、学位论文也加进来。应该可以参考[全国图书参考咨询联盟](https://github.com/l0o0/translators_CN/blob/master/translators/SuperLib.js)或者移植相关代码。感觉读秀算是全图联的收费版。

2、校园外访问读秀，有些网址不太规范，不过结果都有*Detail.jsp?dxNumber=。

https://github.com/l0o0/translators_CN/blob/8ca7b74a5cdd811d7c2eecfd9042b97c39d9f86a/translators/Duxiu.js#L5

```^https?://((?!ucdrs).)*/(bookDetail|JourDetail|thesisDetail|CPDetail|NPDetail)\\.jsp\\?dxNumber=```
自己改的匹配，其中前面排除了全国参考咨询联盟。

**Comment by woooooog** [comment]
感觉读秀的translator经常不能工作，全国图书馆参考咨询联盟反而时常能工作。

**Comment by pixiandouban** [comment]
> 感觉读秀的translator经常不能工作，全国图书馆参考咨询联盟反而时常能工作。

当然，看目前读秀只适配了标准网站的图书页面，应该参考CNKI来修改，全图联适配的文献类型比较多。

**Comment by l0o0** [comment]
是否和这个issue 有关联 https://github.com/l0o0/translators_CN/issues/118

**Comment by pixiandouban** [comment]
> 是否和这个issue 有关联 #118

感觉没怎么有关联。

**Comment by yfdyh000** [comment]
#158 已支持。
"校园外访问"未弄，不确定界面结构是否有通用性，或者需要逐个支持？

**Comment by pixiandouban** [comment]
@l0o0 @yfdyh000 等你把基本的弄好了，我再试试修改一下校外代理。校外代理就是前缀网址不是标准的 **.duxiu.com/**。

比如，期刊文章 天气.DVD光驱复活术[J].电脑采购周刊,2001,(第47期) ，[网址](https://jour-duxiu-com-443.bake1.wor1dbwvwvvrrnm.top/JourDetail.jsp?dxNumber=100145819435&d=9C028FD1F4D011414ABFA5A77A8E1FDD)

**Comment by yfdyh000** [comment]
PR 158目前没什么要动。
如果页面结构不变，只需调整正则来匹配常用域名或特定格式的网址，后者可能增加误触发的概率，前者不易维护。
建议先尝试官方的代理设置功能，参考 https://www.linxingzhong.top/posts/2020-2-26/ 。我没有测试环境，不确定能否适用于脚本中的url判断。

**Comment by jiaojiaodubai** [comment]
更多条目和VPN网址支持已在 9bdf38e2dcef72e8e80accc68e8f24f787d4543b 完成。
