### ISSUE TITLE
知网搜索页面无法获取PDF

### ISSUE THREAD

**Issue by zwbpu** [l0o0/translators_CN#115]
在知网搜索页面同时获取多篇论文时（插件是文件夹图标），仅能够获取题录等元数据，无法抓取PDF。（尝试过更新扩展、换浏览器和重新替换CNKI.js等文件，都没有用。

**Comment by Chendh1999** [comment]
英文版也试了还是不行

**Comment by l0o0** [comment]
@realzsy @Chendh1999 两个同学，复制下网址和截图。看看是不是网址没匹配上，还是因为知网新旧版的问题

**Comment by VivienBH** [comment]
这里试了，英文版可以，但是中文版搜索页面没法抓取PDF。

**Comment by VivienBH** [comment]
这里试了，英文版可以，但是中文版搜索页面没法抓取PDF。
中文版网址：
https://kns.cnki.net/kns8/defaultresult/index
英文版网址：
https://oversea.cnki.net/kns/defaultresult/index

**Comment by l0o0** [comment]
PDF和CAJ的下载，这里有很多因素影响。之前知网的下载很简单，只要找到下载链接，就可以方便在Zotero 里下载。后来知网升级了下载链接，所以就出现了下载时好时坏的情况，不好解决。

**Comment by l0o0** [comment]
目前搜索页面，国内知网只提供CAJ格式，文献详情页面可提供PDF，
