### ISSUE TITLE
无法响应非直接登录知网的网址-附自行解决方案

### ISSUE THREAD

**Issue by Rithen** [l0o0/translators_CN#117]
对于非官网登录，比如我是校web式vpn登录，所以地址栏会看到并没有知网网址（"kns.cnki.net"），这样脚本就无法直接进行抓取。观察地址栏地址，我们的还是静态的地址，所以直接在CNKI.js文件内把知网网址字段替换成对应静态网址就好了。

**Comment by pixiandouban** [comment]
[CNKI](https://github.com/l0o0/translators_CN/blob/master/translators/CNKI.js)目前是通过匹配```(kns8?/defaultresult/index|kns8?/AdvSearch|kcms/detail|KXReader/Detail\\?|KNavi/|Kreader/CatalogViewPage\\.aspx\\?)```来判断的，不是直接通过域名。

**Comment by s-leeq** [comment]
你好，我校通过VPN访问的知网网站可以被这个正则匹配，但是仍然无法在Connector中相应，请问是什么原因呢？我在Debug Output Logging中找不到类似的错误信息，如果有地方可以查看匹配的日志，请问该在哪里找呢？

**Comment by l0o0** [comment]
> 你好，我校通过VPN访问的知网网站可以被这个正则匹配，但是仍然无法在Connector中相应，请问是什么原因呢？我在Debug Output Logging中找不到类似的错误信息，如果有地方可以查看匹配的日志，请问该在哪里找呢？

@s-leeq 可以把你们学校登录VPN访问后的网址发我，我测试一下

**Comment by s-leeq** [comment]
> > 你好，我校通过VPN访问的知网网站可以被这个正则匹配，但是仍然无法在Connector中相应，请问是什么原因呢？我在Debug Output Logging中找不到类似的错误信息，如果有地方可以查看匹配的日志，请问该在哪里找呢？
> 
> @s-leeq 可以把你们学校登录VPN访问后的网址发我，我测试一下

```
https://ywyc.lib.ctgu.edu.cn/https/19rXDUnu0zowe8ObUzgEvAGzOmZS0uvzt/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKu87-SJxoEJu6LL9TJzd50lM-574cO5yoz06vGq-R3jrl3_ir9470UiYN6GeFTCXkxAvq5q0eDtM&uniplatform=NZKPT
http://210.42.42.77/s/net/cnki/kns/G.https/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iLik5jEcCI09uHa3oBxtWoHqt8bD5jRO0hhsuKZ3od5TdQ3HaVX7r55EjlStzPLS9&uniplatform=NZKPT&;x-chain-id=87xmyn1myj9c
```
麻烦查看一下，谢谢！

**Comment by l0o0** [comment]
@s-leeq 
![图片](https://user-images.githubusercontent.com/2743744/222965398-dea484d7-8af5-45eb-a93d-d911a8e000c5.png)
我测试了你提供的2个网址，是能正确识别的。你看看你的知网翻译器版本，是什么时间的？
