### ISSUE TITLE
全国图书馆参考咨询联盟js文件命名

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#118]
查了一下 superlib.net 是超星云图书馆的域名（见[站长之家](https://icp.chinaz.com/superlib.net)），托管在这之上的有其他的图书馆或联盟，如[广州地区高校图书馆联盟](http://www.th.superlib.net/)、[云南省文献资源共享与服务平台(百链)](http://www.yn.superlib.net)、[医学电子文献平台](https://www.szyx.superlib.net/等)。

全图联是否要重命名到 UCDRS或ucdrs.superlib.net，虽然另外几个平台可能大多数用不到。

因为IP地址限制，没有经过测试，如果这些平台的结构都是一样的话，或许可以统一叫 superlib.net。

**Comment by woooooog** [comment]
其他的，比如广州地区高校图书馆联盟，东莞图书馆啥的，其实使用起来还是很好用的。兄能否写一个统一使用的translator？感觉很受用。感谢。

**Comment by l0o0** [comment]
@woooooog 加群联系我617148016

**Comment by l0o0** [comment]
@pixiandouban 同学的意思是不是 全国图书馆联盟这个网址，可能在不同学校或地方是不同的？

**Comment by woooooog** [comment]
应该是，相同的技术，不同的马甲。（卖给不同的单位，使用不同的封面）
你比较一下：
1.东莞图书馆文献检索 (superlib.net)<http://www.dglib.superlib.net/>
2. 学术搜索 (duxiu.com)<http://www.duxiu.com/>
还有很多网站，其实都是基于读秀的这个网站。看能不能整合一下。

发件人: ***@***.***>
发送时间: 2022年6月16日 11:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [l0o0/translators_CN] 全国图书馆参考咨询联盟js文件命名 (Issue #118)


@pixiandouban<https://github.com/pixiandouban> 同学的意思是不是 全国图书馆联盟这个网址，可能在不同学校或地方是不同的？

―

**Comment by pixiandouban** [comment]
> @pixiandouban 同学的意思是不是 全国图书馆联盟这个网址，可能在不同学校或地方是不同的？

全国图书馆参考联盟的网址是 ucdrs.superlib.net 或者 ucdrs.net，不过单独只说 superlib.net 应该不是 全国图书馆参考联盟的。另外目前的全图联的检索平台是基于读秀和百链的（超星旗下），内容和读秀差不多。

**Comment by l0o0** [comment]
@pixiandouban 我理解你的意思了，ucdrs 是 superlib 的子集，目前用的应该是UCDRS或ucdrs.superlib.net 。 既然命名不规范，那更正也是正常的。我之前不了解这么多背景。感谢同学的建议

**Comment by l0o0** [comment]
最近在重新整理各类转换器的问题。上面提到的各类联盟网站，有没有相关的账号可以测试的 @pixiandouban @woooooog 

因为转换器主要依赖网址识别，如果网址类似，而且结构也一样，那合并起来也没有问题

**Comment by pixiandouban** [comment]
superlib.net 系列的也许可以合并。读秀应该不同。另外  #114 读秀应该多支持一些类型。

**Comment by jiaojiaodubai** [comment]
> superlib.net 系列的也许可以合并。读秀应该不同。另外 #114 读秀应该多支持一些类型。

已经在 0552a7cacefdb1d6bad9f39fba77cdfff3cecdfb 完成。此外，读秀和参考联盟的数据服务商虽然一样，界面也相似，但HTML元素的命名规则不一，当前已经将二者完全拆分，不过确实有部分代码可以互相借用。
