### ISSUE TITLE
增加 人大复印报刊资料

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#119]
举例，[1](https://www.rdfybk.com/qw/detail?id=789423)

**Comment by doubanchan** [comment]
该数据库需要订阅之后才可以访问，可以通过[中国国家图书馆](http://read.nlc.cn/outRes/outResList?type=%E5%85%A8%E9%83%A8&searchName=%E4%BA%BA%E5%A4%A7%E5%A4%8D%E5%8D%B0)访问。不过这种文摘/复印类非原始出版数据库可能要想想各个字段如何填写。
