### ISSUE TITLE
在访问 Google Scholar 镜像站时使用 Zotero

### ISSUE THREAD

**Issue by gaospecial** [l0o0/translators_CN#120]
有一些 Google Scholar 镜像站，如：<https://sc.panda321.com/>， 该如何让 Zotero 识别呢？

**Comment by pixiandouban** [comment]
将 [Google Scholar.js](https://github.com/zotero/translators/blob/master/Google%20Scholar.js) 中第5行的target修改成，其他镜像应该也类似
```
	"target": "^https?://(scholar[-.]google[-.](com|cat|(com?[-.])?[a-z]{2})(\.[^/]+)?|sc\.panda321\.com)/(scholar(_case)?\?|citations\?)",
```

**Comment by l0o0** [comment]
仓库有有一个GFSOSO的翻译器，同学可以参考看看，主要还是要修改target，同时注意下ID和label 最好也修改一下，这样都修改过后相当于一个新的翻译器了，可以把文件名也换成镜像站的。这样Google 学术原来的翻译器还是可以用。
