### ISSUE TITLE
我们学校的网站似乎抓取不了CNKI期刊条目和PDF

### ISSUE THREAD

**Issue by Shapeno** [l0o0/translators_CN#122]
我们学校的检索地址是：http://182.150.59.104:8888/https/77726476706e69737468656265737421fbf952d2243e635930068cb8/kns8/defaultresult/index
抓取不了期刊条目，抓下来还是快照

**Comment by Shapeno** [comment]
Pull Request：https://github.com/l0o0/translators_CN/pull/112 经测试可以解决此问题

**Comment by l0o0** [comment]
这是搜索页面，详情页面这样修改有问题么？

**Comment by Shapeno** [comment]
> 这是搜索页面，详情页面这样修改有问题么？

详情页没有问题，pdf也能导入
