### ISSUE TITLE
soopat登录高级用户账户时抓取不了soopat上的信息

### ISSUE THREAD

**Issue by netdog2019** [l0o0/translators_CN#124]
同一篇专利，登录高级用户账户后是下面的地址，此时抓取网页的信息到zotero时出错，提示“使用 Soopat保存时发生错误。尝试使用 Save as Webpage 保存。”，但是它能识别出来显示是专利的图标。
http://plus.soopat.com/Patent/201610347557
但是不登录时是下面的地址，此时抓取网页的信息到zotero时正常，但是不登录的话，下载不了pDF文件，所以能否修改一下js脚本，让它能识别高级用户登录后的网址？毕竟好像只差个www1和plus的区别。我看了一下，想修改，但发现不知道从哪下手，完全看不懂。感谢作者提供这么好的translator。
http://www1.soopat.com/Patent/201610347557

**Comment by l0o0** [comment]
@netdog2019 soopat网站开始时都能下载PDF，后面高级用户才可下载PDF。我们这边没有相关账号去测试，所以翻译器也没有更新。

**Comment by leeray918** [comment]
> 

你好，我可以提供一个短期的高级账户，如果您有时间开发的话。
谢谢！
ps：目前专利之星普通账户还是可以用，而且能自动下载专利。非常感谢！

**Comment by l0o0** [comment]
@leeray918 感谢支持，可能把相关信息发送到我的邮箱 linxzh1989@gmail.com

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/227156880-a9363fce-f2e1-41b0-bbd1-4ba03cab39a2.png)
![图片](https://user-images.githubusercontent.com/2743744/227156895-836f1c3b-de2e-4428-aa96-cab46a508527.png)
@leeray918 @netdog2019 两位同学看看，保存的字段有没有异常或遗漏的。不好放置的字段都放到extra栏里
