### ISSUE TITLE
请求增加「人民日报图文数据库」

### ISSUE THREAD

**Issue by TomBener** [l0o0/translators_CN#128]
网站名称：人民数据-人民日报图文数据库（1946-2022)

网址：http://data.people.com.cn/rmrb

示例文章《[尽管说真话难……](http://data.people.com.cn/pd/rmrb/detail.html?id=c9450f99135f429aa0866fc120ff2da2)》

![photo_2022-09-20 10 42 22](https://user-images.githubusercontent.com/49151155/191155699-d1a1af51-2027-4e91-87b6-e4507d61d55a.jpeg)

**Comment by pixiandouban** [comment]
弄了个 [初步版本](https://github.com/pixiandouban/translators/blob/e6ba0d575744659a46fa42ebd49bc14c29995f0e/Renmin%20Ribao%20Data.js)，请 @l0o0 @zepinglee 帮忙完善。

**Comment by l0o0** [comment]
@pixiandouban 感谢豆瓣的工作，不过我对那个英文名有点疑问， Renmin Ribao Data 还是People's Daily

**Comment by l0o0** [comment]
@TomBener 现在怎么要登录了

**Comment by TomBener** [comment]
@l0o0 似乎一直都要登录才能用，但似乎没有个人注册方式，只能通过机构 IP 使用。

**Comment by doubanchan** [comment]
> @pixiandouban 感谢豆瓣的工作，不过我对那个英文名有点疑问， Renmin Ribao Data 还是People's Daily

我写那个似乎不太行，还需要人帮忙改一下。

**Comment by jiaojiaodubai** [comment]
可以指出有什么问题吗？我会在[标准化进程](https://github.com/l0o0/translators_CN/issues/113)中一并解决。

**Comment by doubanchan** [comment]
[People's Daily.js](https://github.com/l0o0/translators_CN/blob/master/People's%20Daily.js)，只写了一半，然后就放那了。

**Comment by jiaojiaodubai** [comment]
已在 8a4056eb4c4f35417bdc5bb0192fc5e2119e1e1c 完成。有些页面我没有访问权限，可能会有所疏漏。

**Comment by doubanchan** [comment]
@jiaojiaodubai 整版（比如[2023年12月15日 第4版](http://data.people.com.cn/rmrb/20231215/4)）的似乎没有抓取成功？搜索页面的multiple需要权限，可以暂时不管。

**Comment by jiaojiaodubai** [comment]
有整版引用的情况？似乎都是引具体篇目的吧。最新的版面开放浏览，那里的多条目我可以正常抓取。
![Uploading image.png…]()

**Comment by doubanchan** [comment]
手动下载js文件替换之后，可以在整版抓了。
