### ISSUE TITLE
申请添加国家标准全文公开系统的抓取

### ISSUE THREAD

**Issue by tangxunding** [l0o0/translators_CN#132]
那个国家图书馆跳转下载、抓取标准规范信息的translator好像失效了。https://openstd.samr.gov.cn/

**Comment by zepinglee** [comment]
目前没有 <https://openstd.samr.gov.cn> 对应的转换器。

我在 #133 中添加了 <https://std.samr.gov.cn> 的转换器，可以在此基础上修改 openstd 的版本。

**Comment by zepinglee** [comment]
在 #140 中添加。

另外我发现“国家标准全文公开系统”（<https://openstd.samr.gov.cn/>）缺少行业标准等信息，所以建议优先使用“全国标准信息公共服务平台”（<https://std.samr.gov.cn/>）。

**Comment by lychichem** [comment]
目前使用的标准转换器有个小问题，如果一个标准号的搜索结果有多个，在非标准详情页面能够触发转换器的识别，但是无法成功抓取。例子：https://std.samr.gov.cn/search/std?tid=&q=GB%2FT%2017473 。建议的修改方案如下：

1. 如果想优雅，那就让标准搜索结果页面能够识别多个结果并选择导入哪个
2. 如果想偷懒，那就把匹配链接改成标准详情页（`https://std.samr.gov.cn/gb/search/gbDetailed`开头的链接）

**Comment by jiaojiaodubai** [comment]
该issue的申请和问题已分别在#140 和#268 完成
