### ISSUE TITLE
申请添加对“智慧芽”和“合享"外链专利信息的抓取

### ISSUE THREAD

**Issue by psychech** [l0o0/translators_CN#135]
“智慧芽”和“合享"是业内非常重要的两个商业专利数据库。
虽然需要支付较高费用才可登陆使用，但它们提供无需登录即可查看专利信息的外部链接。

希望开发者能添加对“智慧芽”和“合享"的外链专利信息的抓取，以便形成条目导入到Zoreto中。

以下是“智慧芽”和“合享"的外链示例：
- 智慧牙外链示例：https://analytics.zhihuiya.com/patent-view/abst?patentId=198a817b-c6c7-4e38-a42b-c8f1f52a6a47
- 合享外链示例：https://www.incopat.com/detail/init2?formerQuery=Sd%2BCq01dFYrvU%2F97nfhhT%2FR0OjOTHMZL&local=zh

谢谢。

**Comment by jiaojiaodubai** [comment]
那就只能抓取单条目喽？
