### ISSUE TITLE
申请支持科学文库网站的图书条目抓取

### ISSUE THREAD

**Issue by hphGithub** [l0o0/translators_CN#138]
希望开发者能添加对[科学文库](https://book.sciencereading.cn/shop/main/Login/shopFrame.do)的抓取，以便形成图书条目导入到Zoreto中。

- 科学文库示例：[声学学科现状以及未来发展趋势](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BC4788089334E83A5E053020B0A0A2860000)

**Comment by jiaojiaodubai** [comment]
PubScholar中已经包含科学文库的内容

**Comment by tangxunding** [comment]
PubScholar没有科学文库自己更新快，而且科学文库有权限的话，可以在页面直接下载PDF阅读。 @jiaojiaodubai

**Comment by tangxunding** [comment]
PubScholar没有科学文库自己更新快，而且科学文库有权限的话，可以在页面直接下载PDF阅读。 @jiaojiaodubai

**Comment by jiaojiaodubai** [comment]
OK，那我做一个

**Comment by jiaojiaodubai** [comment]
@tangxunding 我基本上完成了，但是我没有下载权限，无法继续完成下载附件那部分的代码，你能在有权限的环境下打开科学文库的网页，然后<kbd>Ctrl</kbd> + <kbd>S</kbd>保存一个`.mhtml`文件然后压缩发给我吗？（因为文件中可能包含机构账户名等隐私信息，请发到邮箱<jiaojiaodubai23@gmail.com>）

**Comment by jiaojiaodubai** [comment]
已在 #296 提交，请审查。

**Comment by tangxunding** [comment]
科学文库登陆后.zip: http://xiazai.tangzhitu.cn/f/25255611-1012363633-2f66cb?p=7932 (访问密码: 7932)

只能这样了，邮件发不过去。
mx.google.com 拒绝将你的邮件发送到以下邮件地址:
[jiaojiaodubai23@gmail.com (jiaojiaodubai23@gmail.com)](mailto:jiaojiaodubai23@gmail.com)
你的邮件未送达，因为收件人的邮件提供程序拒绝了它。

**Comment by jiaojiaodubai** [comment]
@tangxunding 感谢，我后来找了其他同学帮我测试，转换器已经在 #296 提交，你可以自行下载并按照[这里的方法2](https://zotero-chinese.com/user-guide/faqs/update-translators.html#%E6%96%B9%E6%B3%95-2-%E6%89%8B%E5%8A%A8%E6%9B%BF%E6%8D%A2%E6%96%87%E4%BB%B6%E6%9B%B4%E6%96%B0)进行测试。

**Comment by tangxunding** [comment]
@jiaojiaodubai 已尝试，可以用，就是书太大了，下载要好久。另外，科学文库的PDF下载下来只有15天有效期，还只能用知网的阅读器阅读，后附任一阅读器查看和时间权限解码软件的下载链接和说明网址。
科学出版社电子书下载方法 | Feng's Blog (windsky.tech) https://blog.windsky.tech/2022/02/08/ScienceReading/
如果能够搞成，目录添加、PDF下载、PDF权限改变集成在一起就爽了。
只是建议。

**Comment by jiaojiaodubai** [comment]
按我的理解，转换器只对元数据负责，不应对附件作过多的加工，而且公共开源产品不应该承担这样的法律风险，但我可以继续优化目录抓取的代码，以便抓取到更完整的目录列表，感谢你的建议。
