### ISSUE TITLE
专利之星的翻译器失效了

### ISSUE THREAD

**Issue by Geemiing** [l0o0/translators_CN#139]
目前可以识别网站，但是不能正确建立条目。 错误提示为“使用HighWire2.0保存时发生错误。尝试使用Save as Webpage保存。”

**Comment by Geemiing** [comment]
好吧 是我自己的问题。之前用的是zotero的一个便携版软件，用便携版会发生错误。现在测试了正规的zotero软件，专利之星是没问题的。

**Comment by l0o0** [comment]
同学说的便捷版是什么？我之前没接触过这个版本

Geemiing ***@***.***> 于2022年12月1日周四 22:24写道：

**Comment by Geemiing** [comment]
[这个地方的便携版😂](https://portableapps.com/search/node/zotero)
