### ISSUE TITLE
请问CNKI抓取文献如何关闭自动下载pdf

### ISSUE THREAD

**Issue by qizidog** [l0o0/translators_CN#14]
初入一个领域时会抓取大量的文献以待后期进一步检阅，其中不乏很多学位论文，此时没必要直接下载所有的pdf，故想咨询如何自定义是否开启自动下载pdf。

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/93952606-d7b52880-fd7b-11ea-91bb-3ad3efe81666.png)
@qizidog
