### ISSUE TITLE
中国大百科全书·第三版

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#141]
帮忙把中国大百科全书完善一下，[Encyclopedia of China 3rd.js](https://github.com/pixiandouban/translators/blob/master/Encyclopedia%20of%20China%203rd.js)

**Comment by pixiandouban** [comment]
@l0o0 你看一下，[Zgbk](https://github.com/pixiandouban/translators/blob/5d09f1d5f6d99c3e04a942ee602e6c67a3e7a4aa/Encyclopedia%20of%20China%203rd.js)，是否可以合过来。

**Comment by pixiandouban** [comment]
另外，写了个百度百科的，即 #87

**Comment by jiaojiaodubai** [comment]
已在 #273 完成
