### ISSUE TITLE
豆瓣 translator 的短标题

### ISSUE THREAD

**Issue by zepinglee** [l0o0/translators_CN#142]
目前豆瓣 translator 的短标题是将标题加上书名号。这是为了满足哪个特殊用法吗？

https://github.com/l0o0/translators_CN/blob/57d6a61a4c74e9e5cc472cbc81e2082e72a75df6/translators/Douban.js#L173

但是根据 <https://www.zotero.org/support/kb/item_types_and_fields#general_fields>，段标题通常是去掉副标题后部分，比如 <https://book.douban.com/subject/30280001/>，`title` 为“计算机网络：自顶向下方法”，`shortTitle` 应该为“计算机网络”。这样也更符合 CSL 的要求。

**Comment by l0o0** [comment]
当时同学提供的，并没有我们没有过多研究字段要求，所以有些不规范。这个可以修改

**Comment by zepinglee** [comment]
我来改一下这个吧。

**Comment by zepinglee** [comment]
在 #144 中讨论。
