### ISSUE TITLE
知网网址

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#143]
知网的网址无dbname参数时亦可以正常访问，应该加上这种网址格式匹配。
举例 [一位没有获得诺贝尔奖的杰出作家](https://kns.cnki.net/kcms/detail/detail.aspx?filename=SJWH199103016&dbcode=CJFD)。

**Comment by l0o0** [comment]
![image](https://user-images.githubusercontent.com/2743744/197544847-eb1704c1-52f2-4914-b6fe-e85f5de7f660.png)
只是被隐藏了

**Comment by pixiandouban** [comment]
好像重启电脑之后，好了。

**Comment by pixiandouban** [comment]
@l0o0 今天再次遇到无法匹配的问题…
