### ISSUE TITLE
发现有些文献没办法抓取日期

### ISSUE THREAD

**Issue by honest-chong** [l0o0/translators_CN#145]
文献链接：
https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CAPJ&dbname=CAPJLAST&filename=DWJS20211125000&v=
https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CAPJ&dbname=CAPJLAST&filename=GDYJ2022032400U&v=

https://user-images.githubusercontent.com/117070061/198960457-6b1ee10f-85b5-4793-91f1-4feab12bba01.mp4

**Comment by l0o0** [comment]
非常详细的反馈。

根据你提供的这两篇期刊，都是网络首发
![图片](https://user-images.githubusercontent.com/2743744/198962318-2d624b9b-cf64-466d-85b7-3c7521082472.png)

refwork引用格式里也没有日期字段
![图片](https://user-images.githubusercontent.com/2743744/198961998-d6a83952-55c1-4467-a6fa-1869d648cd9d.png)


如果是已经发表的期刊，会有相关的发表年信息
![图片](https://user-images.githubusercontent.com/2743744/198962608-a15a253f-c48a-4107-9d68-d9c6733768e0.png)

**Comment by honest-chong** [comment]
谢谢你的回复。但是如果没有年份的话引用文献的时候就会有信息缺失，有没有办法在年信息字段为空的时候，自动采用其他的字段呢。

**Comment by l0o0** [comment]
如果这个信息，页面上有，是可以的。你要使用哪里的信息

**Comment by honest-chong** [comment]
我感觉或许DOI号里有年份信息？或者我们可能可以直接用网络首发的时间？我还不太清楚具体能不能用，应该用哪个。亦或是网络文献有特殊的引用格式。这个问题可能得问问科研大牛。

![image](https://user-images.githubusercontent.com/117070061/198981325-366dd73c-f599-4105-a381-46c440e8c5a2.png)

**Comment by kongdd** [comment]
现在好像无法在cnki批量导入了。

**Comment by pixiandouban** [comment]
感觉可以在参数“日期”处填写 网络首发时间，这些论文的期号、卷号在未来才会确定。

**Comment by jiaojiaodubai** [comment]
@l0o0 网络首发还没见刊的文章，Zotero里面已经有“preprint”可以用了，我之前弄ChinaXiv遇到过这样的

**Comment by jiaojiaodubai** [comment]
@honest-chong 已在 6471e94727e56744ac06fa266437d3e25cf189db 完成。

**Comment by zepinglee** [comment]
> @l0o0 网络首发还没见刊的文章，Zotero里面已经有“preprint”itemType可以用了，我之前弄ChinaXiv遇到过这样的

APA 格式中“Advance online publication”和预印本（preprint）格式还是有些区别的，而且 Zotero 的预印本类型没有“期刊名”字段。所以我建议还是使用 journalArticle 类型。
<img width="694" alt="Screenshot 2023-12-12 at 15 45 02" src="https://github.com/l0o0/translators_CN/assets/12290822/5fe73272-0878-4c64-af1d-6932a3cb9ef3">
<img width="698" alt="Screenshot 2023-12-12 at 15 45 31" src="https://github.com/l0o0/translators_CN/assets/12290822/82bdc7e8-420a-4111-b021-14546e7a2f9e">

**Comment by jiaojiaodubai** [comment]
@zepinglee  收到，我对引用规范方面了解不多，非常需要你的review，我将在下一次提交中改回来，但保留这种获取时间的方式

**Comment by zepinglee** [comment]
另外可以在 `Extra` 中填写 `Status: 网络首发`，这样对应于 APA 的 `Status: Advance online publication` 用法。不过目前国内期刊/学校应该没有要求填写“网络首发”的。

**Comment by zepinglee** [comment]
关于网络首发的时间，我看了一下 CSL 的 [spec](https://docs.citationstyles.org/en/stable/specification.html#date-variables)，应该使用 `available-date`，即在 `extra` 中填写 `available-date: yyyy-mm-dd`。我可以更新一下全部的中文 CSL，这样在 `issueded` 缺失时可以正确输出 `available-date`。

> available-date
Date the item was initially available (e.g. the online publication date of a journal article before its formal publication date; the date a treaty was made available for signing)

但是目前官方的 styles 中几乎没有使用 `available-date` 字段的（因为这个字段是新添加的）。如果使用这些样式的话可能会有些问题。

**Comment by zepinglee** [comment]
已更新中文 CSL 样式的 `available-date`，见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/f18b620b4f06b33402c15d26b814223b8c9819db>。
