### ISSUE TITLE
请求熊猫学术翻译器（sc.panda321.com）翻译器

### ISSUE THREAD

**Issue by Xu-Jam** [l0o0/translators_CN#147]

**Comment by pixiandouban** [comment]
参考 https://github.com/l0o0/translators_CN/issues/120#issue-1275946118

**Comment by Xu-Jam** [comment]
试了，没有用。。。

**Comment by l0o0** [comment]
@Xu-Jam 这个网站，看起来是类似谷歌学术，不过我在测试的时候发现，他的接口有点不一样，需要重新把接口URL拼出来。

**Comment by l0o0** [comment]
https://sc.panda321.com/extdomains/scholar.googleusercontent.com/scholar.bib?q=info:TOpIPdPQR8EJ:scholar.google.com/&output=citation&scisdr=CgXCpX0bGAA:AAGBfm0AAAAAY2ewSQo8LQiE0JHYVKValkKCsXELhLqf&scisig=AAGBfm0AAAAAY2ewSXA1pvDib4WpVozEFuJh-5lshI6x&scisf=4&ct=citation&cd=-1&hl=zh-CN

这是bibtex 格式的导出形式

**Comment by l0o0** [comment]
如果可以，使用 谷粉学术 替代

**Comment by Xu-Jam** [comment]
好吧，熊猫学术的优点在于可以收藏文章统一导出，避免抓取量过多导致无法抓取的情况出现

**Comment by pixiandouban** [comment]
https://github.com/zotero/translators/blob/23b2f425845b7cb9ab1c4a3425ddaddaedb9d156/Google%20Scholar.js#L5

@Xu-Jam 

改成双反斜杠

`"target": "^https?://(scholar[-.]google[-.](com|cat|(com?[-.])?[a-z]{2})(\\.[^/]+)?|sc\\.panda321\\.com|xs2\\.dailyheadlines\\.cc)/(scholar(_case)?\\?|citations\\?)",`

**Comment by Xu-Jam** [comment]
可以了，太牛了

**Comment by Xu-Jam** [comment]
我顺手给上传了

**Comment by pixiandouban** [comment]
@l0o0 新建了一个 [Google Scholar Mirror.js](https://github.com/pixiandouban/translators/blob/5848fd6ac16ebdd14016305afff40a364fc52cb3/Google%20Scholar%20Mirror.js#L1-L5)，上面的 sc.panda321.com 虽然可以抓取但是明显比 Google Scholar 速度慢，另外其中有一个域名 xs2.zidianzhan.net，好像抓不到。

**Comment by l0o0** [comment]
@pixiandouban 看来可以把这些谷歌学术的镜像都匹配下来😀

**Comment by Xu-Jam** [comment]
我试了一下您新发布的这个js文件，挺好用的。xs2.zidianzhan.net这个试了可以抓取

**Comment by Xu-Jam** [comment]
> 我试了一下您新发布的这个js文件，挺好用的。xs2.zidianzhan.net这个试了可以抓取
