### ISSUE TITLE
CNKI 网址

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#149]
在target中增加`  |kcms/doi|kcms2?/article`
https://github.com/l0o0/translators_CN/blob/8ca7b74a5cdd811d7c2eecfd9042b97c39d9f86a/translators/CNKI.js#L5

结果
`	"target": "https?://.*?/(kns8?/defaultresult/index|kns8?/AdvSearch|kcms/detail|kcms/doi|kcms2?/article|KXReader/Detail\\?|KNavi/|Kreader/CatalogViewPage\\.aspx\\?)",`

好像都是通过 知网RSS 订阅后生成的网址（前缀分别是 t.cnki.net/kcms/article/abstract?v= 和 kns.cnki.net/kcms2/article/abstract?v=）

参考
[网址举例1](https://t.cnki.net/kcms/article/abstract?v=ecdML96R4FsrKTlhGz_pLfkdPQgBfOJ5etxek8fnchw3lV9_GuEZKBBb39cGFq4cm5WGsXJJDXO2J5ulwTq5oWF2YiBcKXPUlsG3WHrNRxqYDOL3aGM2nuzx2SuNpuhm19i-ZnFsA0I=&uniplatform=NZKPT)

[网址举例2](https://kns.cnki.net/kcms2/article/abstract?v=ecdML96R4FuAh9KEL-yfK48sTgN5AcrkVDRi05GoU710j327o9c7MWGJHzVhUGAghyMwyUomw_FRfr25FTu3k4qH4zGQKh_M-DhTFYfDngswW6ei-zRboDJXtxjVkyZZ)

[网址举例3](https://www.cnki.net/kcms/doi/10.13350/j.cjpb.141123.html)

通过期刊目录访问论文也会生成带有 kcms2/article 前缀的格式。

**Comment by pixiandouban** [comment]
以上的网址格式，是否参照 

https://github.com/l0o0/translators_CN/blob/8ca7b74a5cdd811d7c2eecfd9042b97c39d9f86a/translators/CNKI.js#L178

将 url 修改成上面的格式？
https://github.com/l0o0/translators_CN/blob/8ca7b74a5cdd811d7c2eecfd9042b97c39d9f86a/translators/CNKI.js#L320

**Comment by l0o0** [comment]
这种带v格式的网址，我怀疑是另一种形式的url，把数据库信息隐藏起来。抓取的时候容易出现验证，比较麻烦。网址模板后面可以测试一下，可以把这类网址包括进来

**Comment by l0o0** [comment]
这种带v格式的网址，我怀疑是另一种形式的url，把数据库信息隐藏起来。抓取的时候容易出现验证，比较麻烦。网址模板后面可以测试一下，可以把这类网址包括进来

**Comment by pixiandouban** [comment]
@l0o0 除了网址不同外，数据库的信息（dbcode, dbname, filename）都显示在网页源码中，目前看和其他格式没有区别。

**Comment by l0o0** [comment]
> 

目前来看，就是打开时会出现验证页面，其他是正常的

**Comment by l0o0** [comment]
我根据你上面给的3个示例，在正则表达匹配规则是
```
https?://.*?/(kns8?/defaultresult/index|kns8?/AdvSearch|kcms/detail|KXReader/Detail\?|KNavi/|Kreader/CatalogViewPage\.aspx\?|kcms2?/article/abstract\?v=|kcms/doi/)
```

后面2个规则是新增的，不过我在测试时发现DOI链接，在保存为Zotero条目时，网址会自动变成你给的前2个示例的形式。可能是Zotero自行做了其他处理
