### ISSUE TITLE
建议支持从读秀抓取图书/期刊/报纸/学位论文/会议论文/标准/专利等信息

### ISSUE THREAD

**Issue by ricoeur** [l0o0/translators_CN#15]
www.duxiu.com
体验版即可实现大部分功能

**Comment by l0o0** [comment]
读秀这个之前有个朋友已经分享了[链接看这里](https://github.com/zotero/translators/pull/2050)，可能没有更新。QQ群里的朋友帮忙修改了下，你可以试试这个文件，需要解压。我有空联系下对方，看看能不能把读秀放到这个库里。
[Duxiu.js.zip](https://github.com/l0o0/translators_CN/files/5332141/Duxiu.js.zip)

**Comment by ysmintor** [comment]
@l0o0 https://github.com/l0o0/translators_CN 里为啥没有添加 duxiu 的呢？有时候要增加引文用读秀这个插件非常方便爬取书本的信息呀。

**Comment by l0o0** [comment]
@ysmintor 可以的，我上次没找到联系方式。我过几天把读秀的加进去

**Comment by ysmintor** [comment]
> @ysmintor 可以的，我上次没找到联系方式。我过几天把读秀的加进去

谢谢。读秀原作者是 https://github.com/zotero/translators/pull/2050 这个讨论里的 @zuphilip 吗？应该是没有合并到主 master，每次更新读秀插件就被覆盖了。

**Comment by l0o0** [comment]
是的，不过我没有找到联系方式。官方合并有时候是比较花时间

YorkYu <notifications@github.com> 于2021年1月26日周二 下午2:47写道：

**Comment by April-bear** [comment]
读秀的抓取出问题了，无法抓取图书信息，请核实，谢谢！

**Comment by yfdyh000** [comment]
> 读秀的抓取出问题了，无法抓取图书信息，请核实，谢谢！

用 #158 的版本。

**Comment by April-bear** [comment]
您好，谢谢回复，用#158#后还是不能抓取。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l0o0/translators_CN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l0o0/translators_CN] 建议支持从读秀抓取图书/期刊/报纸/学位论文/会议论文/标准/专利等信息 (#15)





  
读秀的抓取出问题了，无法抓取图书信息，请核实，谢谢！
  
用 #158 的版本。
