### ISSUE TITLE
请求支持本地pubmed数据库

### ISSUE THREAD

**Issue by Louis6161** [l0o0/translators_CN#150]
pubmed为医学常用数据库，[本地pubmed](https://pm.yuntsg.com)为国内公司根据pubmed官方api开发的本地化医学文献检索服务系统。目前在浏览器中点击zotero connector抓取到的是"web page without snapshot"。
可以请求为这个网站写个翻译器吗？谢谢！

**Comment by zepinglee** [comment]
NLM 的 PubMed 没有被墙吧？为何不用官网的？

其次，这种需要登录的网站，测试 translator 也很不方便。

**Comment by Louis6161** [comment]
> NLM 的 PubMed 没有被墙吧？为何不用官网的？
> 
> 其次，这种需要登录的网站，测试 translator 也很不方便。

应该没有被墙，但是本地pubmed功能更多，所以日常都在用这个本地pubmed。如果保存文献还得再切换回pubmed，中间还得转一会。
这个网站好像可以申请个人账号，有效期3个月。
翻译器这边如果也很麻烦就算了吧。😂 谢谢！
