### ISSUE TITLE
请求支持谷歌学术My library页面和semantic scholar的Library页面的抓取

### ISSUE THREAD

**Issue by ritian4399** [l0o0/translators_CN#152]
semantic scholar是一款基于AI技术构建的学术搜索引擎，在人工智能等研究领域常用到。
![image](https://user-images.githubusercontent.com/103869541/204292496-5db6a6a6-b7f7-4a3b-8d5f-91d23a85824f.png)
![image](https://user-images.githubusercontent.com/103869541/204292649-becb2730-f17e-4889-8d98-b4ae2289a45a.png)

**Comment by jiaojiaodubai** [comment]
[Google Scholar](https://github.com/zotero/translators/blob/master/Google%20Scholar.js) 和 [Semantic Scholar](https://github.com/zotero/translators/blob/master/Semantic%20Scholar.js)是[官方仓库](https://github.com/zotero/translators)维护的翻译器，你需要去那里提issue
