### ISSUE TITLE
学校VPN登入知网，期刊能通过zotero connector下载PDF，学位论文则无法下载

### ISSUE THREAD

**Issue by li-shipeng** [l0o0/translators_CN#155]
开发者您好！

问题如标题。zotero的translator和chrome的zotero connector插件均已更新。请问需要提供什么信息以帮助解决该问题。

**Comment by l0o0** [comment]
目前中文知网的学位论文是只有caj格式，可以试试调到海外版，一般可以下载PDF。也可以使用[油猴插件](https://greasyfork.org/zh-CN/scripts/389343-%E4%B8%AD%E5%9B%BD%E7%9F%A5%E7%BD%91cnki%E7%A1%95%E5%8D%9A%E8%AE%BA%E6%96%87pdf%E4%B8%8B%E8%BD%BD/code)
