### ISSUE TITLE
中国知网识别失败的问题

### ISSUE THREAD

**Issue by PanZhanhua** [l0o0/translators_CN#16]
在中国知网添加文献时，部分文献会提示抓取失败。经过我的观察，是url参数的顺序问题。

大部分时候，在知网搜索，并点击结果，url的参数顺序为：
https://kns.cnki.net/kcms/detail/detail.aspx?
**dbcode**=*
&**dbname**=*
&**filename**=*
&**v**=*
这时候保存正常

但有时候，url的参数顺序会变成
https://kns.cnki.net/kcms/detail/detail.aspx?
filename=*
&dbcode=*
&dbname=*
&v=*
这时候保存文献，就会提示失败。

但是我对js及translator都不太熟悉，因此希望作者能修复此问题。

**Comment by l0o0** [comment]
非常感谢这么详细的信息，我会去测试下

**Comment by l0o0** [comment]
@PanZhanhua 同学你好，我这边有个网址是 https://kns.cnki.net/KCMS/detail/detail.aspx?filename=SPZZ201412003&dbcode=CJFQ&dbname=CJFDLAST2015 。你试试这个网址，能正常识别嘛，同时看看你 那个cnki.js的更新时间是不是最新的？

**Comment by PanZhanhua** [comment]
你好，我测试了下。你提供的网址可以正常添加。cnki.js是9月30号的版本，应该是最新的。

这个是我发现问题的文献，我刚刚试了下，依旧无法添加。
https://kns.cnki.net/kcms/detail/detail.aspx?filename=DWJS202008003&dbcode=CJFQ&dbname=DKFXTEMP&v=j8XooEn0frsPyLgNEwgl7%mmd2FjfDge8J8qSAOWq4ZaDH9Q0Oc6zA0wHcaDSyIAXkf2o

我把后面的v=去掉，网址：
https://kns.cnki.net/kcms/detail/detail.aspx?filename=DWJS202008003&dbcode=CJFQ&dbname=DKFXTEMP
也无法添加。

提示这个：
![image](https://user-images.githubusercontent.com/44353455/95699696-c7f07c00-0c77-11eb-8f86-52116439eb3a.png)

**Comment by l0o0** [comment]
@PanZhanhua 原因找到了，因为这个dbname和dbcode不一样导致的。一般dbcode与dbname前4个字符一样。你这个例子是个例外，我可能要修改下识别代码。

**Comment by PanZhanhua** [comment]
好。谢谢你的工作。^-^。

**Comment by l0o0** [comment]
@PanZhanhua 我刚才看了下，你上面那个文章链接奇怪，能正常打开，可是左上角的引用是返回空的结果
![图片](https://user-images.githubusercontent.com/2743744/95701988-9d092680-0c7d-11eb-925e-3eaf5d111859.png)
我估计是这个文章的链接更新了，而你这个可能是之前网络优先发行的，dbname和dbcode之类的是临时的。我又在知网上搜索这个文章，返回的链接是这个 https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2020&filename=DWJS202008003&v=j8XooEn0frtKsGoyvW8KeEg38Uq%25mmd2F3tucueW6UUM7hil%25mmd2BtkqzgjnXFeN%25mmd2FmbbeO4ps 这个链接是可以识别的，你看看。

我看这个文章是8月发行的，可能是这个原因导致查询的信息发生了变化，我这个是用那个引用的API来获取引文数据的。如果API返回空，那应该会出错了。

**Comment by PanZhanhua** [comment]
对哦，这个文章是通过别的文献的参考文献点击进去的，无法添加。

然后我试着在知网直接搜索这篇，的确是可以添加。但是通过别的论文的参考文献点击进来，却无法添加。

然后我观察url。发现通过参考文献点进去，url的参数顺序跟直接搜索的url参数顺序不同。当时以为是url顺序的问题。

![image](https://user-images.githubusercontent.com/44353455/95702717-b317e680-0c7f-11eb-9eb4-7b5b207ad32b.png)


我根据你刚刚的提示，查看这个临时文献，引用API的确是返回空。

但是通过修改右上角的印刷版\录用定稿选项，API有效。是否可以判断：如果引用API为空，则检查是否存在这个选项框。选择另一个选项，看看API是否为空。
![image](https://user-images.githubusercontent.com/44353455/95702633-7f3cc100-0c7f-11eb-8064-0c3adce602d0.png)

![image](https://user-images.githubusercontent.com/44353455/95702607-67653d00-0c7f-11eb-98c7-23031fddb5c8.png)

**Comment by l0o0** [comment]
@PanZhanhua 可以的，我后面看看有没有办法处理一下这个问题

**Comment by l0o0** [comment]
@PanZhanhua  我看了下页面的信息，录用定稿的链接是`/kcms/detail/11.2410.TM.20200528.1430.002.html`，并没有dbcode等信息可以获取。如果硬要获取，会让cnki.js 变得复杂。还是建议手动点击切换录用版的链接。

**Comment by PanZhanhua** [comment]
好。感谢！

我上次还发现，从印刷版切换到定稿，再切换回印刷版，url的dbcode等参数会变成正常的参数而非临时的了。希望这能提供一些思路。。

最后感谢您的付出。🙏
