### ISSUE TITLE
知网中文版获取学位论文caj文件无法直接打开

### ISSUE THREAD

**Issue by JillinJia** [l0o0/translators_CN#162]
**获取论文**：
《黄瓜共表达基因模块的识别及其特点分析》

**zotero中的获取结果**：
<img width="468" alt="image" src="https://user-images.githubusercontent.com/45500811/218315312-39d4450e-ddc0-4532-a77d-b19587c1f56b.png">

**无法直接打开**：
<img width="281" alt="image" src="https://user-images.githubusercontent.com/45500811/218315334-e2d56bdf-f578-46fe-a5d5-c0349b3a5f0c.png">

找到文件位置后，**手动添加.caj后缀**，才可成功打开：
<img width="160" alt="image" src="https://user-images.githubusercontent.com/45500811/218315529-86bf4d07-3ccd-41b3-a8f4-b2222853e4d5.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/45500811/218315431-8de6803c-eb5a-4062-b9a5-6ce61adf76e1.png">

**Comment by zepinglee** [comment]
将该文章的 URL 贴上来

**Comment by JillinJia** [comment]
> 将该文章的 URL 贴上来

https://bar.cnki.net/bar/download/order?id=jBGETXBNdPImvx70aLAuJPYxPoFw%2Bp%2Bi0fIiSrcN6lVnqRDzWk5xZcr2gWP4hlFedIHL2Cy%2BlkEQPNV7YmeogaZkLkctbazBAH%2Br8YgpNUAr4qya3J1MXVAeiRx5Olqse20RE6OVXy1GJ0Ud%2FbKdbUN1tZaOZ9Yf2CwqWvTYvKvMu%2FsTy5QX8vMQEr7plrpCfret%2FY0YC%2B0tu%2B4P0Sf9C3coBQGVUiyBxvQTy79iQIo%3D

**Comment by xigxmmbc** [comment]
我这里有同样的问题, 所有学位论文下载后都没有caj后缀

**Comment by xigxmmbc** [comment]
> 我这里有同样的问题, 所有学位论文下载后都没有caj后缀

解决了, 去掉zotero自带的自动重命名的选项
![image](https://user-images.githubusercontent.com/102339037/224910565-0769f8e7-0531-492a-8d35-bb1ae3b9385f.png)

**Comment by JillinJia** [comment]
现在学位论文好像都可以直接下载pdf版了

**Comment by l0o0** [comment]
CAJ格式会有应对的meme type，我在附件中设置了 `application/caj`，这样双击CAJ附件的时候，应该会自动高系统调用CAJ默认的程序打开。

**Comment by OrlandoZh** [comment]
现在问题是海外知网抓取也是full text caj

**Comment by l0o0** [comment]
把文献搜索页面的网址给我一下 @OrlandoZh

**Comment by l0o0** [comment]
把文献搜索页面的网址给我一下 @OrlandoZh

**Comment by OrlandoZh** [comment]
首页  https://chn.oversea.cnki.net/index/
搜索页面 https://chn.oversea.cnki.net/kns/defaultresult/index

**Comment by jiaojiaodubai** [comment]
2023.11.28知网更新后，此问题应该已经连同翻译器更新被解决？

**Comment by Liuyulun** [comment]
> 我这里有同样的问题, 所有学位论文下载后都没有caj后缀

我也是，请问您解决了吗？

**Comment by Liuyulun** [comment]
> 2023.11.28知网更新后，此问题应该已经连同翻译器更新被解决？

没有解决啊，我这里还需要手动添加.caj后缀
