### ISSUE TITLE
知网论文题录链接过长

### ISSUE THREAD

**Issue by yangtzech** [l0o0/translators_CN#165]
以论文《利用深度学习从面部表情和语音识别抑郁症方法的研究》为例

国内站搜索结果是https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C447WN1SO36whFuPQ0yKi4pXSQlJ_W8wBD9JRPlAs_d8BxIj_TFITuop6xX8eKtyN5ygR9QhjyGzEcdCPTzB8P9b&uniplatform=NZKPT

但是通过
1）搜索结果页面的在线阅读链接https://kreader.cnki.net/Kreader/RedriectPage.aspx?dbCode=cdmd&filename=1023411927.nh&tablename=CDFDTEMP&uid=WEEvREcwSlJHSldSdmVpaVVVQVRCNXJPdk43WDVqYWt2cmlEL041ZExFcz0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4IQMovwHtwkF4VYPoHbKxJw!!
1）点击引用——更多格式进入的页面链接https://kns.cnki.net/dm/manage/export.html?filename=CDFDTEMP!1023411927.nh!1!0&displaymode=NEW&uniplatform=NZKPT 

提取到如下缩短后的链接

https://kns.cnki.net/kcms/detail/detail.aspx?dbname=CMFDTEMP&filename=1022520123.nh

抑或是通过https://chn.oversea.cnki.net/kns/defaultresult/index 或者 https://oversea.cnki.net/index/ 搜索结果网址获取

https://chn.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1023411927.nh&uniplatform=OVERSEA&v=5xnaXCB3FesDCTfzairvIgjUeygfe_txQppxhX0wLp1-UnBxT9pZl9cB1iFgsFaL

这样缩短后的链接在论文里面展示更为美观

**Comment by yfdyh000** [comment]
您似乎指知网搜索结果条目 - “引用”中的“<html>
<body>


APA格式引文 | [1]郭威彤.(2022).利用深度学习从面部表情和语音识别抑郁症方法的研究(博士学位论文,兰州大学).https://kns.cnki.net/KCMS/detail/detail.aspx?dbname=CDFDTEMP&filename=1023411927.nh
-- | --



</body>
</html>”网址更短。

https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C447WN1SO36whFuPQ0yKi4pXSQlJ_W8wBD9JRPlAs_d8BxIj_TFITuop6xX8eKtyN5ygR9QhjyGzEcdCPTzB8P9b&uniplatform=NZKPT 网页源码中，有filename参数，倒是可能用来构造短网址。但也许难以确定网址是否有效、长期有效。分享-复制链接，提供的是有v（唯一标识符）而无文件名参数的kcms2的网址，不确定有何种考量。

**Comment by yangtzech** [comment]
可以参见#34，这条issue中链接还是可以访问的

再就是一个月前我通过zotero获取的文献保存下来的链接还是这样的格式
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2017&filename=1017800399.nh&uniplatform=NZKPT&v=_6BrdAMlRvZj3yuDBZDLEBpj8TuJNLbYjbVgmdWx21N-9aPJU9ZQjlO4sEb2mo82
不知道什么时候变成这样abstract结尾的链接了

**Comment by yangtzech** [comment]
又或者通过知网空间 https://www.cnki.com.cn/index.htm 搜索，得到页面链接 https://cdmd.cnki.com.cn/Article/CDMD-10730-1023411927.htm

**Comment by l0o0** [comment]
@yangtzech 同学的意思是有时抓取知网时保留的URL过长，想得到一个稍短一些的网址，这样在参考文献中引用时，更美观。一般来说，我们需要获取知网的一些参数，那样大概就能拼出知网一篇文章的URL，目前已知的参数有dbcode，dbname，filename。其中dbcode和dbname应该有某种联系，filename应该是唯一的，在知网空间和其他类型的子网站是通用的。#170 中有同学列出了一些材料。
我觉得在转换器translator中自行修改保留的网址，可能会对其他同学造成疑惑。可以设计一个生成短网址的功能，供有需求的同学调用就行

**Comment by yangtzech** [comment]
是的。有这样的功能就可以了。除了通过dbcode之类的拼接，不知道能否直接从知网空间搜索 https://www.cnki.com.cn/index.htm，链接似乎更简洁

**Comment by l0o0** [comment]
只要搞明白他们的规则，应该也是可以

**Comment by yangtzech** [comment]
可以，转换器导入题录时保留原始网址，提供一个转换链接的功能，加入链接可能非永久的说明

**Comment by doubanchan** [comment]
之前提过这个，见 #61。另外 @l0o0 #61 这个issue看来可以关了，已经在 #149 中解决了。感觉 v 可能类似万方数据的网址，将 dbcode、filename 封装起来了。

**Comment by doubanchan** [comment]
@l0o0 知网空间（cnki.com.cn）和 知网（cnki.net）差别太大，不建议使用。我都是直接用插件让其自动跳转到 cnki.net，各种不方便。

**Comment by l0o0** [comment]
> @l0o0 知网空间（cnki.com.cn）和 知网（cnki.net）差别太大，不建议使用。我都是直接用插件让其自动跳转到 cnki.net，各种不方便。

那还是使用知网主站的地址，比较保险

**Comment by jiaojiaodubai** [comment]
已经在 4d75425e3a75650cdefb755a5fb10b52a876bd73 部分支持。实测发现有些链接并不是十分保险（我曾经尝试把test cases里面的链接都改成短的这种形式，但这样导致一些测试用例无法打开）。
