### ISSUE TITLE
为什么我把translators.CNKIPDF改成false之后不能抓取caj格式的全文，但是在网站上直接下载可以获取

### ISSUE THREAD

**Issue by gklzc0608** [l0o0/translators_CN#17]
麻烦大佬答疑一下，谢谢了

**Comment by Lemmingh** [comment]
因为知网的接口改了。

现在的情况是：

* `dflag=pdfdown`: PDF
* `dflag=cajdown`: CAJ

---

这一段需要重写
https://github.com/l0o0/translators_CN/blob/c2de68bec765fad5edc129948d6aefaaaf281df4/translators/CNKI.js#L252-L259

**Comment by gklzc0608** [comment]
我不会改。。。大佬能说的具体一点吗，我把您标黄的部分的“dflag=pdfdown”改成了”dflag=pdfdown:PDF”还是没用，您说的是这个意思吗

发送自 Windows 10 版邮件应用

发件人: Lemmingh
发送时间: 2020年10月18日 0:30
收件人: l0o0/translators_CN
抄送: gklzc0608; Author
主题: Re: [l0o0/translators_CN]=?UTF-8?Q?_=E4=B8=BA=E4=BB=80=E4=B9=88=E6=88=91=E6=8A=8Atranslators.CNKIPDF=E6=94=B9=E6=88=90false=E4=B9=8B=E5=90=8E=E4=B8=8D=E8=83=BD=E6=8A=93=E5=8F=96caj=E6=A0=BC=E5=BC=8F=E7=9A=84=E5=85=A8=E6=96=87=EF=BC=8C=E4=BD=86=E6=98=AF=E5=9C=A8=E7=BD=91=E7=AB=99=E4=B8=8A=E7=9B=B4=E6=8E=A5=E4=B8=8B=E8=BD=BD=E5=8F=AF=E4=BB=A5=E8=8E=B7=E5=8F=96?==?UTF-8?Q?_=28#17=29?=

因为知网的接口改了。
现在的情况是：
• dflag=pdfdown: PDF
• dflag=cajdown: CAJ

这一段需要重写
https://github.com/l0o0/translators_CN/blob/c2de68bec765fad5edc129948d6aefaaaf281df4/translators/CNKI.js#L252-L259

**Comment by Lemmingh** [comment]
我眼花，看错了。打扰了。

**Comment by gklzc0608** [comment]
= = 那是哪有问题呢，有办法解决吗？

发送自 Windows 10 版邮件应用

发件人: Lemmingh
发送时间: 2020年10月19日 10:43
收件人: l0o0/translators_CN
抄送: gklzc0608; Author
主题: Re: [l0o0/translators_CN]=?UTF-8?Q?_=E4=B8=BA=E4=BB=80=E4=B9=88=E6=88=91=E6=8A=8Atranslators.CNKIPDF=E6=94=B9=E6=88=90false=E4=B9=8B=E5=90=8E=E4=B8=8D=E8=83=BD=E6=8A=93=E5=8F=96caj=E6=A0=BC=E5=BC=8F=E7=9A=84=E5=85=A8=E6=96=87=EF=BC=8C=E4=BD=86=E6=98=AF=E5=9C=A8=E7=BD=91=E7=AB=99=E4=B8=8A=E7=9B=B4=E6=8E=A5=E4=B8=8B=E8=BD=BD=E5=8F=AF=E4=BB=A5=E8=8E=B7=E5=8F=96?==?UTF-8?Q?_=28#17=29?=

我眼花，看错了。打扰了。

**Comment by l0o0** [comment]
同学，你是想下载CAJ格式的文件？@gklzc0608

**Comment by gklzc0608** [comment]
@l0o0   是的，我想在zetero导入CNKI文献信息的时候，同时下载CAJ格式全文。

**Comment by l0o0** [comment]
CAJ格式是想在学位论文的时候下载吧？

**Comment by gklzc0608** [comment]
对

**Comment by l0o0** [comment]
@gklzc0608 你看看你的CNKI.js是不是最新的？在代码的243行是这样的`var keepPDF = Z.getHiddenPref('CNKIPDF');`

**Comment by gklzc0608** [comment]
是的，我下的CNKI.js是最新更新的那个版本

**Comment by l0o0** [comment]
问题还存在么 @gklzc0608

**Comment by gklzc0608** [comment]
@l0o0    有，学位论文的PDF和CAJ都下不了，但是期刊的可以= =

**Comment by l0o0** [comment]
@gklzc0608  有没有出现Full PDF Text 的小红叉？如果出现说明，下载过程出现问题，可能是权限或网络原因造成

**Comment by gklzc0608** [comment]
@l0o0   有，那应该怎么解决呢，我之前是可以下的，后面突然就不行了

**Comment by l0o0** [comment]
你可以看看日志里是什么信息？你先打开这知网，然后点击小图标进行下载，这里打开日志窗口
![图片](https://user-images.githubusercontent.com/2743744/99018091-3d5fad00-2594-11eb-9ee7-b294208e9baf.png)

出现小红叉时，看看日志后面是不是出现什么PDF 相关的信息

**Comment by gklzc0608** [comment]
@l0o0   我又刷新了一下translator之后，又可以下PDF了，但是把CNKIPDF改成false之后，还是无法下载CAJ= =，不知道为啥。然后看了一下日志，可能是我没看懂，我没有找到PDF或者CAJ这类关键字，都是full text，也没看到下载成功或者失败的信息，很多信息都是在sync和api在进行交互的提示。

**Comment by l0o0** [comment]
@gklzc0608 要不就下载PDF好了，用我另一个插件也能添加目录信息。你可以试试

**Comment by gklzc0608** [comment]
@l0o0   行，能给个链接吗，大佬

**Comment by l0o0** [comment]
看看这个 @gklzc0608 https://github.com/l0o0/jasminum/releases/tag/v0.0.8

**Comment by gklzc0608** [comment]
@l0o0    OK，弄好了，谢谢大佬。Orz
