### ISSUE TITLE
维普的中文翻译器好久好久没有更新了

### ISSUE THREAD

**Issue by 56125a** [l0o0/translators_CN#173]
维普的中文翻译器更新时间还是2019年，好久好久不更新了，现在已经无法提取条目、下载附件了。

**Comment by l0o0** [comment]
好的，安排

**Comment by 56125a** [comment]
> 好的，安排

感谢大佬

**Comment by yzy1228682367** [comment]
好像现在还是没有办法提取条目。

**Comment by l0o0** [comment]
@yzy1228682367 维普好像有多个版本，你们现在用的是什么版本，有空我更新一下。我昨天看了维普官网，搜索的文献可以用metadata 的转换器来收集。

**Comment by yzy1228682367** [comment]
https://lib.cqvip.com/Qikan/Article/Detail?id=7109808542&from=Qikan_Search_Index
比如这一个就提取不到耶

**Comment by l0o0** [comment]
> 

收到
