### ISSUE TITLE
申请 臺大佛學數位圖書館 的translator

### ISSUE THREAD

**Issue by CallMeNP** [l0o0/translators_CN#174]
哪位能帮忙开发一下这个网站的抓取器么？很多佛教专业的论文只有这里收录了。 https://buddhism.lib.ntu.edu.tw/index.jsp

万分感谢，愿意请喝杯咖啡。

**Comment by l0o0** [comment]
好的，我会加入开发排期。这个网站是只有期刊类型么？我找的这篇，PDF的[下载](https://buddhism.lib.ntu.edu.tw/search/search_detail.jsp?comefrom=homeNewFulltext&seq=667100)是转到知网空间

**Comment by CallMeNP** [comment]
> 好的，我会加入开发排期。这个网站是只有期刊类型么？我找的这篇，PDF的[下载](https://buddhism.lib.ntu.edu.tw/search/search_detail.jsp?comefrom=homeNewFulltext&seq=667100)是转到知网空间

感谢～

这里包含多种内容类型，比如期刊论文、学位论文、专著，等等。其他区别我不确定对zotero开发有没有意义。先对这几种举例：
* 期刊文章： [〈迦旃延氏經〉(Kātyāyana-sūtra) 梵漢對照及其不二中道學理](https://buddhism.lib.ntu.edu.tw/search/search_detail.jsp?seq=542521) pdf下载地址还是台大。
* 学位论文： [《別譯雜阿含》中「欲」一字之使用研究](https://buddhism.lib.ntu.edu.tw/search/search_detail.jsp?seq=642158) pdf 下载是跳转到 [https://hdl.handle.net](https://hdl.handle.net/11296/uvf88n)
* 专著书籍：[「空」、「有」與「有」、「無」 -- 玄學與般若學交會問題之研究](https://buddhism.lib.ntu.edu.tw/search/search_detail.jsp?seq=125907) pdf下载地址也是台大。
* 其他还有连续出版物（等于期刊的一册？）、会议论文等。

pdf的角度来说，下载地址有本站和外链跳转两种。不过我觉得可以不太在意pdf抓取的成功率。

**Comment by tzuifurther** [comment]
ncl.edu.tw 這個很難自動下載

**Comment by tzuifurther** [comment]
對阿，我正在提交此網站，不過連結好像沒有規律

**Comment by l0o0** [comment]
> 

你有发现什么问题么，可以详细列出来交流一下

**Comment by tzuifurther** [comment]
有些是還有外連結，還有一些只有紙本

**Comment by CallMeNP** [comment]
> 有些是還有外連結，還有一些只有紙本 上面[《別譯雜阿含》中「欲」一字之使用研究](https://hdl.handle.net/11296/uvf88n) 下載時跳出[這個](https://ndltd.ncl.edu.tw/cgi-bin/gs32/gsweb.cgi?o=dnclcdr&s=id=%22105FGU00841025%22.&searchmode=basic#XXX) 檔案連結是[這個](https://ndltd.ncl.edu.tw/cgi-bin/gs32/gsweb.cgi/ccd=6qjAOV/brwfull?filename=FRW%257Fde_GGSbNTINZbKS%2597%2593%258D&dbid=FRW%257Fde_GGSbNTI&way=2&attachfile=1)

感覺可以放棄pdf的抓取。這個網站的內容很雜，只有紙本沒有pdf的很多。能夠提取文獻信息已經很實用了。

**Comment by tzuifurther** [comment]
我目前是放棄pdf的抓取，只抓資料，他不像一般的論文網站將資料格式化

**Comment by CallMeNP** [comment]
@jiaojiaodubai 万分感谢！刚刚发现瑞幸咖啡只能赠送给微信联系人。有没有什么方式能在口头之外表达感谢么？就像 https://www.buymeacoffee.com/ 。
