### ISSUE TITLE
下载出来的文件格式还是caj

### ISSUE THREAD

**Issue by guiyou27** [l0o0/translators_CN#175]
在知网上通过Zotero Connector下载到zotero后，发现文件格式还是caj，我想要的是pdf格式，好像默认的就是pdf格式才对，不知道问题出在哪里了

**Comment by l0o0** [comment]
你是在搜索页面下载的还是文献详情页面

guiyou27 ***@***.***> 于 2023年3月27日周一 下午6:06写道：

**Comment by guiyou27** [comment]
在搜索页面下载的

**Comment by l0o0** [comment]
知网国内搜索页面仅有CAJ，PDF链接对Zotero Connector 来处理有点难

**Comment by logan00000000** [comment]
最近确实存在这样的问题，现在使用海外版的知网在搜索页面批量下载也是caj格式

**Comment by l0o0** [comment]
> 最近确实存在这样的问题，现在使用海外版的知网在搜索页面批量下载也是caj格式

我这边没有海外版知网的账号，不能测试，能否截图一下海外版知网的搜索页面
![图片](https://user-images.githubusercontent.com/2743744/229132084-f0bd016a-cb05-4f85-9e59-b07eb3bc6247.png)
学位论文这城也仅有caj么？

**Comment by logan00000000** [comment]
> > 最近确实存在这样的问题，现在使用海外版的知网在搜索页面批量下载也是caj格式
> 
> 我这边没有海外版知网的账号，不能测试，能否截图一下海外版知网的搜索页面 ![图片](https://user-images.githubusercontent.com/2743744/229132084-f0bd016a-cb05-4f85-9e59-b07eb3bc6247.png) 学位论文这城也仅有caj么？

海外版知网与国内知网数据互通，同一账号即可访问

**Comment by l0o0** [comment]
我看知网在搜索页面只有CAJ提供，文献详情页面已经开放PDF和CAJ。可能这是知网最后的倔强。
