### ISSUE TITLE
无法抓取 知乎专栏的正文

### ISSUE THREAD

**Issue by Test202010** [l0o0/translators_CN#177]
![image](https://user-images.githubusercontent.com/73330797/228700788-2e99185c-2815-484c-a6d0-b0388b69b075.png)
无法抓取正文 只能抓取 snapshot

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/228709415-babfc473-5136-4ecc-832b-bf9117e328d8.png)
![图片](https://user-images.githubusercontent.com/2743744/228709484-795ac04c-71ac-420e-8f05-b3bdc437d26e.png)

我这里测试正常，我觉得你应该是没有更新知乎的这个转换器
![图片](https://user-images.githubusercontent.com/2743744/228709565-9fdbe380-e5e1-4e17-9ae4-ecbecc94b8bd.png)

**Comment by Test202010** [comment]
![image](https://user-images.githubusercontent.com/73330797/228711166-afdaf95a-cb9b-4ffd-b23c-d85469f7cb17.png)

我根据您说的 Update 了插件 ，把浏览器的connecter插件也更新了，然后搞定了 多谢！
