### ISSUE TITLE
抓取知乎 生成的Author或者Creator一栏 会有不必要的字符串

### ISSUE THREAD

**Issue by Test202010** [l0o0/translators_CN#178]
不必要的字符串 如下：
, .css-18biwo{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}​.css-1ifz0go{overflow:visible!important;}
推测：应该是 页面解析的时候，所写的规则 不匹配 所致
![image](https://user-images.githubusercontent.com/73330797/229036845-50c3b993-e408-4927-89bc-bd5ace5252bf.png)

**Comment by Test202010** [comment]
作者一栏 字符串过长 ，导致同步时出错

**Comment by l0o0** [comment]
好的，麻烦提供一下链接，我之前测试时没遇到这种情况

**Comment by Test202010** [comment]
https://www.zhihu.com/question/440729199/answer/1702311609
使用插件下载后 作者栏出现长字符串 如图
![image](https://user-images.githubusercontent.com/73330797/229392512-68252ef7-df7e-4adc-ae3b-dcbe4f771b66.png)

**Comment by l0o0** [comment]
更新好了，麻烦测试一下
