### ISSUE TITLE
希望修复新版的万网页面的js

### ISSUE THREAD

**Issue by OrlandoZh** [l0o0/translators_CN#179]
希望修复新版的万网页面的js

![image](https://user-images.githubusercontent.com/70483783/229056613-b2d70b50-0f0f-4008-891a-81e2d38d231b.png)

搜索页面网址

https://s.wanfangdata.com.cn/paper?q=%E6%B5%8B%E8%AF%95

文献页面
https://d.wanfangdata.com.cn/periodical/ChlQZXJpb2RpY2FsQ0hJTmV3UzIwMjMwMzIxEg96Z2NzanMyMDIzMDIwMTcaCHd0NTE2M3dr

**Comment by doubanchan** [comment]
重启一下试试，这边测试没问题。

**Comment by l0o0** [comment]
@OrlandoZh 万方搜索页面有点问题，因为数据应该加密了，爬虫页面时报错。单个文献详情页面应该正常

**Comment by l0o0** [comment]
这个issue先关掉喽

**Comment by OrlandoZh** [comment]
ok
