### ISSUE TITLE
希望能发布 release

### ISSUE THREAD

**Issue by chhlab** [l0o0/translators_CN#18]
建议更新 translator 文件之后发布一个 release，这样可以通过 GitHub 的 watch 功能订阅更新

**Comment by l0o0** [comment]
我后面会有我的Jasminum里面添加更新和下载功能，到时候，可以直接点击更新。等我双11买完东西，有空来更新下

**Comment by Reveanime** [comment]
这个方案比release好👏

**Comment by l0o0** [comment]
这个插件已经有下载更新下载功能了 https://github.com/l0o0/jasminum
