### ISSUE TITLE
【请添加】还一个国家出版署的全部出版物的目录源

### ISSUE THREAD

**Issue by ottilis** [l0o0/translators_CN#181]
【请添加】还一个国家出版署的全部出版物的目录源。书目应该比较全面，对外开放查询，地址：
`https://book.cppinfo.cn/home/index`

国家出版发行信息公共服务平台

海量

书目上传量 145.16万 本 销售数据量 4.46亿 条 库存数据量 108.47亿 条 交易数据量 21.39万 次

**Comment by jiaojiaodubai** [comment]
我写了一个（[pull 214](https://github.com/l0o0/translators_CN/pull/214)），你试试看好用不？只是数据库里面没给出版社地址的信息，暂时没办法填充这个字段。
