### ISSUE TITLE
知网无法批量抓取pdf，只能抓取caj

### ISSUE THREAD

**Issue by Invincible-Dhh** [l0o0/translators_CN#182]
进入单个论文页面后可以抓取pdf，搜索界面只能批量抓取caj格式，已更新translators

**Comment by l0o0** [comment]
目前知网没有在搜索页面提供PDF，用其他方法去获取PDF非常不稳定，而且在translator中不好处理。所有还没有办法

**Comment by jiaojiaodubai** [comment]
@Invincible-Dhh  已经在 6471e94727e56744ac06fa266437d3e25cf189db 修复。
