### ISSUE TITLE
建议添加面向预发布平台Chinaxiv的解析器

### ISSUE THREAD

**Issue by thetaaaaa** [l0o0/translators_CN#184]
建议添加面向中国科学院科技论文预发布平台的解析器。中国科学院科技论文预发布平台旨在打造中文版的预印本平台，它的网址是：http://www.chinaxiv.org/home.htm

![image](https://user-images.githubusercontent.com/66288540/232230079-0f5cf898-5081-4b79-9788-b48aa1a60b34.png)

**Comment by jiaojiaodubai** [comment]
尝试弄了一下，发现期刊信息不全，缺页码

**Comment by jiaojiaodubai** [comment]
中国科学院科技论文预发布平台的翻译器`(ChinaXiv.js)` 已经合并到主线，支持茉莉花更新。@thetaaaaa
