### ISSUE TITLE
6.0.24版本新增了dataset和standard条目类型

### ISSUE THREAD

**Issue by wohenbushuang** [l0o0/translators_CN#185]
[6.0.24 Changelog](https://www.zotero.org/support/changelog#changes_in_6024_april_19_2023)

原先在`extra`字段标记了`Type: standard`的条目在升级6.0.24版本后会自动转换为standard类型（但是原先在`extra`字段中记录的其他信息不变，不会自动填充到新字段）
https://github.com/l0o0/translators_CN/blob/d9de87dbb344efed6ef1881c2ee6ca09c047df52/translators/Wanfang%20Data.js#L289-L291

Now I start to work on it.

**Comment by zepinglee** [comment]
支持，好像 std.samr.gov.cn 的 translator 也需要改一下。

**Comment by wohenbushuang** [comment]
@zepinglee 已更新
@l0o0 请求审核批准PR #186

**Comment by zepinglee** [comment]
感谢帮我解决了 samr.gov.cn。
