### ISSUE TITLE
更新到最新版本后出现翻译器界面空空如也，更新翻译器信息出现延时错误

### ISSUE THREAD

**Issue by liyunxiao2020** [l0o0/translators_CN#187]
![茉莉花更新翻译器](https://user-images.githubusercontent.com/112650414/233553953-040192f5-a24b-4691-96bb-1c319f68e43a.png)
![茉莉花更新翻译器1](https://user-images.githubusercontent.com/112650414/233553976-f0a20f38-38ac-4a04-a3c7-b3b6310b21f1.png)

**Comment by yfdyh000** [comment]
https://github.com/l0o0/jasminum/issues/166

**Comment by l0o0** [comment]
已切换下载源
