### ISSUE TITLE
学校更换webvpn，无法全局代理，茉莉花插件无法获取知网权限，请问有什么解决方法吗？

### ISSUE THREAD

**Issue by 2020jia** [l0o0/translators_CN#189]
如题，谢谢。

**Comment by l0o0** [comment]
是zotero connector无法抓取么？元数据支持抓取么

无名小辈 ***@***.***> 于 2023年5月2日周二 下午8:29写道：

**Comment by l0o0** [comment]
知网助手里的，对vpn不支持，等后面更新

无名小辈 ***@***.***> 于 2023年5月2日周二 下午11:48写道：

**Comment by l0o0** [comment]
已更新转换器，请及时更新测试并反馈 https://github.com/l0o0/translators_CN/commit/4d75425e3a75650cdefb755a5fb10b52a876bd73
