### ISSUE TITLE
CNKI翻译器失效

### ISSUE THREAD

**Issue by moonwatcher373** [l0o0/translators_CN#190]
使用平台: MacOS 12.5, intel

问题：在Safari, Chrome, Edge上通过校外访问查询知网上文献时，无法通过zotero connector保存文献元数据。分别尝试通过茉莉花插件更新翻译器和手动下载并替换翻译器，并在Chrome和Edge上的Zotero Connector设置中update translator后依然报错。

**Comment by l0o0** [comment]
这个问题存在多久了，一般过几天再试试，应该就好了😄

moonwatcher373 ***@***.***> 于 2023年5月5日周五 上午11:36写道：

**Comment by ZHULOO** [comment]
<img width="1898" alt="image" src="https://github.com/l0o0/translators_CN/assets/43084101/db2b0b6e-27c4-434d-bf1a-dd638ef1c720">
同样的问题，校园网环境内，一直正常使用下载pdf文献的，突然保存不了了，试了各种方法，重装软件和更新translator还是不行。

**Comment by ZHULOO** [comment]
<img width="1889" alt="image" src="https://github.com/l0o0/translators_CN/assets/43084101/6d1c84b1-0424-4736-9db7-27357aa04500">
report errors中的提示

**Comment by gtdg0317** [comment]
我也突然这样了，有什么解决方法吗请问
