### ISSUE TITLE
希望添加知网海外版的翻译器

### ISSUE THREAD

**Issue by OrlandoZh** [l0o0/translators_CN#191]
目前发现知网会锁ip，ip国内打开是国内知网，ip国外会打开海外知网，现在的翻译器海外知网尝试不能使用（ps，一开始我也以为知网是合并成一个，后来才发现这个）

**Comment by l0o0** [comment]
确实知网会根据IP自动切换国内或海外版。我估计海外版限制少，国内版限制多。

**Comment by jiaojiaodubai** [comment]
@OrlandoZh 已经在 6471e94727e56744ac06fa266437d3e25cf189db 完成。
