### ISSUE TITLE
建议增加裁判文书网的翻译器~

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#193]
https://wenshu.court.gov.cn

**Comment by zepinglee** [comment]
我不太了解你们法律界的情况，这里提到“裁判文书网不太好用，搜索案例一般用北大法宝”。

https://github.com/l0o0/translators_CN/issues/129#issuecomment-1274668333

**Comment by zepinglee** [comment]
我来尝试写这个吧，顺便把咕了好久的 @129 处理掉。

不过可能需要你们熟悉法律的帮忙校对一些字段的信息。

**Comment by yzy1228682367** [comment]
太感谢了！我可以帮忙校对~

**Comment by yzy1228682367** [comment]
我个人感觉北大法宝和裁判文书网都可以的~ 裁判文书网更加权威，北大法宝更加好用。

**Comment by zepinglee** [comment]
上周末在忙优先级更高的，这周末抽时间看一下。

**Comment by yzy1228682367** [comment]
好嘞 感谢~

**Comment by yzy1228682367** [comment]
这样子也没有问题呀，案由是“其他”。它说“根据上下文或者当事人信息可以推知案由的，案由可以省略。”也并非一定要省略。

**Comment by yzy1228682367** [comment]
![CleanShot 2023-06-22 at 00 36 25@2x](https://github.com/l0o0/translators_CN/assets/50101175/1b2d71a9-cb29-41a3-934a-d6e230dad156)
![CleanShot 2023-06-22 at 00 38 11@2x](https://github.com/l0o0/translators_CN/assets/50101175/e5999f19-6370-4df5-a510-d9d1b8f2bb50)
请问有没有可能用北大法宝来生成类似格式呢？先用“案由”判断属于“民事”“行政”还是“刑事”案件，然后从“当事人”中抽取“原告”以及“被告”。
https://www.pkulaw.com/pfnl/a25051f3312b07f31283da7ab5ad76fdbd34f054c6e07219bdfb.html?keyword=%E6%B5%B7%E8%A1%8C%E5%88%9D%E5%AD%97%E7%AC%AC142%E5%8F%B7%20&way=listView

**Comment by yzy1228682367** [comment]
![CleanShot 2023-06-22 at 00 40 44@2x](https://github.com/l0o0/translators_CN/assets/50101175/c32cabc6-d5a4-4de5-9b47-61ba706de3c3)
哦，裁判文书网点击“概要”可以产生如下信息，您看可否满足要求呢？

**Comment by yzy1228682367** [comment]
![CleanShot 2023-06-22 at 00 42 09@2x](https://github.com/l0o0/translators_CN/assets/50101175/5f6c6908-fe35-4798-9aeb-2b43037b37f6)
“概要”在最左侧。
