### ISSUE TITLE
请求抓取“全国标准信息公共服务平台”（https://std.samr.gov.cn/）时，能够抓取标准号。

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#198]
因为有的引注格式，例如法学引注手册，要求具有标准号。
![CleanShot 2023-07-07 at 20 54 13@2x](https://github.com/l0o0/translators_CN/assets/50101175/83be0e89-cf34-4473-925a-4c3657586801)

**Comment by wohenbushuang** [comment]
原本就可以的吧

https://github.com/l0o0/translators_CN/blob/da49dd996d175feb73068c575fa6f832e893af22/translators/National%20Public%20Service%20Platform%20for%20Standards%20Information%20-%20China.js#L76-L83

对于Zotero新类型`standard`的修改在#185

**Comment by yzy1228682367** [comment]
哦哦哦 在其他，看到啦，抱歉。
