### ISSUE TITLE
知网抓取文献的作者姓和名是分开的，如何让姓和名合在一起？

### ISSUE THREAD

**Issue by iseex** [l0o0/translators_CN#2]
你好作者，现在不论是您提供的CNKI.js还是Zotero默认的CNKI.js，在抓取知网文献后，author一栏中姓和名是分开的，比如，“张，三丰”。这会导致用Zotfile的PDF无法包含完整的姓名（目前Zotfile还不支持完成姓名的通配符），所以我想在抓取文献的源头解决这个问题。经过测试，在谷歌学术抓取知网文献，姓和名是连续的，就很完美。所以希望作者能答复下如何让知网文献抓取到的作者是连续的。十分感谢！

**Comment by l0o0** [comment]
同学可以参考[Zotfile 官网](http://zotfile.com/index.html#renaming-rules)上 4.2的更新说明，可以使用`%g_`来显示作者全名(感谢[QingQYang](https://github.com/QingQYang)的修复)  
@iseex

**Comment by l0o0** [comment]
@iseex 我最近写了一个插件，用于合并和拆分中文姓名，你也可以试试https://github.com/l0o0/jasminum

**Comment by iseex** [comment]
好的，我在你们的qq群，看到了。谢谢！作品很棒！

发自我的iPhone
