### ISSUE TITLE
建议翻译器可以做一个类似于OneNote那样的网页剪辑

### ISSUE THREAD

**Issue by pengxy0** [l0o0/translators_CN#201]
翻译器的确很实用，但也有很多网页内容不能剪辑，目前试了微信公众号的推文和知乎问答，都可以剪辑成zotero的笔记，也有很多网页是以快照形式体现的。
![image](https://github.com/l0o0/translators_CN/assets/130196652/f702f6e4-43c8-4644-9263-f7f749caa19d)

**Comment by pengxy0** [comment]
或者各位大佬已经有什么剪藏插件，可以推荐下我，小弟在此感谢！

**Comment by l0o0** [comment]
自带的snapshot 可以么，现在zotero 7已经支持阅读网页，还可以添加注释

**Comment by pengxy0** [comment]
可以的了，也是刚才知道zotero7有这个阅读网页的功能了。谢谢大佬。不过这个阅读功能貌似不能放大缩小页面，希望后期zotero可以优化一下，就更完美了。
