### ISSUE TITLE
翻译器全部失效，更新后再次打开仍然失效，没有本地时间

### ISSUE THREAD

**Issue by zhuwoshi** [l0o0/translators_CN#204]
![image](https://github.com/l0o0/translators_CN/assets/136768349/2846859d-4482-4e58-b969-7093299ae303)

**Comment by yfdyh000** [comment]
更新 https://github.com/l0o0/jasminum 版本，作者换了路径。

**Comment by zhuwoshi** [comment]
> 更新 https://github.com/l0o0/jasminum 版本，作者换了路径。

非常感谢！
