### ISSUE TITLE
建议标准号填入到“号码”一栏

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#206]
![CleanShot 2023-08-26 at 23 49 59@2x](https://github.com/l0o0/translators_CN/assets/50101175/f503338a-7f80-438f-8978-2423192db626)
因为CSL识别的是号码一栏，填入号码一栏比较方便引用。https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl

**Comment by zepinglee** [comment]
这是旧版保存为 `report` 类型，又自动转为 `standard` 类型导致的。建议更新 `National Public Service Platform for Standards Information` 的 translator 至 2023-06-27 17:37:20。

**Comment by yzy1228682367** [comment]
> 这是旧版保存为 `report` 类型，又自动转为 `standard` 类型导致的。建议更新 `National Public Service Platform for Standards Information` 的 translator 至 2023-06-27 17:37:20。

哦吼 好滴 谢谢

**Comment by zepinglee** [comment]
> 另外请问对于已经保存到文库里面的条目，有办法按照翻译器批量更新它的元数据吗？

据我了解只能自己写 JavaScript 代码，参考 <https://www.zotero.org/support/dev/client_coding/javascript_api>。

你的这类文献有多少？

**Comment by yzy1228682367** [comment]
不是很多，谢啦。
