### ISSUE TITLE
万方翻译器在某些页面无法使用

### ISSUE THREAD

**Issue by ilcpm** [l0o0/translators_CN#207]
在下面的页面中，茉莉花中的第三方万方翻译器失效

公共服务机器人的电磁兼容安全风险监测研究
https://d.wanfangdata.com.cn/periodical/ChhQZXJpb2RpY2FsQ0hJTmV3MjAyMzA4MDYSEXpsanNqZHlqMjAyMzAxMDEzGgg0a3o0cGg4Nw%3D%3D

但是在另一个万方的页面中又可以生效

基于 DWT-DCT-SVD的彩色图像零水印算法
https://d.wanfangdata.com.cn/periodical/wdzxyjsj201608023

看上去似乎只是网址后面的内容长一些

---

下面是一些相关环境
报错情况：
这里前面的wanfang data是插件茉莉花提供的第三方翻译器，无法识别之后后面的doi是zotero自己的翻译器
![C0CHN90GLWJ0K$1W M$SQF](https://github.com/l0o0/translators_CN/assets/36830343/ed1afa75-c10a-421f-b1b3-35cdedfb5716)

翻译器：
![image](https://github.com/l0o0/translators_CN/assets/36830343/b388a10c-d02f-4f07-a55e-bfe77712b9aa)

**Comment by liuxsdev** [comment]
跟url长度没关系
万方的一些文章没有卷信息，比如你失败的这篇
![image](https://github.com/l0o0/translators_CN/assets/11004456/9e015d15-8f6b-46b4-bf21-897c922351e1)
正常的卷 和期 都有的
![image](https://github.com/l0o0/translators_CN/assets/11004456/e896c3d5-34d5-4d77-b6e1-572f3dd90322)

没有卷的时候，由于少一个值，卷、期就对应不上了，期的值为 undefined
![image](https://github.com/l0o0/translators_CN/assets/11004456/7395934f-551e-4a44-8f99-52fcf1aa9855)
