### ISSUE TITLE
中国知网抓取页面提示错误

### ISSUE THREAD

**Issue by MartinYuan1995** [l0o0/translators_CN#21]
![Xnip2020-11-22_15-45-02](https://user-images.githubusercontent.com/47047658/99898083-c3d56680-2cd9-11eb-8031-6c736aa1c2b9.jpg)
![Xnip2020-11-22_15-46-50](https://user-images.githubusercontent.com/47047658/99898098-f41d0500-2cd9-11eb-81b5-54301fd1a434.jpg)
![Xnip2020-11-22_15-45-13](https://user-images.githubusercontent.com/47047658/99898086-c8018400-2cd9-11eb-99d9-a5fbc0c02b39.jpg)
使用中国知网搜索完之后，浏览器插件变成文件夹图标，点击之后报错，无法出现搜索页面的文献列表

**Comment by l0o0** [comment]
同学，这边建议你多尝试几次更新translator的操作
