### ISSUE TITLE
求增加国际标准ISO的抓取器~

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#212]
https://www.iso.org/standard/63598.html

**Comment by yzy1228682367** [comment]
发现可以从国标抓~感谢

**Comment by zepinglee** [comment]
ISO 这种国际的标准更适合向官方的 translator 仓库request。发自我的 iPhone在 2023年9月18日，09:37，yzy ***@***.***> 写道：﻿
发现可以从国标抓~感谢

**Comment by yzy1228682367** [comment]
好哩 谢谢！
