### ISSUE TITLE
怎样可以不保存微信公众号或者知网等网站的文档格式，求怎么设置？

### ISSUE THREAD

**Issue by pengxy0** [l0o0/translators_CN#213]
如题，怎样可以不保存微信公众号或者知网等网站的文档格式，求怎么设置？如下图：
![6C@ N_YKA(XB4G0X$%4M10T](https://github.com/l0o0/translators_CN/assets/130196652/30344707-5c3e-4632-9561-452aa9ebf282)

**Comment by l0o0** [comment]
我发现最近 Zotero 已经支持网页格式的阅读，这个note我觉得可以去掉。等后面更新，我会去掉自动生成的笔记

**Comment by dengyuyueyuyue** [comment]
> 我发现最近 Zotero 已经支持网页格式的阅读，这个note我觉得可以去掉。等后面更新，我会去掉自动生成的笔记

作者大大能否保留此操作？或者维护时保存一份可以抓取文档的js, 我以及周围的朋友非常依赖将网站文章抓取为文档这一操作，因为我们可以基于此对文档进行文本进一步修改，进行信息整合，感谢！！

**Comment by dengyuyueyuyue** [comment]
> 我发现最近 Zotero 已经支持网页格式的阅读，这个note我觉得可以去掉。等后面更新，我会去掉自动生成的笔记

作者大大能否保留此操作？或者可以额外提供一份可以抓取文档的js文件, 我以及周围的朋友非常依赖将网站文章抓取为文档这一操作，因为我们可以基于此对文档进行文本进一步修改，进行信息整合，感谢！！
