### ISSUE TITLE
请求保留保存微信公众号的文档功能

### ISSUE THREAD

**Issue by dengyuyueyuyue** [l0o0/translators_CN#216]
![1696232587254](https://github.com/l0o0/translators_CN/assets/85548361/c8db21f4-1ca6-4d3a-bbcc-1a54628cc92e)

作者大大能否保留此操作？或者可以额外提供一份可以抓取文档的js文件, 我以及周围的朋友非常依赖将网站文章抓取为文档这一操作，因为我们可以基于此对文档进行文本进一步修改，进行信息整合，感谢！！

**Comment by jiaojiaodubai** [comment]
其实你把这里注释掉的代码取消注释就好了 @dengyuyueyuyue 
![image](https://github.com/l0o0/translators_CN/assets/63148861/79fbda13-833d-453c-82e7-205911181d5a)
