### ISSUE TITLE
百度学术和全国图书馆联盟不能抓取参考文献信息

### ISSUE THREAD

**Issue by eastnoob** [l0o0/translators_CN#22]
在**百度学术**和**全国图书馆联盟**中抓取信息的时候，虽然connector可以准确识别网站类型，但是保存的时候会无法抓取信息，且不保存任何内容（如图）。translator和浏览器插件端均已更新，浏览器为edge稳定版，不清楚是我的配置有问题或者其他原因，请大大解答。
问题网站如图：
![image](https://user-images.githubusercontent.com/61303573/100958576-94372180-3557-11eb-9512-a8949a8337bf.png)
其它网站正常情况如图：
![image](https://user-images.githubusercontent.com/61303573/100958483-618d2900-3557-11eb-9f28-3e2f66b0ff64.png)

**Comment by l0o0** [comment]
百度API发生变化了，暂还没想到如何解决。全国图书馆联盟已经处理好了，可以更新下

**Comment by eastnoob** [comment]
谢谢，大大辛苦啦😄
