### ISSUE TITLE
为何我这里豆瓣找不到评分的信息？

### ISSUE THREAD

**Issue by hxsnow10** [l0o0/translators_CN#220]
看起来是生效了更之前提取的不一样，但是找不到评分。

比如这个 https://book.douban.com/subject/25883305/
我的是
![image](https://github.com/l0o0/translators_CN/assets/5416620/cdfd504b-9daf-4d79-ba84-b37b94271797)

**Comment by hxsnow10** [comment]
而且提取特别特别慢，大概要接近1分钟，之前只要几秒..

**Comment by zepinglee** [comment]
Zotero 或 CSL 没有与评分相关的字段，所以没有录入该信息。

可以考虑在 `extra` 中填写 `Rating: 9.0`。

**Comment by hxsnow10** [comment]
"保留豆瓣评价人数+豆瓣评分+原作名+定价". 
主要我在README里看到对豆瓣translator的描述，我以为它支持评分的提取呢？

**Comment by zepinglee** [comment]
> "保留豆瓣评价人数+豆瓣评分+原作名+定价". 主要我在README里看到对豆瓣translator的描述，我以为它支持评分的提取呢？

我在 https://github.com/l0o0/translators_CN/pull/144 中忘记修改描述信息了。

你需要评分、评价人数这些信息吗？添加这些支持也不难。

**Comment by hxsnow10** [comment]
是的，如果不麻烦的话有空可以帮加下，谢谢了

Zeping Lee ***@***.***> 于2023年10月14日周六 12:45写道：

**Comment by jiaojiaodubai** [comment]
已在 #264 完成@hxsnow10
