### ISSUE TITLE
似乎知乎和微信文章不起作用

### ISSUE THREAD

**Issue by anyiweb** [l0o0/translators_CN#226]
如图，抓取了几次都只有在线网页链接，快照已关闭，翻译器已经更新，但是只能抓取到链接。请问这大概是什么问题呢

![image](https://github.com/l0o0/translators_CN/assets/60560420/884dcbe7-7259-470d-9532-a6677285daba)
![image](https://github.com/l0o0/translators_CN/assets/60560420/d997cce2-27a1-4eae-809f-0434caf035a4)
![image](https://github.com/l0o0/translators_CN/assets/60560420/d786e2e2-c6d3-4170-a834-01b8533de6a6)
![image](https://github.com/l0o0/translators_CN/assets/60560420/292678fe-dcea-4774-b86c-bee511aec0ae)

**Comment by jiaojiaodubai** [comment]
你说的是 (#213 ) 吗？

**Comment by anyiweb** [comment]
> 你说的是 (#213 ) 吗？
是的

**Comment by anyiweb** [comment]
> 你说的是 (#213 ) 吗？

是的，请问‘’网页格式的阅读‘’这个在zotero中怎么显示呢，我好像抓取之后只有一个链接

**Comment by jiaojiaodubai** [comment]
> > 你说的是 (#213 ) 吗？
> 
> 是的，请问‘’网页格式的阅读‘’这个在zotero中怎么显示呢，我好像抓取之后只有一个链接

指的应该是这里 _[Available for beta testing: Updated reader with EPUB/snapshot support and new annotation types](https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types)_ 
@l0o0 我感觉，“添加note”应该作为Connector的Preference项予以保留。

**Comment by anyiweb** [comment]
> > > 你说的是 (#213 ) 吗？
> > 
> > 
> > 是的，请问‘’网页格式的阅读‘’这个在zotero中怎么显示呢，我好像抓取之后只有一个链接
> 
> 指的应该是这里 _[Available for beta testing: Updated reader with EPUB/snapshot support and new annotation types](https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types)_ @l0o0 我感觉，“添加note”应该作为Connector的Preference项予以保留。

>>明白了，谢谢！
