### ISSUE TITLE
能否新增对PubScholar的支持

### ISSUE THREAD

**Issue by Riceneeder** [l0o0/translators_CN#228]
> PubScholar公益学术平台在尊重知识产权和国际通行规范的前提下，发挥中国科学院自身拥有丰富且高质量学术资源的优势，带动国内外的学术资源机构积极合作，最大限度地开放优质学术资源。
> 平台资源每日持续更新。目前平台可检索的元数据资源量约1.7亿条，包括科技论文元数据约9,548万条，科技专利元数据约8,013万条，科学数据元数据约48万条。
> 可免费获取的全文资源量约8,000万篇，包括科技论文全文数据约2,122万篇，专利全文数据约5,878万篇。

能否增加对PubScholar公益学术平台的支持

**Comment by PlanetesDDH** [comment]
dd (๑•̀ㅂ•́)و✧

**Comment by l0o0** [comment]
这么好的网站，怎么会不支持，等他们网站扩容稳定后，会跟进
