### ISSUE TITLE
万方数据的链接似乎有变，无法抓取数据

### ISSUE THREAD

**Issue by bennylii** [l0o0/translators_CN#23]
似乎之前的链接为http://d.wanfangdata.com.cn/Periodical_xdqb200902027.aspx
但是现在的链接为http://d.wanfangdata.com.cn/periodical/xdqb200902027

导致js内表达式失效，但是我不会js，请求dalao测试。

**Comment by l0o0** [comment]
同学你好，我测试了下是没有问题。万方这个最近有过更新，不知道你有没有用[最新](https://github.com/l0o0/translators_CN/blob/master/translators/Wanfang%20Data.js)的试试

**Comment by bennylii** [comment]
果然是我没更新テ_デ
(* /ω＼*)
