### ISSUE TITLE
Saving with CNKI doesn't work

### ISSUE THREAD

**Issue by Qnurye** [l0o0/translators_CN#231]
- OS: Arch Linux
- Browser: Firefox Developer Edition 120.0b9 (64-bit)
- Zotero Standalone: 6.0.30-1
- Zotero Connector: 5.0.114
- CNKI.js: [9c4cfb0](https://github.com/l0o0/translators_CN/commit/9c4cfb0264d415f96901d60dda25943ce0e4f9d6)
- Network Env: Both Proxy and Direct

# How did I produce

After correctly configured according to [README.md](https://github.com/l0o0/translators_CN/README.md), I tried to save a journal on cnki.net using Zotero Connector. Then I get a message saying "An error occurred saving with CNKI. Attempting to save using Save as Webpage instead". Meanwhile, an error log produced:

```
[JavaScript Error: "HTTP request to https://kns.cnki.net/KNS8/manage/ShowExport?filename=DNDX202301015&displaymode=Refworks&orderparam=0&ordertype=desc&selectfield=&dbname=CJFDLAST2023&random=0.2111567532240084 rejected with status 0"]
```

![screen](https://github.com/l0o0/translators_CN/assets/50016379/5d485de0-8d09-40bb-aa4f-34b142b96be6)
![screen](https://github.com/l0o0/translators_CN/assets/50016379/6f679ee7-ffa1-4209-b3a9-4634299f112c)

**Comment by Lenthking** [comment]
me too

**Comment by icodexin** [comment]
me too +1

**Comment by pooneyy** [comment]
正在写开题报告啊……今晚上七八点还可以正常抓取题录，大约九点突然就抓不了知网题录了。试了B站和知乎的教程，全部都没用。看时间正好是这条ISSUE提出来前后。看来遇到这个问题不止我一个人

**Comment by BlueBubble23** [comment]
一样的问题

**Comment by whisper1001** [comment]
+1还没好

**Comment by pooneyy** [comment]
分享一个临时的解决方案
文献页面点击“引用”
![image](https://github.com/l0o0/translators_CN/assets/85266337/52bc34ee-84d2-480b-b1a3-4388b2effb16)
然后点“更多引用格式”
![image](https://github.com/l0o0/translators_CN/assets/85266337/eab1560d-65e9-42a3-9efb-479ce2bc8df3)
选择EndNote，导出为文件
![image](https://github.com/l0o0/translators_CN/assets/85266337/b672bf62-f382-4ab2-a840-738f334e8a2e)
Zotero左上角“文件”->“导入”->“从文件导入”

**Comment by cardinalsystem256** [comment]
+1

**Comment by LaoshuBaby** [comment]
> 选择EndNote，导出为文件
> ![image](https://user-images.githubusercontent.com/85266337/284034727-b672bf62-f382-4ab2-a840-738f334e8a2e.png)
> Zotero左上角“文件”->“导入”->“从文件导入”

其实可以选bibtex的，Zotero可以直接从剪贴板导入bibtex或其他主流格式（但感觉bibtex最稳妥）
![图片](https://github.com/l0o0/translators_CN/assets/42690037/cc49302a-cea3-4bdf-936d-17e371adc4f4)

**Comment by pooneyy** [comment]
> > 选择EndNote，导出为文件
> > ![image](https://user-images.githubusercontent.com/85266337/284034727-b672bf62-f382-4ab2-a840-738f334e8a2e.png)
> > Zotero左上角“文件”->“导入”->“从文件导入”
> 
> 其实可以选bibtex的，Zotero可以直接从剪贴板导入bibtex或其他主流格式（但感觉bibtex最稳妥） ![图片](https://user-images.githubusercontent.com/42690037/284037366-cc49302a-cea3-4bdf-936d-17e371adc4f4.png)

我试了，但是不知道什么原因，导入进去后只是一条空白的题录，不管是通过剪切板还是通过文件导入，我的版本是6.0.30。而且BibTex携带的信息太少了，也没有摘要

**Comment by Hercule777** [comment]
> > > 选择EndNote，导出为文件
> > > ![image](https://user-images.githubusercontent.com/85266337/284034727-b672bf62-f382-4ab2-a840-738f334e8a2e.png)
> > > Zotero左上角“文件”->“导入”->“从文件导入”
> > 
> > 
> > 其实可以选bibtex的，Zotero可以直接从剪贴板导入bibtex或其他主流格式（但感觉bibtex最稳妥） ![图片](https://user-images.githubusercontent.com/42690037/284037366-cc49302a-cea3-4bdf-936d-17e371adc4f4.png)
> 
> 我试了，但是不知道什么原因，导入进去后只是一条空白的题录，不管是通过剪切板还是通过文件导入，我的版本是6.0.30。而且BibTex携带的信息太少了，也没有摘要

这位老哥前面说的endnotes有效，复制，从剪贴板导入即可
![image](https://github.com/l0o0/translators_CN/assets/91647504/0c2b27ac-673b-413d-bc74-4394f778a0b8)
![image](https://github.com/l0o0/translators_CN/assets/91647504/f2c9ee69-77e4-40e3-9ccd-2a8292574e78)

**Comment by cyq51bbd** [comment]
看来是同样的问题

**Comment by Sunshineyyq** [comment]
是的我也是这样，大概什么时候能恢复啊

**Comment by yzy1228682367** [comment]
> When I use the new "[translators_CN](https://github.com/l0o0/translators_CN/blob/master/CNKI.js)", the "Zotero Connector" still doesn't work. It is stuck in the save procedure. ![image](https://user-images.githubusercontent.com/49866394/284109138-fbf5f1d9-a58d-462b-8745-c588f7cb2b7b.png) ![image](https://user-images.githubusercontent.com/49866394/284109203-7c5b3d87-04b4-4aeb-acc4-c88503a287fc.png)

我也是，好像新版仍然没有解决。

**Comment by Cooooz** [comment]
同样的问题，希望大佬能修复一下

**Comment by Lyndonxie** [comment]
> > > 选择EndNote，导出为文件
> > > ![image](https://user-images.githubusercontent.com/85266337/284034727-b672bf62-f382-4ab2-a840-738f334e8a2e.png)
> > > Zotero左上角“文件”->“导入”->“从文件导入”
> > 
> > 
> > 其实可以选bibtex的，Zotero可以直接从剪贴板导入bibtex或其他主流格式（但感觉bibtex最稳妥） ![图片](https://user-images.githubusercontent.com/42690037/284037366-cc49302a-cea3-4bdf-936d-17e371adc4f4.png)
> 
> 我试了，但是不知道什么原因，导入进去后只是一条空白的题录，不管是通过剪切板还是通过文件导入，我的版本是6.0.30。而且BibTex携带的信息太少了，也没有摘要

我用的剪切板导入，是可以的，版本是6.0.30

**Comment by yun-xx** [comment]
#

> When I use the new "[translators_CN](https://github.com/l0o0/translators_CN/blob/master/CNKI.js)", the "Zotero Connector" still doesn't work. It is stuck in the save procedure.当我使用新的“translators_CN”时，“Zotero Connector”仍然不起作用。它卡在保存过程中。 ![image](https://user-images.githubusercontent.com/49866394/284109138-fbf5f1d9-a58d-462b-8745-c588f7cb2b7b.png) ![image](https://user-images.githubusercontent.com/49866394/284109203-7c5b3d87-04b4-4aeb-acc4-c88503a287fc.png)

+1

**Comment by PaulWang7777** [comment]
> 最新版已经成功解决。 ![图像](https://user-images.githubusercontent.com/49866394/284255592-d2fb9283-b413-4838-892e-354617f4134a.png)

是要更新翻译器吗，请问下

**Comment by yun-xx** [comment]
> > 最新版已经成功解决。 <img alt="图像" width="764" height="32.4375" src="https://user-images.githubusercontent.com/49866394/284255592-d2fb9283-b413-4838-892e-354617f4134a.png">
> 
> 是要更新翻译器吗，请问下

刚试了，好了耶，更新最新的CKNI.js就可以，多谢  @2021521

**Comment by yun-xx** [comment]
是CNKI

**Comment by yun-xx** [comment]
我是找到最新的CNKI.js，然后进zetero 翻译器文件夹替换掉这一个就可以了

**Comment by PaulWang7777** [comment]
> 我是找到最新的CNKI.js，然后进zetero 翻译器文件夹替换掉这一个就可以了
请问下是在哪里找到的呢，方便发一个链接吗，万分感谢

**Comment by yun-xx** [comment]
https://github.com/l0o0/translators_CN/blob/master/CNKI.js

**Comment by yun-xx** [comment]
https://github.com/l0o0/translators_CN/blob/master/CNKI.js

**Comment by yun-xx** [comment]
都重启试试？

**Comment by normanfoster** [comment]
Still does‘t work after updating the CNKI.js

`[JavaScript Error: "HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code undefined" {file: "chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/zotero.js" line: 306}]`

**Comment by normanfoster** [comment]
<img width="1296" alt="image" src="https://github.com/l0o0/translators_CN/assets/54034933/2e5c363d-e5db-4909-8cf1-8689cbeaf10b">

**Comment by PaulWang7777** [comment]
> 都重启试试？
都试过了，电脑都重启试过了，真是奇怪

**Comment by WayneMooooo** [comment]
换了最新的translator同样不行，在能下载PDF的网络环境下在知网上什么也抓取不下来，反而不能下的时候能抓取其它信息除了PDF

**Comment by L-0901** [comment]
> https://github.com/l0o0/translators_CN/blob/master/CNKI.js

请问怎么下载呢？找了好半天不知道点击哪个下载

**Comment by yun-xx** [comment]
![image](https://github.com/l0o0/translators_CN/assets/151519929/d7514780-fcad-4c5c-a32a-2b28158427e8)
下载替换原来的文件

**Comment by yun-xx** [comment]
下载替换原来的文件
![image](https://github.com/l0o0/translators_CN/assets/151519929/0ecd7b01-9edf-4125-b707-012deef93dd9)

**Comment by yun-xx** [comment]
![image](https://github.com/l0o0/translators_CN/assets/151519929/3dd4f7c3-22af-4523-a35f-071b3febd0c1)
那个向下的箭头就是下载文件

**Comment by L-0901** [comment]
> ![image](https://user-images.githubusercontent.com/151519929/284434167-3dd4f7c3-22af-4523-a35f-071b3febd0c1.png)那个向下的箭头就是下载文件

我点了没有反应呢

**Comment by yun-xx** [comment]
稍等一会就会弹出来了

**Comment by L-0901** [comment]
> 稍等一会就会弹出来了

谢谢回复啊，能给我看一下弹出来是什么样吗？我感觉我等了好久页面也没有变化

**Comment by yun-xx** [comment]
[CNKI.zip](https://github.com/l0o0/translators_CN/files/13420882/CNKI.zip)

**Comment by L-0901** [comment]
> [CNKI.zip](https://github.com/l0o0/translators_CN/files/13420885/CNKI.zip)

感谢呀，太谢谢你了❥(^_-)

**Comment by yun-xx** [comment]
没事，你先试试看有没有效果吧

**Comment by PaulWang7777** [comment]
我的还是没效果，连茉莉花插件都重新装了



发自我的iPhone


------------------ Original ------------------
From: yun-xx ***@***.***&gt;
Date: Tue,Nov 21,2023 9:46 AM
To: l0o0/translators_CN ***@***.***&gt;
Cc: PaulWang7777 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [l0o0/translators_CN] Saving with CNKI doesn't work (Issue #231)





 
没事，你先试试看有没有效果吧

**Comment by yun-xx** [comment]
[translators.zip](https://github.com/l0o0/translators_CN/files/13420974/translators.zip)
要不试试全换成我的translator，我的没问题，不行的话就试试反馈错误请大佬帮忙了

**Comment by Qnurye** [comment]
The problem has been fixed since commit [46c59d9](https://github.com/l0o0/translators_CN/commit/46c59d98541295e9de1111fe666479d4c9bc69f8)  :smile: .Many thanks and :heart: to the contributors

**Comment by PaulWang7777** [comment]
为什么我更新了最新的翻译器还是不行哈哈，edge浏览器




校信&nbsp;&nbsp;、
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l0o0/translators_CN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月21日(星期二) 晚上11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l0o0/translators_CN] Saving with CNKI doesn't work (Issue #231)





 
The problem has been fixed since commit 46c59d9  😄 .Many thanks and ❤️ to the contributors

**Comment by Qnurye** [comment]
> 为什么我更新了最新的翻译器还是不行哈哈，edge浏览器 校信&nbsp;&nbsp;、 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "l0o0/translators_CN" ***@***.***&gt;; 发送时间:&nbsp;2023年11月21日(星期二) 晚上11:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [l0o0/translators_CN] Saving with CNKI doesn't work (Issue #231) The problem has been fixed since commit [46c59d9](https://github.com/l0o0/translators_CN/commit/46c59d98541295e9de1111fe666479d4c9bc69f8) 😄 .Many thanks and ❤️ to the contributors — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请尝试一下以下步骤：
1. 删除 `...\Zotero\translators\CNKI.js` (Linux/MacOS: `rm ~/Zotero/translators/CNKI.js`)
2. 下载最新版本的 [CNKI.js](https://raw.githubusercontent.com/l0o0/translators_CN/46c59d98541295e9de1111fe666479d4c9bc69f8/CNKI.js)，并替换刚刚删除的版本
3. 完全重启 Zotero Standalone 应用程序
4. 完全重启浏览器
5. 如图，在“高级”配置中多点几次更新 Translator
![图](https://camo.githubusercontent.com/de068cf74137bd1106db988529277f107cd4fc6ebea4b89d7e2bf8cb0387c584/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f31392f646c51674b532e676966)

如果没能解决你的问题，欢迎补充一下 Zotero Connector 的报错信息或日志信息

**Comment by l0o0** [comment]
还有一个点，我特意在代码里添加了日志，如果更新后，点击抓取后，浏览器的日志里会出现
![图片](https://github.com/l0o0/translators_CN/assets/2743744/fd1e3f5d-94b0-44c3-9ac6-c8a8a918b47b)

**Comment by weigeqq4** [comment]
![1700635912143](https://github.com/l0o0/translators_CN/assets/135113875/cc62aff9-e761-4ea0-988e-bdca5d3be180)

![1700635929179](https://github.com/l0o0/translators_CN/assets/135113875/93145960-e783-4821-8674-cafe4c93947c)
大佬，今天更新了最新翻译器并按照您说的步骤试了，依然无法保存PDF

**Comment by weigeqq4** [comment]
> 为什么我更新了最新的翻译器还是不行哈哈，edge浏览器 校信&nbsp;&nbsp;、 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "l0o0/translators_CN" ***@***.***&gt;; 发送时间:&nbsp;2023年11月21日(星期二) 晚上11:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [l0o0/translators_CN] Saving with CNKI doesn't work (Issue #231) The problem has been fixed since commit [46c59d9](https://github.com/l0o0/translators_CN/commit/46c59d98541295e9de1111fe666479d4c9bc69f8) 😄 .Many thanks and ❤️ to the contributors — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

朋友你的能用了吗？

**Comment by l0o0** [comment]
你们把网址发出来

weigeqq4 ***@***.***> 于 2023年11月22日周三 下午11:48写道：

**Comment by minatozakiqiao** [comment]
我的edge浏览器突然抓取不了了，茉莉花和扩展管理等方法都试过了还是不行，也未显示抓取失败，甚至还显示了抓取图标，但点了之后几秒就消失了，同样的方法，我的谷歌都还可以抓取，就是edge不行

**Comment by weigeqq4** [comment]
(3)(+0004860): Connector_Browser: onActivated for https://ras.cdutcm.lib4s.com:7080/s/net/cnki/kns/G.https/kcms2/article/abstract?v=vCcGnC-OR23-lkYpQkhZpyvAgIeCxzG9Fy2cvJ7JkAAxhI8PPcNMaZ0j6AZjypm3LBRl4m6ry0Hjf2ABLPJBPxK-fWGxn0Fo7noPztTb_I7A8SCSdffS6PlqUCUxVXai3ipW1kagSnY=&uniplatform=NZKPT&language=CHS

(3)(+0001872): HTTP GET moz-extension://351e2725-c57e-4319-a9d8-ba46bbdc5ea7/utilities/resource/dateFormats.json

(3)(+0003701): Translators: Looking for translators for https://ras.cdutcm.lib4s.com:7080/s/net/cnki/kns/G.https/kcms2/article/abstract?v=vCcGnC-OR23-lkYpQkhZpyvAgIeCxzG9Fy2cvJ7JkAAxhI8PPcNMaZ0j6AZjypm3LBRl4m6ry0Hjf2ABLPJBPxK-fWGxn0Fo7noPztTb_I7A8SCSdffS6PlqUCUxVXai3ipW1kagSnY=&uniplatform=NZKPT&language=CHS

(3)(+0000018): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000007): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000003): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000004): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000003): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000002): Connector: Method getTranslatorCode succeeded

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/getTranslatorCode

(3)(+0000004): Connector: Method getTranslatorCode succeeded

(3)(+0000002): Connector: Method getTranslatorCode succeeded

(4)(+0000013): Translate: Binding sandbox to https://ras.cdutcm.lib4s.com:7080/s/net/cnki/kns/G.https/kcms2/article/abstract?v=vCcGnC-OR23-lkYpQkhZpyvAgIeCxzG9Fy2cvJ7JkAAxhI8PPcNMaZ0j6AZjypm3LBRl4m6ry0Hjf2ABLPJBPxK-fWGxn0Fo7noPztTb_I7A8SCSdffS6PlqUCUxVXai3ipW1kagSnY=&uniplatform=NZKPT&language=CHS

(4)(+0000002): Translate: Parsing code for CNKI (5c95b67b-41c5-4f55-b71a-48d5d7183063, 2023-11-21 14:49:24)

(3)(+0000002): {
    "dbname": "CAPJLAST"
    "filename": "XDKF20231120003"
    "dbcode": "CAPJ"
    "url": "https://ras.cdutcm.lib4s.com:7080/s/net/cnki/kns/G.https/kcms2/article/abstract?v=vCcGnC-OR23-lkYpQkhZpyvAgIeCxzG9Fy2cvJ7JkAAxhI8PPcNMaZ0j6AZjypm3LBRl4m6ry0Hjf2ABLPJBPxK-fWGxn0Fo7noPztTb_I7A8SCSdffS6PlqUCUxVXai3ipW1kagSnY=&uniplatform=NZKPT&language=CHS"
}

(4)(+0000010): Translate: Parsing code for Library Catalog (InnoPAC) (4fd6b89b-2316-2dc4-fd87-61a97dd941e8, 2021-08-04 21:15:52)

(4)(+0000003): Translate: Parsing code for Silverchair (3bae3a55-f021-4b59-8a14-43701f336adf, 2022-08-23 13:00:08)

(4)(+0000003): Translate: Parsing code for unAPI (e7e01cac-1e37-4da6-b078-a0e8343b0e98, 2019-06-10 23:11:21)

(4)(+0000002): Translate: Parsing code for COinS (05d07af9-105a-4572-99f6-a8e231c0daef, 2021-06-01 17:38:46)

(4)(+0000004): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2023-08-16 15:18:29)

(3)(+0000001): Translate: Embedded Metadata: found 5 meta tags.

(4)(+0000001): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2023-10-18 11:11:59)

(3)(+0000004): Translate: All translator detect calls and RPC calls complete:

(3)(+0000001): 	CNKI: 100

(5)(+0000001): Translate: Running handler 0 for translators

(3)(+0001031): Connector_Browser: onActivated for moz-extension://351e2725-c57e-4319-a9d8-ba46bbdc5ea7/preferences/preferences.html#advanced

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000004): Connector: Method ping succeeded

(3)(+0002022): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000013): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707129911

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000001): Translators: Saved updated translator list (740 translators)

(3)(+0000004): Repo: Next check in 86402s

(3)(+0000572): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000013): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707130502

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000003): Repo: Next check in 86402s

(3)(+0000551): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000012): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707131069

(3)(+0000002): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000001): Repo: Next check in 86402s

(3)(+0000249): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000012): Connector: Method getTranslators succeeded

(3)(+0000001): Setting connector.repo.lastCheck.localTime to 1700707131334

(3)(+0000002): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000000): Repo: Next check in 86402s

(3)(+0000227): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000012): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707131575

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000002): Repo: Next check in 86402s

(3)(+0000368): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000013): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707131959

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000002): Repo: Next check in 86402s

(3)(+0000337): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000011): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707132310

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000001): Repo: Next check in 86402s

(3)(+0000370): HTTP POST http://127.0.0.1:23119/connector/getTranslators

(3)(+0000012): Connector: Method getTranslators succeeded

(3)(+0000000): Setting connector.repo.lastCheck.localTime to 1700707132694

(3)(+0000001): Setting translatorMetadata to [{"translatorID":"f3e31f93-c18d-4ba3-9aa6-1963702b5762","translatorType":4,"label":"Ab Imperio","cre

(3)(+0000000): Translators: Saved updated translator list (740 translators)

(3)(+0000001): Repo: Next check in 86402s

(3)(+0002122): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000002): Connector: Method ping succeeded

(3)(+0000807): Connector_Browser: onActivated for about:addons

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000006): Connector: Method ping succeeded

(3)(+0000541): Connector_Browser: onActivated for https://ras.cdutcm.lib4s.com:7080/s/net/cnki/kns/G.https/kcms2/article/abstract?v=vCcGnC-OR23-lkYpQkhZpyvAgIeCxzG9Fy2cvJ7JkAAxhI8PPcNMaZ0j6AZjypm3LBRl4m6ry0Hjf2ABLPJBPxK-fWGxn0Fo7noPztTb_I7A8SCSdffS6PlqUCUxVXai3ipW1kagSnY=&uniplatform=NZKPT&language=CHS

(3)(+0003349): Connector_Browser: onActivated for moz-extension://351e2725-c57e-4319-a9d8-ba46bbdc5ea7/preferences/preferences.html#general

(3)(+0000000): HTTP POST http://127.0.0.1:23119/connector/ping

(3)(+0000004): Connector: Method ping succeeded

**Comment by weigeqq4** [comment]
不知道是哪一个，我发的是您说的浏览器日志里的内容

**Comment by s0wies0** [comment]
我更新了最新的也不行，和之前一样，更新后只能在浏览器插件上显示不同的图标，但无法抓取知网文章元数据和pdf。

**Comment by s0wies0** [comment]
> 我更新了最新的也不行，和之前一样，更新后只能在浏览器插件上显示不同的图标，但无法抓取知网文章元数据和pdf。

试了试直接上知网，抓取没问题。但是vpn登陆之后无法抓取。

**Comment by l0o0** [comment]
我发现原因了，因为使用vpn登录后，往api发送信息的时候，会夹带vpn代理后的网址作为referer，导致返回 的信息不正确。解析不了引文信息，导致没有条目保存 @s0wies0 @weigeqq4

**Comment by s0wies0** [comment]
> 我发现原因了，因为使用vpn登录后，往api发送信息的时候，会夹带vpn代理后的网址作为referer，导致返回 的信息不正确。解析不了引文信息，导致没有条目保存 @s0wies0 @weigeqq4

在这次普遍出问题之前，抓取元数据是没问题的，pdf一直抓不了。
