### ISSUE TITLE
PiShu Data无法在国图VPN下使用

### ISSUE THREAD

**Issue by jiaojiaodubai** [l0o0/translators_CN#239]
登陆国图账号后，vpn浏览皮书数据库，zotero connector即变成国图的图标了，无法抓取数据和pdf。可以解决吗？

_Originally posted by @s0wies0 in https://github.com/l0o0/translators_CN/issues/219#issuecomment-1824132081_

**Comment by jiaojiaodubai** [comment]
已在 [PR#240](https://github.com/l0o0/translators_CN/pull/240) 中修复。@s0wies0

**Comment by s0wies0** [comment]
![image](https://github.com/user-attachments/assets/22b1df6b-5b9e-4ba5-9e90-194f52424aaf)

还是国图vpn下，皮书数据库在整本书页面不显示书的icon，点开章节显示book section图标，但只能作为website保存，且无法直接下载pdf。

**Comment by jiaojiaodubai** [comment]
> 还是国图vpn下，皮书数据库在整本书页面不显示书的icon

请联系我的邮箱 jiaojiaodubai23@gmail.com远程调试

> 点开章节显示book section图标，但只能作为webpage保存，且无法直接下载pdf。

这倒是符合设计预期的
