### ISSUE TITLE
全国图书馆参考咨询联盟书籍元数据中作者显示问题

### ISSUE THREAD

**Issue by 11good11** [l0o0/translators_CN#241]
你好，目前转换器对于图书联盟中所有书籍的元数据中，作者信息的显示均显示在一起，显示有误，望改正，感谢作者！详情如图所示：
![image](https://github.com/l0o0/translators_CN/assets/73817578/9504d88f-b119-44d1-b456-fccbc72ca40c)

**Comment by jiaojiaodubai** [comment]
已在 #242 修复

**Comment by 11good11** [comment]
好的，感谢感谢，我这边直接等茉莉花的转换器更新了

**Comment by 11good11** [comment]
> 已在 #242 修复

http://ytlx.whrsm.ac.cn/CN/abstract/abstract12338.shtml
http://der.tsinghuajournals.com/CN/abstract/abstract155047.shtml
你好，麻烦这两个网址的转换器也修复下，也是类似的问题，谢谢了

**Comment by jiaojiaodubai** [comment]
> http://ytlx.whrsm.ac.cn/CN/abstract/abstract12338.shtml http://der.tsinghuajournals.com/CN/abstract/abstract155047.shtml 你好，麻烦这两个网址的转换器也修复下，也是类似的问题，谢谢了

后面提到的这两个网站可以使用`Metadata.js` 或 `MagTech.js`抓取。
内置的`Metadata.js`的优先级更高，但`Metadata.js`对中文网站兼容性不好，我建议获取 #243 的最新版`MagTech.js`然后如下图使用它来抓取（刚才的PR支持了你提到的网站）。

![image](https://github.com/l0o0/translators_CN/assets/63148861/e971c5e3-e7c8-4eaa-a208-31e6775ad3e7)

**Comment by 11good11** [comment]
> > http://ytlx.whrsm.ac.cn/CN/abstract/abstract12338.shtml http://der.tsinghuajournals.com/CN/abstract/abstract155047.shtml 你好，麻烦这两个网址的转换器也修复下，也是类似的问题，谢谢了
> 
> 后面提到的这两个网站可以使用`Metadata.js` 或 `MagTech.js`抓取。 内置的`Metadata.js`的优先级更高，但`Metadata.js`对中文网站兼容性不好，我建议获取 #243 的最新版`MagTech.js`然后如下图使用它来抓取（刚才的PR支持了你提到的网站）。
> 
> ![image](https://private-user-images.githubusercontent.com/63148861/287207672-e8c946f9-34b4-4015-ae3c-9130b454c069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODAyMzQsIm5iZiI6MTcwMTY3OTkzNCwicGF0aCI6Ii82MzE0ODg2MS8yODcyMDc2NzItZThjOTQ2ZjktMzRiNC00MDE1LWFlM2MtOTEzMGI0NTRjMDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA4NTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YTJiOTUxOWMyMjJhNjllNmYwNzg5ODgyZWQ1OWI5OTIxMTIxMjQ5ZTc2NzMwMzkwNzJiMmFiNWJmMTk2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z9OBzrc0V7fT511lJDJatBmKIJNMXM_jxDVsidaoNbQ)

您好，依旧是全国图书馆参考咨询联盟元数据抓取问题，请看截图，麻烦修复下，感谢感谢😘，而且豆瓣读书上，元数据中作者抓取也有类似的问题，感谢更新
![image](https://github.com/l0o0/translators_CN/assets/73817578/e6c8a1e7-88d6-4638-a0a7-1adb56951129)

**Comment by 11good11** [comment]
> 已修复，同样在 #242 @11good11

感谢感谢，非常感谢
