### ISSUE TITLE
海外知网报错

### ISSUE THREAD

**Issue by OrlandoZh** [l0o0/translators_CN#244]
问题海外知网报错： 更新的11月30的翻译器
https://chn.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTODAY&filename=TDYX2023S1018&uniplatform=OVERSEA&v=HiAQXPZ84leBC0C-MxDl80v-s9DeLFmr9K0J8VwkDPguAINTkRLbD4N98-vbGrMt
![image](https://github.com/l0o0/translators_CN/assets/70483783/586d201d-3e3d-467e-882c-fb7ccaa721c5)

**Comment by OrlandoZh** [comment]
![image](https://github.com/l0o0/translators_CN/assets/70483783/415a0007-17f9-4493-ac1a-3c07c4ab161e)
包括识别

**Comment by jiaojiaodubai** [comment]
@OrlandoZh 你是在VPN环境下使用的吗？

**Comment by yfdyh000** [comment]
茉莉花中更新翻译器并重启Connector扩展后，该链接抓取和元数据抓取正常。

**Comment by OrlandoZh** [comment]
@jiaojiaodubai  香港

**Comment by OrlandoZh** [comment]
@更新茉莉花到1.0.10后获取知网元数据提示无是什么原因

**Comment by OrlandoZh** [comment]
@yfdyh000  更新茉莉花到1.0.10后获取知网元数据提示无是什么原因

**Comment by jiaojiaodubai** [comment]
你好，能给把获取不到的条目发一下吗？我试一下。还是说……所有的条目都获取不到？



---Original---
From: ***@***.***&gt;
Sent at: 2023年12月2日(Sat) Evening10:54
To: ***@***.***&gt;;
***@***.***&gt;;
Subject: Re: [l0o0/translators_CN] 海外知网报错 (Issue #244)




 
@更新茉莉花到1.0.10后获取知网元数据提示无是什么原因

**Comment by Sofiaccch** [comment]
求助：更新了翻译器，浏览器更新了拓展程序，海外知网仍无法抓取父目录。
<img width="242" alt="34f379a62e22b7023bd6bc331a02874" src="https://github.com/l0o0/translators_CN/assets/152897594/7240338a-e44e-4cf3-b88c-7caca4cd884a">
<img width="760" alt="a85c24fd1c36071a2ee14ba17773eae" src="https://github.com/l0o0/translators_CN/assets/152897594/69024296-6602-4422-ac25-ed79e6cb455c">

**Comment by jiaojiaodubai** [comment]
@Sofiaccch 首先按照[这里](https://forums.zotero.org/discussion/comment/449968/#Comment_449968)排查一下，仍有问题请<kbd>Ctrl</kbd>+<kbd>S</kbd>将当前网页保存为`.mhtml`格式并压缩发上来我看看。

**Comment by Sofiaccch** [comment]
> @Sofiaccch 首先按照[这里](https://forums.zotero.org/discussion/comment/449968/#Comment_449968)排查一下，仍有问题请Ctrl+S将当前网页保存为`.mhtml`格式并压缩发上来我看看。

已看了你提供的网页，尽力自查，做过网页里说的步骤，仍不可。麻烦啦！不知道是否理解正确，是把需要抓取的但失败的知网页发给你是吗？请查收。
[《义务教育英语课程标准（2022年版）》：培养科学素养 - 中国知网.zip](https://github.com/l0o0/translators_CN/files/13548678/2022.-.zip)

**Comment by jiaojiaodubai** [comment]
@Sofiaccch @OrlandoZh 我刚才挂梯子测试了一下，问题基本清楚了，跟接口认证有关，解决问题需要一些时间。
你们可以暂时先用知网的[一键导出](https://www.zhihu.com/question/351079330/answer/1727296293)结合Zotero的“从剪贴板导入”（Ctrl + Shif + Alt + I）。

**Comment by Sofiaccch** [comment]
@jiaojiaodubai 感恩！辛苦了！：）

**Comment by jiaojiaodubai** [comment]
6471e94727e56744ac06fa266437d3e25cf189db 已支持海外知网，如有问题可继续反馈。@OrlandoZh @Sofiaccch
