### ISSUE TITLE
豆瓣作者名抓取异常

### ISSUE THREAD

**Issue by jiaojiaodubai** [l0o0/translators_CN#246]
> 豆瓣读书上，元数据中作者抓取也有类似的问题，感谢更新
![image](https://github.com/l0o0/translators_CN/assets/73817578/e6c8a1e7-88d6-4638-a0a7-1adb56951129)

_Originally posted by @11good11 in https://github.com/l0o0/translators_CN/issues/241#issuecomment-1838101021_

**Comment by yfdyh000** [comment]
应该继续在 #241 讨论吧？

**Comment by jiaojiaodubai** [comment]
因为是不同翻译器的问题，所以分开了
