### ISSUE TITLE
更新翻译器及浏览器后，知网父目录抓取仍然失败

### ISSUE THREAD

**Issue by Sofiaccch** [l0o0/translators_CN#247]
更新了翻译器，更新了浏览器拓展程序翻译器后，仍无法抓取知网父目录。提示Save as webpage
<img width="242" alt="34f379a62e22b7023bd6bc331a02874" src="https://github.com/l0o0/translators_CN/assets/152897594/1c1ca883-53cd-4c45-9167-ce334a07a908">
<img width="760" alt="a85c24fd1c36071a2ee14ba17773eae" src="https://github.com/l0o0/translators_CN/assets/152897594/22333208-122b-47f6-b1fd-59e228049c7b">

**Comment by jiaojiaodubai** [comment]
@Sofiaccch 新版本的知网翻译器已经推送，现在问题还存在吗？
