### ISSUE TITLE
征集豆瓣翻译器测试用例

### ISSUE THREAD

**Issue by jiaojiaodubai** [l0o0/translators_CN#261]
**背景** [必填]
为了推进#113，我正在更新豆瓣翻译器（Douabn.js），它的代码风格没有太大的问题，但有进一步简化的空间。我在测试过程中发现[这个](https://www.douban.com/doulist/133232148/)页面的类型识别有问题。此外，翻译器里提到它支持

>  A search listing of books
>  A book html
>  A doulist html
>  A do html
>  A wish html
>  A collect html

但测试用例并没有完全覆盖以上这些类型。其中最令我感到困惑的是这三个：

>  A do html
>  A wish html
>  A collect html

我几乎没使用过豆瓣，我也检索不到以上三种页面的例子。

**你的想法** [必填]
我需要确保更新之后不影响翻译器的功能性，所以希望了解豆瓣的朋友帮我收集一下上面提到的这些网页类型的链接。
或许 @TanGuangZhi  @zepinglee  @hxsnow10 @moleng09 @risshun @11good11 了解这些情况吗？

**Comment by yfdyh000** [comment]
- A search listing of books   读书搜索？https://search.douban.com/book/subject_search?search_text=%E4%B8%AD%E6%96%87&cat=1001 目前不支持？
- A book html  https://book.douban.com/subject/4920007/ 。html=网页。
- A doulist html  https://www.douban.com/doulist/37388265/
- A do html   https://movie.douban.com/mine?status=do 我的在看。
- A wish html  https://movie.douban.com/mine?status=wish 我的想看
- A collect html  https://movie.douban.com/mine?status=collect 我看过的。以及像是 https://movie.douban.com/people/kikikaikai/collect 看别人的。

似乎未支持的：
- https://book.douban.com/series/57510
- https://www.douban.com/location/drama/10863724/
- https://music.douban.com/subject/1405306/
- https://www.douban.com/game/26368768/

**Comment by zepinglee** [comment]
看了一下 blame，我在 <https://github.com/l0o0/translators_CN/commit/87e4924990b8afcd3455b597f8011a6d935e9e64> 中不小心将 `page` 改成了 `html`，可能是不小心全局替换的。

至于 `multiple` 的情况我就没有测试过了。
