### ISSUE TITLE
豆瓣 &amp; 没有替换为 &

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#265]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [ ] 缺少字段、字段错误
- [X] 其他

**发生问题的链接** [必填]
[在此填写链接](https://www.cnki.net/)

https://book.douban.com/subject/3530721/

**问题描述** [必填]

见摘要结果

**你的预期结果**

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [x] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
已在 #264 中修复，待代码审查完毕后会合并到主线，到时记得更新
