### ISSUE TITLE
豆瓣目录笔记没有正确分行

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#271]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://book.douban.com/subject/24531956/

**问题描述** [必填]
目录笔记没有正确分行，笔记名称也不再命名为 《书名》 - 目录

**你的预期结果**
和之前版本一样进行正确分行

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [x] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
已修复。

**Comment by aGolduck** [comment]
> 已修复。

豆瓣音乐曲目有类似问题。
可能电影也有？

**Comment by jiaojiaodubai** [comment]
电影无目录，音乐是我疏忽了，稍后修复
