### ISSUE TITLE
CNKI ISSN

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#275]
**你遇到了什么问题？** [必填]
- [x] 其他

**发生问题的链接** [必填]
[链接](https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDAUTO&filename=SHGL202304028&v=)

**问题描述** [必填]
CNKI期刊中抓取结果无ISSN

**你的预期结果**
包含ISSN项

**浏览器**

- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版

**Comment by doubanchan** [comment]
在“Debug Output Logging”中有输出ISSN，感觉加上问题不大。

**Comment by jiaojiaodubai** [comment]
referBibXI中没有这个字段，原来的正则表达式有问题，我现在已经修复了，正在更新测试用例
