### ISSUE TITLE
豆瓣电影剧集类日期的关键词是”首播“不是”上映时间“

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#278]
剧集类现在剪辑不到日期信息

**Comment by jiaojiaodubai** [comment]
我现在能够在代码中区分“[电影](https://movie.douban.com/subject/4860078/)”和“[电视剧](https://movie.douban.com/subject/35840681/)”，并且分别获取它们的上映时间或首播时间，但豆瓣的“电视剧”是指整个电视节目，而Zotero中的`tvBroadcast`却是指电视节目中的某一集。豆瓣虽然有[分集的页面](https://movie.douban.com/subject/35840681/episode/5/)，可是信息太少，抓取意义不大。豆瓣的这种电视节目应该不能作为`film`记录吧？我不知道怎么办才好了。@zepingLee

**Comment by zepinglee** [comment]
> 但豆瓣的“电视剧”是指整个电视节目，而Zotero中的`tvBroadcast`却是指电视节目中的某一集

Zotero 确实是这么规定的，不过如果 `programTitle` (`publicationTitle`) 为空，导出为 CSL 的 `broadcast` 类型会看作是整个剧集。因为 CSL 的 [spec](https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types) 是这么描述的：

> broadcast
>
> If container-title is present, the item is interpreted as an episode contained within a larger broadcast series (e.g. an episode in a television show or an episode of a podcast)

其中 `container-title` 对应 Zotero 的 `programTitle` (`publicationTitle`)。

**Comment by jiaojiaodubai** [comment]
原来如此，那我可以马上修复这个问题了。

**Comment by jiaojiaodubai** [comment]
已在 3ad9b7d48394292ab91d450292db1329a72ed782 修复（提交信息有错字，真是不好意思）
