### ISSUE TITLE
请问现在支持超星期刊吗

### ISSUE THREAD

**Issue by macchen123** [l0o0/translators_CN#28]
我保存超星期刊里的论文出现了这个错误
![image](https://user-images.githubusercontent.com/40541246/107118273-e0fce880-6877-11eb-8515-cdb96cbf60b2.png)

**Comment by Lemmingh** [comment]
**不支持**

<https://github.com/l0o0/translators_CN/blob/ddafc0cbce4db5797d267031487ba3546d736d4e/README.md#-%E7%9B%AE%E6%A0%87%E7%BD%91%E7%AB%99>

---

打开你展示的那个网页
<http://qikan.chaoxing.com/detail_38502727e7500f26bd22f7bc9ed20ad3e4fb5bbaf72b88231921b0a3ea255101fc1cf1fbb4666ae67ef87c686f84d771445d9193bb355f397b8f31c55cb113227af02114356bfcb51daa50110d69f9b3>

把鼠标放到 Zotero Connector 的图标上，提示是

> Save to Zotero (DOI)

所以，点击后，调用的是官方仓库的 DOI (c159dcfe-8a53-4301-a499-30f6549c340d)
<https://github.com/zotero/translators/blob/99a685ab2939db5264f39edfc8cbf106373aa985/DOI.js>

它进而调用 DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9)
<https://github.com/zotero/translators/blob/17e3773bcb3e8a56767eec29f160e2eb67d0832c/DOI%20Content%20Negotiation.js>

试图访问
<https://doi.org/10.3969/j.issn.1003-6970.2020.04.016>

然而那个页面返回 `404 Not Found`。自然会出错。

**Comment by macchen123** [comment]
好吧，谢谢回复



---原始邮件---
发件人: "Lemmingh"<notifications@github.com&gt;
发送时间: 2021年2月6日(周六) 晚上11:20
收件人: "l0o0/translators_CN"<translators_CN@noreply.github.com&gt;;
抄送: "macchen123"<1247290501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [l0o0/translators_CN] 请问现在支持超星期刊吗 (#28)




 
不支持
 
https://github.com/l0o0/translators_CN/blob/ddafc0cbce4db5797d267031487ba3546d736d4e/README.md#-%E7%9B%AE%E6%A0%87%E7%BD%91%E7%AB%99
 
 
打开你展示的那个网页
 http://qikan.chaoxing.com/detail_38502727e7500f26bd22f7bc9ed20ad3e4fb5bbaf72b88231921b0a3ea255101fc1cf1fbb4666ae67ef87c686f84d771445d9193bb355f397b8f31c55cb113227af02114356bfcb51daa50110d69f9b3
 
把鼠标放到 Zotero Connector 的图标上，提示是
  
Save to Zotero (DOI)
  
所以，点击后，调用的是官方仓库的 DOI (c159dcfe-8a53-4301-a499-30f6549c340d)
 https://github.com/zotero/translators/blob/99a685ab2939db5264f39edfc8cbf106373aa985/DOI.js
 
它进而调用 DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9)
 https://github.com/zotero/translators/blob/17e3773bcb3e8a56767eec29f160e2eb67d0832c/DOI%20Content%20Negotiation.js
 
试图访问
 https://doi.org/10.3969/j.issn.1003-6970.2020.04.016
 
然而那个页面返回 404 Not Found。自然会出错。

**Comment by l0o0** [comment]
你可以试试在知网里搜索，知网应该包括大多数期刊的 @macchen123

**Comment by l0o0** [comment]
#92
