### ISSUE TITLE
豆瓣电影剪辑标题为空

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#281]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

如题

**发生问题的链接** [必填]
https://movie.douban.com/subject/26603847/

**浏览器**

- [X] Chrome（谷歌浏览器）
- [X] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [x] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
有标题啊（虽然标题分割不太合理）

**Comment by aGolduck** [comment]
![Xnip2024-01-09_10-45-07](https://github.com/l0o0/translators_CN/assets/2016363/93059583-9b3a-4a16-a269-b43e5fee280d)
你看到的是这个结果吗？我昨天更新以后就这样

**Comment by jiaojiaodubai** [comment]
还确实是哦……我更新以后是你这个结果，我马上修复一下，昨天为了照顾某些英文翻译的标题，修改了标题的匹配方式

**Comment by jiaojiaodubai** [comment]
已修复
