### ISSUE TITLE
Sina Weibo

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#284]
**你想申请哪个网站的翻译器？** [必填]
[新浪微博](https://weibo.com)

**网站描述** [必填]
微博客服务，可以参考[Twitter.js](https://github.com/zotero/translators/blob/master/Twitter.js)。之前开了个头，见[Sina Weibo.js](https://github.com/pixiandouban/translators/blob/master/Sina%20Weibo.js)。

**条目类型**
- [x] ForumPost

**网站权限**
- [x] 通常不需要注册

**Comment by jiaojiaodubai** [comment]
> 微博客服务

这句话是什么意思？

**Comment by yfdyh000** [comment]
> > 微博客服务
> 
> 这句话是什么意思？

“微博”类服务的的规范化名称。
https://www.12377.cn/gfwj/2020/ff8afe59_web.html

**Comment by doubanchan** [comment]
新浪微博是一种微博客（microblog）服务。上面的[Twitter.js](https://github.com/zotero/translators/blob/master/Twitter.js)，不知道是不是因为改版原因，现在抓取失败。

**Comment by jiaojiaodubai** [comment]
推特的代码实际上非常老旧了，我已经清空原[Sina Weibo.js](https://github.com/pixiandouban/translators/blob/master/Sina%20Weibo.js)的代码从头写了。里面提到的旧版微博我有印象，但我现在找不到切换旧版的入口。

**Comment by jiaojiaodubai** [comment]
已在 #287 完成。
