### ISSUE TITLE
Nlc.cn.js 文件名和有效性

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#288]
该目前的这个 Nlc.cn.js只是中国国家图书馆中的[中国标准在线服务网](http://read.nlc.cn/outRes/outResList?type=%E6%A0%87%E5%87%86%E4%B8%93%E5%88%A9)的数据库（和[Spc.org.cn](https://github.com/l0o0/translators_CN/blob/master/Spc.org.cn.js)内容有些类似，另外SPC应该是Standards Press of China/中国标准出版社缩写），且似乎好像无法正常抓取，建议先将其改名 Nlc.cn standard.js或者相关名称，不应该占用整个国图的域名。

**Comment by jiaojiaodubai** [comment]
Nlc.cn.js我连域名都进不去，所以在LintIt里面也没有改它

**Comment by doubanchan** [comment]
nlc.cn.js中提到的标准数据库需要注册国图账号才能进入和阅览。

**Comment by jiaojiaodubai** [comment]
> 需要注册国图账号

普通的用户的帐号就可以吗？不需要机构帐号或者和机构绑定的帐号？

**Comment by doubanchan** [comment]
不需要机构账号，需要登录的地方，个人自己注册就可以（暂时没遇见过需要机构账号的情况）。

**Comment by jiaojiaodubai** [comment]
本来想抢救一下，但是过程中发现这个网站的数据也太糙了，好多都没有归口单位和页码。
再者，有些信息似乎是错的，如GB/T 7714-2015的“发布日期”那里，居然写“1987-05-05”，按理说，同名不同号的标准不是应该区分的吗？它这怎么把“发布日期”算到祖上十八辈去了。

**Comment by jiaojiaodubai** [comment]
已在#292 中提交，请审查。
