### ISSUE TITLE
小宇宙 xiaoyuzhoufm

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#289]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目

**发生问题的链接** [必填]
[播客](https://www.xiaoyuzhoufm.com/episode/659f88316d045a7f5ed18dac)

**问题描述** [必填]
“使用 xiaoyuzhoufm 保存时发生错误。改为尝试用 Embedded Metadata 保存。”

**浏览器**
- [x] FireFox（火狐浏览器）

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版

**Comment by jiaojiaodubai** [comment]
这个翻译器的代码早已过时，我已知晓这一情况，且[无意更新它](https://github.com/jiaojiaodubai/translators_CN/tree/LintIt)，除非有用户用户再提出需求吧。
