### ISSUE TITLE
无法通过右键“找到可用的pdf”,下载到知网的pdf，有获取pdf权限

### ISSUE THREAD

**Issue by sunzhouhong** [l0o0/translators_CN#29]

**Comment by l0o0** [comment]
右键 查找可用的PDF 是 Zotero 自带的功能，一般是从一些开放数据库里根据条目的DOI信息来获取免费的PDF。知网不在此列，所以没有效果。这个应该不属于这个项目的功能，你可以到茉莉花插件那里提需求。不过我也在考虑添加这个功能
