### ISSUE TITLE
如果不和其他引注格式冲突，微信翻译器抓取时，请问可否填写“微信公众号”到“网站类型”字段？

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#290]
**你遇到了什么问题？** [必填]
- [x] 其他

**发生问题的链接** [必填]
http://mp.weixin.qq.com/s?__biz=Mzg2Nzc4ODA4NA==&mid=2247494843&idx=1&sn=7effbde066b995d93a5199c4cf9b9942&chksm=ceb498e0f9c311f631b5f9c685a8e3b6bf30014492b74033b601e4b09d8d520936553f86ac6c#rd

**问题描述** [必填]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/248#issuecomment-1890991721
由于法学引注手册对微信公众号的引注有特别要求，例如下图。如果不和其他引注格式冲突，微信翻译器抓取时，请问可否填写“微信公众号”到“网站类型”字段（现在是“微信公众平台”）？
![image](https://github.com/l0o0/translators_CN/assets/50101175/82bca04b-8b86-4d3f-8f99-520cfaffb162)

**Comment by jiaojiaodubai** [comment]
不存在技术难度，规范方面得请教 @zepinglee

**Comment by zepinglee** [comment]
> 不存在技术难度，规范方面得请教 @zepinglee

据我了解除《法学引注手册》外没有其他体例规定了“微信公众号”的格式，所以 `websiteType` 这么填没什么问题。

**Comment by jiaojiaodubai** [comment]
已在 ad1c3e7b9e1dc3e0699606a2fdcb87eddfc34707 完成，22:00后即可通过茉莉花获取最新版微信转换器。原先写“微信公众平台”是因为网站元数据就是这么写的。

**Comment by yzy1228682367** [comment]
感谢大佬❤️
