### ISSUE TITLE
dpaper.js 改善

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#293]
**CSTR**
建议加上CSTR唯一标识符
**URL**
URL可以只保留……paperID=数字
比如[case1](http://dpaper.las.ac.cn/Dpaper/detail/detailNew?paperID=20172916)，简短网址可以访问
**大学**
newItem.university，认为应该是“中国科学院大学”，一般指学位授予机构，其所在的研究所一般应该不能授予学位。
培养单位： “昆明动物研究所”可以考虑放到extra字段。
**creator**
https://github.com/l0o0/translators_CN/blob/42ad036bae33e18f5506d1266cc27c593ff92400/dpaper.js#L4

**Comment by jiaojiaodubai** [comment]
于 9bfdfd20d3289000e809be1c36f5dbfcbd406561 完成。
