### ISSUE TITLE
flk.npc.gov.cn

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#294]
**你想申请哪个网站的翻译器？** [必填]
[国家法律法规数据库](https://flk.npc.gov.cn/)

**网站描述** [必填]
全国人大常委会办公厅维护的法律法规数据库，包括中华人民共和国现行有效的宪法（含修正案）、法律、行政法规、监察法规、地方性法规、自治条例和单行条例、经济特区法规、司法解释电子文本。

**条目类型**
- [x] 法律

**网站权限**
- [x] 免费阅读

**Comment by jiaojiaodubai** [comment]
这个网站在北大法宝的相关讨论里提到过，我已经加入个人todo，只是暂时还没照顾得到。

**Comment by jiaojiaodubai** [comment]
缺少发文号，可能没有制作转换器的必要。

**Comment by jiaojiaodubai** [comment]
完成于 #302，请审查。
