### ISSUE TITLE
豆瓣电影演员被列为导演

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#299]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://movie.douban.com/subject/35725869/

**问题描述** [必填]
演员被列为导演，看起来是同一个被列了两次，一次是导演，一次是贡献者，比如这《年会不能停！》这条的大鹏和白客

**你的预期结果**
各个参与人员分配到正确的角色

**浏览器**

- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
修复于 125c3dbdf8bd894fbeadb4a7118005ba4f3ed3d6。
