### ISSUE TITLE
问一个有些不相关的问题

### ISSUE THREAD

**Issue by weidongzhou1994** [l0o0/translators_CN#3]
您好！打扰一下，请问zotero如何抓取 百度学术 呢？仅仅是替换baidu scholar.js吗？貌似不行。

**Comment by l0o0** [comment]
你好，我这边测试了下，发现百度学术是有问题。我会修复这个问题

**Comment by l0o0** [comment]
@weidongzhou1994 同学你能详细描述下具体的问题么？可以提供下对应的文章链接，我可以测试一下
