### ISSUE TITLE
刊物检索后，随便选一个月的期刊，不能批量下载pdf，进入详情页后，单独可以下载pdf

### ISSUE THREAD

**Issue by sunzhouhong** [l0o0/translators_CN#30]
https://navi.cnki.net/knavi/JournalDetail?pcode=CJFD&pykm=ZDJY

**Comment by sunzhouhong** [comment]
navi.cnki.net 这个域名是不是没有识别

**Comment by l0o0** [comment]
我看这个应该是可以的，不过你给的链接中，没有具体的文章信息。如果点击左侧发行时间，加载对应的文章，是可以抓取的
![图片](https://user-images.githubusercontent.com/2743744/109619022-396f8f00-7b73-11eb-99e2-e62fd6faa82c.png)
不过附件链接的抓取倒是有问题

**Comment by sunzhouhong** [comment]
题录可以抓取，pdf全文好像还不行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linxzh"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午4:21
收件人: "l0o0/translators_CN"<translators_CN@noreply.github.com&gt;; 
抄送: "sun.soaring"<30413345@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [l0o0/translators_CN] 刊物检索后，随便选一个月的期刊，不能批量下载pdf，进入详情页后，单独可以下载pdf (#30)





 
我看这个应该是可以的，不过你给的链接中，没有具体的文章信息。如果点击左侧发行时间，加载对应的文章，是可以抓取的
 
 不过附件链接的抓取倒是有问题
