### ISSUE TITLE
豆瓣电影标题为多语言失败

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#300]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://movie.douban.com/subject/1308843/
https://movie.douban.com/subject/1450031/
https://movie.douban.com/subject/3183628/

**问题描述** [必填]
如题

**你的预期结果**
正确剪辑

**浏览器**

- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
修复于 52c442c97cbeaf5bc982b24c1a3ade9cbace8086。

**Comment by aGolduck** [comment]
建议是把这些 bad case 加到测试里，感觉快速迭代很容易挂一漏万。如果原网页不频烦更新，这些 test cases 还是能在一段时间内有效。

**Comment by jiaojiaodubai** [comment]
感谢你的建议。test  cases主要展示的是对各种条目的支持，因为这些条目的抓取方法和对字段的要求不太一样。而bad case我会以注释形式放到相关代码处，我认为这样更有指向性、解释性。
