### ISSUE TITLE
北大法宝/Pkulaw 子域名

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#303]
**你遇到了什么问题？** [必填]
- [x] 其他

**发生问题的链接** [必填]
[北大法宝 中国法律检索系统](https://law.pkulaw.com/)

**问题描述** [必填]
[北大法宝·中国法律检索系统](https://law.pkulaw.com/)中的法律法规可以免费查阅，不像法宝主站均为付费版。

**Comment by yzy1228682367** [comment]
法宝主站法律也是免费的吧？收费的规章、法规这些？

**Comment by doubanchan** [comment]
看了下该子域名，分为宪法、法律、法律解释（全国人大）、行政法规、监察法规、地方性法规、部门规章（国务院各部门）、地方政府规章、司法解释（最高法），应该只有效力位阶属于宪法、法律的部分是免费的，其余部分在法宝主站收费。可能要讨论下是否值得添加到pkulaw.js转换器中。

**Comment by jiaojiaodubai** [comment]
看了一下，界面风格非常相似，适配起来应该不难
