### ISSUE TITLE
pubscholar 改善

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#304]
**你遇到了什么问题？** [必填]
- [x] 其他

**发生问题的链接** [必填]
[学位论文](https://pubscholar.cn/articles/656ef23fb7c7102a0785c59494004e7d97ea90bfb81eec6e25e65c17f2ab63eddce7de1ef7c0de56ab558f34701acd08)
[预印本](https://pubscholar.cn/articles/f338efc1a3149a83528f6bedbd9e14a2256d7785342a0f9e315c4386c028335c176d4583f3cd44fa1a3ea5a4982c762b)

**问题描述** [必填]
学位论文、预印本统一识别到了期刊论文。

**其他**
1、包括期刊论文、学位论文、预印本论文网也皆有“合作资源方链接”或搜索界面的“原文链接”，pubscholar应该是和baidu scholar、Googel scholar一样是个学术聚合网站，本身只提供元数据，全文链接在原始网站，个人认为最好将附上原始网站的链接附在extra中。（中文期刊：维普，外文期刊：期刊官网、DOAJ，学位论文：dpaper、科睿唯安（北京中科进出口），预印本：**xiv）
2、部分图书提供直接下载链接，[例1](https://pubscholar.cn/books/ee3b019c3eda4207bea6a337c8ca9fe62aa092a41d5b43ba88638490e262f62c8029e162b1ef427b2ba92aa5b76ca129)

**Comment by doubanchan** [comment]
**原文链接**
个人想法，根据[Zotero](https://www.zotero.org/support/dev/translators/coding)，可以将非pubscholar的原文链接放在附件（attachments）中。
```
var linkURL = "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC" + ids[i] + "/";
newItem.attachments = [{
	url: linkURL,
	title: "PubMed Central Link",
	mimeType: "text/html",
	snapshot: false
}];
```
举例，[case](https://pubscholar.cn/articles/e0557c152e0364026ecd163515d2300c50007053f0b582c293ed4c70029d337c30183c98f91f023ebe9acf9c0bfe0315)，可以分别添加[期刊官网](https://linkinghub.elsevier.com/retrieve/pii/S1674987123001688)和[DOAJ](https://doaj.org/article/c46547d3712342338c8bc1d3a0fa446f)

**Comment by jiaojiaodubai** [comment]
我现在点进case里面根本不识别，看来是网站又改了，得抽时间适配

**Comment by jiaojiaodubai** [comment]
已在 50c805e9663038b9133817bb28a8a0e752cf0f12 部分完成；关于附件的处理，由于文献来源的链接是网站JS自身维护的变量，逆向分析比较困难，暂不考虑支持。不过在其他转换器中会考虑你提到的情况。
