### ISSUE TITLE
国家科技图书文献中心/National Science and Technology Library/NSTL

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#307]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目

**发生问题的链接** [必填]
[链接](https://www.nstl.gov.cn/paper_detail.html?id=11548b4483a0090a29ff858849128255)

**问题描述** [必填]
如：“作者”字段没有分开。
在Firefox、Chrome均未识别；在编辑器Scaffold上“TranslatorTester: National Science and Technology Library - China `Test 1: failed (Detection failed)`”

**你的预期结果**
如：“作者”名字应该分开。

**浏览器**
- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）
- [x] Scaffold

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版

**其他**
似乎无有效的调试信息；否能解释下detectWeb，不了解monitorDOMChanges。

**Comment by jiaojiaodubai** [comment]
Edge 未能复现以上错误。
![image](https://github.com/l0o0/translators_CN/assets/63148861/6161bb7f-d8f4-4965-b231-fb55f697e7aa)
![image](https://github.com/l0o0/translators_CN/assets/63148861/46459797-597a-4493-8508-648270ecc377)

**Comment by doubanchan** [comment]
加了一行	**Z.debug( typeof zhType );**，Scaffold中结果是 **undefined**
https://github.com/l0o0/translators_CN/blob/441258e74df898791b7d27f56a250426688189f0/National%20Science%20and%20Technology%20Library%20-%20China.js#L56

**Comment by jiaojiaodubai** [comment]
> 否能解释下detectWeb，不了解monitorDOMChanges。

`monitorDOMChanges()`，第一个参数是要监测的Element，第二个参数是监测属性，当第一个参数的Element发生第二个参数所描述的变化时，再次触发`detectWeb()`重新判断页面类型，用于在动态加载的页面等待相关元素加载出来。

**Comment by jiaojiaodubai** [comment]
> 在Firefox、Chrome均未识别；在编辑器Scaffold上“TranslatorTester: National Science and Technology Library - China Test 1: failed (Detection failed)
> 加了一行 Z.debug( typeof zhType );，Scaffold中结果是 undefined

说明在你的页面中未获取到“期刊论文”这几个字，你打开dev tools看一下，标题前面的“【期刊论文】”这几个字应该是什么`selector`？

**Comment by jiaojiaodubai** [comment]
@doubanchan  这个问题还存在吗？
