### ISSUE TITLE
为「国家哲学社会科学文献中心」增加「.cn」域名支持。

### ISSUE THREAD

**Issue by konxina** [l0o0/translators_CN#313]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目
- [x] 无法保存条目
- [ ] 无法下载附件
- [ ]  缺少字段、字段错误
- [x] 其他

**发生问题的链接** [必填]
[国家哲学社会科学文献中心](https://www.ncpssd.cn/)

**问题描述** [必填]
国家哲学社会科学文献中心正在转移域名，将逐步由「www.ncpssd.org」转移至「www.ncpssd.cn」。
现正处于缓冲期，两域名皆可使用。

**你的预期结果**
为兼容性考虑，增加对「.cn」域名的支持。

**Comment by jiaojiaodubai** [comment]
完成于 35faf2396ed723ede95b796445974122fd605156
