### ISSUE TITLE
豆瓣 translator 是否能把海报作为附件

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#315]
以前见过 imdb 可以做到

**Comment by iiwenwen** [comment]
目前来看只能将海报下载后放入附件中，实现类似功能的有calibre的元数据获取功能。

**Comment by aGolduck** [comment]
@jiaojiaodubai 书籍和音乐是否考虑也一起加入，新版 zotero 将右侧的摘要钉住后视觉效果相当棒。
![Xnip2024-03-18_14-18-26](https://github.com/l0o0/translators_CN/assets/2016363/6d4cfc95-9850-4f4d-8837-fdf4d42d6c08)

**Comment by jiaojiaodubai** [comment]
下载附件会拖慢抓取速度，如果不是确有研究需要，我个人不打算将图书和专辑的封面加入到附件中。---原始邮件---发件人: ***@***.***>发送时间: 2024年3月18日(周一) 下午2:19收件人: ***@***.***>;抄送: ***@***.***>***@***.***>;主题: Re: [l0o0/translators_CN] 豆瓣 translator 是否能把海报作为附件 (Issue #315)
@jiaojiaodubai 书籍和音乐是否考虑也一起加入，新版 zotero 将右侧的摘要钉住后视觉效果相当棒。
Xnip2024-03-18_14-18-26.jpg (view on web)
