### ISSUE TITLE
北大法宝翻译器似乎存在部分问题。

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#316]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
(https://www.pkulaw.com/pfnl/95b2ca8d4055fce1c5f1fba8de4bd9a2b8d2091306f66181bdfb.html)

**问题描述** [必填]
1.审判法院会把“注”也加入
2.语言会被设置为“en”
3.“genre”和“法宝印证码”会连在一起，致使输出引注时也被一起带入。
![CleanShot 2024-02-24 at 16 29 33](https://github.com/l0o0/translators_CN/assets/50101175/49774142-6914-4206-b3cd-bc17246b547e)
![CleanShot 2024-02-24 at 16 39 15@2x](https://github.com/l0o0/translators_CN/assets/50101175/76553b28-dde1-48e8-9b7c-c28476fe349a)

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [x] 其他 ARC

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [x] 我尝试过重启浏览器、Zotero或电脑
- [x] 我使用VPN访问
- [x] 我使用校园网直接访问
- [ ] 我在海外访问

**附件**

**Comment by yzy1228682367** [comment]
另外可以请问下开发者您的快照抓取功能能够正常使用吗？我目前是beta62，chrome、edge和arc都没有办法抓取网页快照(/∇＼*)

**Comment by jiaojiaodubai** [comment]
可以抓取的

**Comment by yzy1228682367** [comment]
> 可以抓取的

啊哦，好哩谢谢❤️
