### ISSUE TITLE
专利之星BUG

### ISSUE THREAD

**Issue by yangtzech** [l0o0/translators_CN#32]
有的专利存在申请和授权两个文件，目前只能获取申请的文件 [1]，而授权了的文件[2]无法获取。
文件[2]包含[1]中信息，建议有[2]的取[2]，没[2]的取[1]。
![S$22__8`P 37{%N4)QYN@$O](https://user-images.githubusercontent.com/41911522/112080433-f6766980-8bbc-11eb-81f1-3d040c17d491.png)

**Comment by wanyzh** [comment]
能不能发一个同时有申请文件和授权文件的链接？我测试修改下。

**Comment by yangtzech** [comment]
试试这个
http://cprs.patentstar.com.cn/Search/Detail?ANE=7BEA9GDA5EAA9FBG3ACA7EDA9BHA9BFE9IED9GBCBICA9HIH

**Comment by wanyzh** [comment]
> 试试这个
> http://cprs.patentstar.com.cn/Search/Detail?ANE=7BEA9GDA5EAA9FBG3ACA7EDA9BHA9BFE9IED9GBCBICA9HIH

好的，我抽空测试下。

**Comment by yangtzech** [comment]
> > 试试这个
> > http://cprs.patentstar.com.cn/Search/Detail?ANE=7BEA9GDA5EAA9FBG3ACA7EDA9BHA9BFE9IED9GBCBICA9HIH
> 
> 好的，我抽空测试下。

多谢

**Comment by wanyzh** [comment]
@yangtzech 中午休息时间修改了下这个translator，我这里测试了几个例子没问题，你先试试看，没问题我再pl。
https://github.com/wanyzh/translators_CN/blob/master/translators/PatentStar.js

**Comment by yangtzech** [comment]
> @yangtzech 中午休息时间修改了下这个translator，我这里测试了几个例子没问题，你先试试看，没问题我再pl。
> https://github.com/wanyzh/translators_CN/blob/master/translators/PatentStar.js

可以获取到授权后文件。多谢。

**Comment by yangtzech** [comment]
@wanyzh 但是未授权的专利的专利号是主动不填写的吗？

**Comment by wanyzh** [comment]
> @wanyzh 但是未授权的专利的专利号是主动不填写的吗？

应该有的，patent number和application number都有。你发个有问题的链接和截图看看？

**Comment by yangtzech** [comment]
> > @wanyzh 但是未授权的专利的专利号是主动不填写的吗？
> 
> 应该有的，patent number和application number都有。你发个有问题的链接和截图看看？

不好意思，是失效的专利不填写。然后我看代码在这个地方有个判断

**Comment by wanyzh** [comment]
> > > @wanyzh 但是未授权的专利的专利号是主动不填写的吗？
> > 
> > 
> > 应该有的，patent number和application number都有。你发个有问题的链接和截图看看？
> 
> 不好意思，是失效的专利不填写。然后我看代码在这个地方有个判断

嗯，是的，失效的专利我屏蔽了专利号，如果需要可以把这个地方注释掉。
![Snipaste_2021-03-24_15-03-05](https://user-images.githubusercontent.com/31266986/112268596-2e130d80-8cb2-11eb-96f1-40848cbfdc3f.png)

**Comment by yangtzech** [comment]
> > > > @wanyzh 但是未授权的专利的专利号是主动不填写的吗？
> > > 
> > > 
> > > 应该有的，patent number和application number都有。你发个有问题的链接和截图看看？
> > 
> > 
> > 不好意思，是失效的专利不填写。然后我看代码在这个地方有个判断
> 
> 嗯，是的，失效的专利我屏蔽了专利号，如果需要可以把这个地方注释掉。
> ![Snipaste_2021-03-24_15-03-05](https://user-images.githubusercontent.com/31266986/112268596-2e130d80-8cb2-11eb-96f1-40848cbfdc3f.png)

多谢

**Comment by l0o0** [comment]
这个翻译器，需要更新嘛？

**Comment by wanyzh** [comment]
> 这个翻译器，需要更新嘛？

需要更新，我晚上提交PL

**Comment by l0o0** [comment]
@wanyzh 麻烦老哥了
