### ISSUE TITLE
豆瓣部分书籍「其他」字段内容出现错误

### ISSUE THREAD

**Issue by iiwenwen** [l0o0/translators_CN#324]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
[极简个性心理学：破解人格基因 (豆瓣)](https://book.douban.com/subject/27045485/)
[东京八平米 (豆瓣)](https://book.douban.com/subject/36096287/)
[同意 (豆瓣)](https://book.douban.com/subject/35947066/)

**问题描述** [必填]
“其他”字段中出现非预期的错误，一段json内容包含豆瓣页面中作者firstName与lastName信息。目前测试，因为作者名中出现“国家”才会出现该问题，不知是有意设置还是BUG。

**你的预期结果**
“其他”字段不包含多余的内容。

**浏览器**

- [x] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [x] 其他（Arc浏览器）

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [x] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**附件**

<img width="288" alt="Snipaste_2024-03-12_21-12-32" src="https://github.com/l0o0/translators_CN/assets/25455839/56e24e9a-8338-44d7-ad6d-5fa267f4ff67">

**Comment by jiaojiaodubai** [comment]
这是有意设置的，一些引注格式要求输出作者的国籍，而官方的数据结构又不支持存储额外的“国籍”信息，所以我们增加了这个字段，通过 Zotero format metadata插件，你可以在需要的时候读取Extra中的JSON数据，实现快速批量添加国籍或移除国籍，详见[#106](https://github.com/northword/zotero-format-metadata/issues/106)。
