### ISSUE TITLE
patsnap专利库翻译器申请

### ISSUE THREAD

**Issue by ypZhang-2020** [l0o0/translators_CN#325]
**你想申请哪个网站的翻译器？** [必填]
[在此填写链接](https://analytics.zhihuiya.com/)

**网站描述** [必填]
可以支持多个国家的专利查询和下载

**条目类型**

- [是] 专利

**网站权限**
- [是] 需要注册帐号
- [ 可能] 需要购买服务或使用机构帐号登录

**Comment by jiaojiaodubai** [comment]
这个以前有人提到过（#135），就是智慧芽嘛，但是我没有帐号就一直没法做

**Comment by jiaojiaodubai** [comment]
完成于 21726b3c8a32ac4ef012f6df9ad024c5454eb0ff，由于网站的版权保护，转换器不支持批量抓取以及抓取PDF。
