### ISSUE TITLE
TOAJ

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#329]
**你遇到了什么问题？** [必填]
- [x] 无法下载附件

**发生问题的链接** [必填]
[文章连接](https://toaj.stpi.narl.org.tw/index/journal/volume/article/4b1141f98a421cb5018a4a6ce9a50175)

**问题描述** [必填]
点击网页中[[全文電子檔下載]](https://toaj.stpi.narl.org.tw/file/article/download/4b1141f98a421cb5018a4a6ce9a50175)按钮，可以下载，在Zotero不能下载pdf

**浏览器**
- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）

**Comment by jiaojiaodubai** [comment]
转换器获取的链接与实际下载链接并无差别，且translator无法干预附件的下载过程。
