### ISSUE TITLE
是否考虑将电影风格放入「流派」字段

### ISSUE THREAD

**Issue by iiwenwen** [l0o0/translators_CN#332]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [ ] 缺少字段、字段错误
- [x] 其他

**发生问题的链接** [必填]
NA
**问题描述** [必填]
Zotero电影条目中有「流派」字段。

<img width="301" alt="image" src="https://github.com/l0o0/translators_CN/assets/25455839/0d977ae6-efb8-4d3d-803a-306baaead547">

Zotero官网[kb：item\_types\_and\_fields [Zotero 文档] --- kb:item\_types\_and\_fields [Zotero Documentation]](https://www.zotero.org/support/kb/item_types_and_fields#general_fields)将Genre作为电影的类型字段。

<img width="743" alt="20240318141621" src="https://github.com/l0o0/translators_CN/assets/25455839/64dca7aa-0d95-4933-bff1-8fcbbd306e49">

目前豆瓣电影的类型是作为额外字段存在在「其他」中，是否考虑将电影风格放入「流派」字段中。

**你的预期结果**
在「流派」字段中显示电影类型。

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [x] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by zepinglee** [comment]
见 <https://github.com/l0o0/translators_CN/pull/264#issuecomment-1870348985>，像 APA 需要在 `genre` 填入 “Film”，似乎与 Zotero 的文档冲突。我再问一下 Zotero 官方吧。

**Comment by zepinglee** [comment]
CSL 的 [spec](https://docs.citationstyles.org/en/stable/specification.html) 中要求：

> genre... Do not use for topical descriptions or categories (e.g. “adventure” for an adventure movie)

<https://forums.zotero.org/discussion/comment/459727/#Comment_459727> 已经回复了：

> CSL is right, Zotero docs are wrong.

**Comment by iiwenwen** [comment]
好的，了解，多谢。
