### ISSUE TITLE
掌桥科研语种

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#334]
**你遇到了什么问题？** [必填]
- [x] 其他

**发生问题的链接** [必填]
[case](https://www.zhangqiaokeyan.com/journal-foreign-detail/0704016959221.html)

**问题描述** [必填]
1、日语有jpn标识，见[case](https://www.zhangqiaokeyan.com/journal-foreign-detail/0704016959221.html)；
2、数据库中有俄语文献，见[case](https://www.zhangqiaokeyan.com/journal-foreign-detail/0704033042606.html)。
3、日语的语言标识jp-JP，是不是应该是ja-JP，或ja？
[这里](https://github.com/citation-style-language/locales/blob/master/locales-ja-JP.xml)使用用的是ja-jp。

**Comment by zepinglee** [comment]
> 日语的语言标识jp-JP，是不是应该是ja-JP，或ja？

确实应该是 `ja-JP`。

对于 CSL 来说，`ja-JP` 或 `ja` 都可以，因为 [locales.json#L27](https://github.com/citation-style-language/locales/blob/cf4b49404fc15cf9a37372e4707ce710b0935ccc/locales.json#L27) 设置了 `ja` primary-dialect 为 `ja-JP`。不过 Zotero 的文档中 <https://www.zotero.org/support/kb/item_types_and_fields#general_fields> 建议加上国家代码。
<img width="842" alt="Screenshot 2024-04-08 at 20 37 03" src="https://github.com/l0o0/translators_CN/assets/12290822/c263d3d7-16a0-4c81-aecc-5dd783d8fffa">

**Comment by doubanchan** [comment]
@jiaojiaodubai 上面落了一项，需要同chi/eng一样，添加jpn作为ja/ja-JP的标识（jpn是日语的ISO 692或693三位代码，俄语的三位代码是rus）  https://github.com/l0o0/translators_CN/blob/e01168b1dfaf9a421f3a40abc6fccccda3961c71/zhangqiaokeyan.js#L233

**Comment by jiaojiaodubai** [comment]
done---原始邮件---发件人: ***@***.***>发送时间: 2024年4月12日(周五) 下午4:40收件人: ***@***.***>;抄送: ***@***.***>***@***.***>;主题: Re: [l0o0/translators_CN] 掌桥科研语种 (Issue #334)
@jiaojiaodubai 上面落了一项，需要同chi/eng一样，添加jpn作为ja/ja-JP的标识（jpn是日语的ISO 692或693三位代码，俄语的三位代码是rus）  https://github.com/l0o0/translators_CN/blob/e01168b1dfaf9a421f3a40abc6fccccda3961c71/zhangqiaokeyan.js#L233

**Comment by doubanchan** [comment]
@jiaojiaodubai  rus: 'ru-RU'
https://github.com/l0o0/translators_CN/blob/3d8134182f11ceca983f3b1533e4b5f8331ea4ef/zhangqiaokeyan.js#L237
