### ISSUE TITLE
抓取知网的期刊时，会自动消除期号前面的0

### ISSUE THREAD

**Issue by lxcbetter** [l0o0/translators_CN#338]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
[论文网址](https://kns.cnki.net/kcms2/article/abstract?v=MuKJieOJLT1cnWIJ2uUvsYnV7OatW2ARRvGejfoS9gvZ8NEElCsizTHyz_63oezSkG1a77XsP7UYWpOLA0JQjK3dQQok8SD2txZvb18S0eBT6M47AIDTZiS_mn8m1vxOt3i7I9o14I4=&uniplatform=NZKPT&flag=copy)

**问题描述** [必填]
在抓取知网的期刊时，会自动把期号前面的0消除，比如原本是02，导入后就变成了2。

![zotero中的信息](https://github.com/l0o0/translators_CN/assets/77924059/df4fb81c-1714-4327-a269-76460d878ce5)

![导入word后的效果](https://github.com/l0o0/translators_CN/assets/77924059/609fff17-d5d8-4cf9-9297-f78af9ed78ed)

**你的预期结果**

应完整抓取期号

![实际的参考文献效果](https://github.com/l0o0/translators_CN/assets/77924059/cba1b0d6-8f42-4029-b308-7274ab0eb7b0)
实际的参考文献效果，期号应是02。

**浏览器**

- [x] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by zepinglee** [comment]
1. GB/T 7714 的示例中期号前不加 0；
2. 国标起草人在一篇文章中也建议不加 0；
3. 我了解的国内外样式没有期号要加 0 的。

**Comment by lxcbetter** [comment]
了解了，那我按照国际惯例来吧

**Comment by zepinglee** [comment]
<http://bjxb.cessp.org.cn/ch/reader/view_abstract.aspx?file_no=20230626&flag=1>

<img width="697" alt="Screenshot 2024-05-08 at 22 52 27" src="https://github.com/l0o0/translators_CN/assets/12290822/fb1e109d-5818-405b-a170-1d48ece0a3cf">

作者是 GB/T 7714—2015 起草人之一。
