### ISSUE TITLE
知网学位论文信息获取BUG

### ISSUE THREAD

**Issue by yangtzech** [l0o0/translators_CN#34]
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD202101&filename=1020116029.nh
上面链接可以获取到论文的目录
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&filename=1020116029.nh
上面链接不行

**Comment by l0o0** [comment]
第二个链接的目录确实有问题，我怀疑可能和这个URL有关，具体我要去看一下是哪里有问题

**Comment by yangtzech** [comment]
> 第二个链接的目录确实有问题，我怀疑可能和这个URL有关，具体我要去看一下是哪里有问题

第一个链接是在知网里面搜索得到的，第二个是先借助百度搜索到，百度学术的知网链接是知网空间，所以我在这个地方使用了https://github.com/dlutor/BaiduXueShu-CNKI-change，然后我看代码里面好像在转换链接时，只加了dbcode，没加dbname。
谢谢了

**Comment by l0o0** [comment]
对的，现在按照知网那边的格式，应该不会出现第二种情况，所以当时没有考虑到这种特殊情况，我看看后面处理一下。

**Comment by yangtzech** [comment]
> 对的，现在按照知网那边的格式，应该不会出现第二种情况，所以当时没有考虑到这种特殊情况，我看看后面处理一下。

多谢

**Comment by yangtzech** [comment]
> 同学你好，你可以看一下你现在知网翻译器CNKI.js 文件中lastUpdated 的时间么，如果不是最新的，可更新一下试试。我看第二个链接是可以抓取的。
还是不行啊我😢
![image](https://user-images.githubusercontent.com/41911522/113312192-9d38d380-933c-11eb-9e87-68508eaf5ee6.png)

**Comment by l0o0** [comment]
不着急，我猜测会不会是没有更新翻译器信息成功导致的。你可以右键 Zotero Connector -> 选项，打开这里的日志信息，看看这个是不是有20210317的时间。信息比较多的时候，你可以先清空，然后再刷新网页，重新抓取，这样信息更容易查找
![图片](https://user-images.githubusercontent.com/2743744/113369146-28dd4f00-9393-11eb-9a53-143293cad288.png)

**Comment by yangtzech** [comment]
> 不着急，我猜测会不会是没有更新翻译器信息成功导致的。你可以右键 Zotero Connector -> 选项，打开这里的日志信息，看看这个是不是有20210317的时间。信息比较多的时候，你可以先清空，然后再刷新网页，重新抓取，这样信息更容易查找
> ![图片](https://user-images.githubusercontent.com/2743744/113369146-28dd4f00-9393-11eb-9a53-143293cad288.png)
 20210317
![image](https://user-images.githubusercontent.com/41911522/113369659-65f61100-9394-11eb-9f9b-4a1359851b20.png)

**Comment by l0o0** [comment]
那你试试在测试环境，能正常不？
工具 -> 开发者 -> Translator Editor
![图片](https://user-images.githubusercontent.com/2743744/113377345-a199d680-93a6-11eb-9773-5ac307379109.png)

**Comment by l0o0** [comment]
忘了说明了，要先提前设置好translator 目录 
![图片](https://user-images.githubusercontent.com/2743744/113384414-8e900200-93b8-11eb-94d1-1e8b84b5a2a6.png)

**Comment by yangtzech** [comment]
16:42:08 {
             "dbname": "CMFDTOTAL"
             "filename": "1020116029.nh"
             "dbcode": "CMFD"
             "url": "https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&filename=1020116029.nh"
         }
16:42:08 detectWeb returned type "thesis"

16:42:39 ----------------CNKI 20210317---------------------
16:42:39 {
             "dbname": "CMFDTOTAL"
             "filename": "1020116029.nh"
             "dbcode": "CMFD"
             "url": "https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&filename=1020116029.nh"
         }
16:42:39 
         RT Dissertation
         SR 1
         A1 周效良
         A1 刘应东
         A1 周怀钰
         PB 兰州交通大学
         T1 基于可变元胞传输模型的城市网络交通流模拟
         CL 硕士
         YR 2020
         K1 城市交通网络;交通流仿真;元胞传输模型;路径选择;Urban Transportation Network;Traffic flow simulation;Cell transmission model;Routing behavior
         AB 伴随着我国城镇化、机动化进程的不断加快,全国私家车的拥有量快速增长,“出行难”已成为民众普遍关心的热点、难点问题。交通流作为城市交通系统的主要参与对象,如何真实的刻画城市路网交通流的内在运行规律对于交通拥堵管理以及交通系统优化具有重要现实意义。本文利用可变细胞传输模型(VCTM)作为工具。以Siouxfalls网络的变种为路网仿真环境,建立城市网络交通流仿真模型,采用Java语言进行仿真迭代,分别探讨了需求、路网关键节点、路段以及出行者路径选择行为下的路网交通流运行特征。主要包括以下工作:(1)首先从整体的角度分析了当需求水平固定时路网交通流的时空分布特性,接着分析了当需求变化时路网交通流的整...
         LA 中文;
         DS CNKI
         
16:42:39 Returned item:
           {
             "itemType": "thesis"
             "creators": [
               {
                 "lastName": "周"
                 "firstName": "效良"
                 "creatorType": "author"
               }
               {
                 "lastName": "刘"
                 "firstName": "应东"
                 "creatorType": "contributor"
               }
               {
                 "lastName": "周"
                 "firstName": "怀钰"
                 "creatorType": "contributor"
               }
             ]
             "notes": []
             "tags": [
               {
         -       "tag": "城市交通网络"
         +       "tag": "Cell transmission model"
               }
               {
         -       "tag": "交通流仿真"
         +       "tag": "Routing behavior"
               }
               {
         -       "tag": "元胞传输模型"
         +       "tag": "Traffic flow simulation"
               }
               {
         -       "tag": "路径选择"
         +       "tag": "Urban Transportation Network"
               }
               {
         -       "tag": "Urban Transportation Network"
         +       "tag": "交通流仿真"
               }
               {
         -       "tag": "Traffic flow simulation"
         +       "tag": "元胞传输模型"
               }
               {
         -       "tag": "Cell transmission model"
         +       "tag": "城市交通网络"
               }
               {
         -       "tag": "Routing behavior"
         +       "tag": "路径选择"
               }
             ]
             "seeAlso": []
             "attachments": [
               {
                 "title": "Full Text PDF"
                 "mimeType": "application/pdf"
               }
             ]
             "university": "兰州交通大学"
             "title": "基于可变元胞传输模型的城市网络交通流模拟"
             "thesisType": "硕士"
             "abstractNote": "伴随着我国城镇化、机动化进程的不断加快,全国私家车的拥有量快速增长,“出行难”已成为民众普遍关心的热点、难点问题。交通流作为城市交通系统的主要参与对象,如何真实的刻画城市路网交通流的内在运行规律对于交通拥堵管理以及交通系统优化具有重要现实意义。本文利用可变细胞传输模型（VCTM）作为工具。以Siouxfalls网络的变种为路网仿真环境,建立城市网络交通流仿真模型,采用Java语言进行仿真迭代,分别探讨了需求、路网关键节点、路段以及出行者路径选择行为下的路网交通流运行特征。主要包括以下工作:（1）首先从整体的角度分析了当需求水平固定时路网交通流的时空分布特性,接着分析了当需求变化时路网交通流的整体、局部时空分布特性。（2）探讨了路段的位置、所承载的车流来源、车流去向对路段平均行程速度的影响。发现这种影响作用取决于节点、路段的局部结构特征。（3）提出了基于节点紧密度中心性与基于边权重PageRank算法的网络关键节点挖掘模型;提出了基于边介数中心性的路网关键路段识别模型。并对测试网络中的关键节点、路段进行识别。仿真测试表明,该模型具有较高的合理性。（4）探讨了基于路段拥堵程度的动态路径选择下网络交通流的时空分布特征,并对需求固定和需求变化下路网交通流进行迭代仿真。（5）从用户最优和系统最优两个角度探讨了基于路段拥堵程度的择路机制和基于路段吸引程度的动态路径选择机制与路网交通流之间的相互关系。（6）分析了单个交叉口信号配时对交通流的影响,建立了单个交叉口双目标动态信号配时优化模型,提出了基于三维空间双邻居元胞遗传算法,并利用改进的元胞遗传算法进行求解。"
             "language": "中文;"
             "date": "2020"
         -   "DOI": "10.27205/d.cnki.gltec.2020.001176"
             "url": "https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&filename=1020116029.nh"
             "libraryCatalog": "CNKI"
         -   "accessDate": "2021-04-02T08:42:39Z"
           }
16:42:39 Translation successful

**Comment by l0o0** [comment]
你上面的信息，说明工作正常啊

**Comment by yangtzech** [comment]
> 你上面的信息，说明工作正常啊

但是每次保存题录的时候，就是不能弹出那个命令行的框然后生成pdf目录。

**Comment by l0o0** [comment]
那你这边是meta 信息是保存好了，就是保存的PDF不能生成书签。你可以测试下，手动添加书签那个选项可以成功么？

**Comment by yangtzech** [comment]
> 那你这边是meta 信息是保存好了，就是保存的PDF不能生成书签。你可以测试下，手动添加书签那个选项可以成功么？

不可以，没有反应

**Comment by l0o0** [comment]
在 帮助 -> 输出错误日志 -> 查看输出文件，会跑出一个日志窗口。你先点击上面的clear清除已有的信息，等没有新的日志输出后，你再点击添加书签，日志窗口会有新的信息出现，这时点击右上的文件 -> 保存，把保存的日志发贴上来我看看

**Comment by yangtzech** [comment]
[Debug Output.txt](https://github.com/l0o0/translators_CN/files/6254790/Debug.Output.txt)

**Comment by l0o0** [comment]
获取书签信息的URL出错了，应该还是因为这个论文的URL和平常的不一样造成的，我可以更新一下代码试试

**Comment by l0o0** [comment]
把后缀名改为xpi，然后安装这个插件再试试
[jasminum.zip](https://github.com/l0o0/translators_CN/files/6254826/jasminum.zip)

**Comment by yangtzech** [comment]
> 把后缀名改为xpi，然后安装这个插件再试试
> [jasminum.zip](https://github.com/l0o0/translators_CN/files/6254826/jasminum.zip)

emm，我回宿舍了，明天早上试一下，谢谢大佬

**Comment by yangtzech** [comment]
可以了，谢谢大佬
