### ISSUE TITLE
豆瓣书语言属性识别错误

### ISSUE THREAD

**Issue by aGolduck** [l0o0/translators_CN#343]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [x] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://book.douban.com/subject/1962875/
https://book.douban.com/subject/1025156/

**问题描述** [必填]
语言字段为: en

**你的预期结果**
应为： zh

**浏览器**

- [x] Chrome（谷歌浏览器）
- [x] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [x] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
未能在所提供的链接中复现问题，可能是其他插件引起的问题，你可以尝试禁用所有插件后再重试一下

**Comment by aGolduck** [comment]
查明是 linter 的问题，感谢

**Comment by jiaojiaodubai** [comment]
@northword
