### ISSUE TITLE
gov.cn Policy.js 成文日期与发布日期

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#345]
**背景** [必填]
政府公文（法律性质的文件），通常会有“成文日期”和“发布日期”，引用的时候该用哪一个，不知道有没有相关的规定，是否也应该两个日期都列出来？比如[1](https://www.gov.cn/zhengce/zhengceku/2019-06/28/content_5404170.htm)

---
《[法学引注手册](https://cbimg.cnki.net/Editor/2019/1107/zgfx/090fce08-e3c7-4231-b406-8a84d177b024.pdf)》（2019年）中引用《国务院关于在全国建立农村最低生活保障制度的通知》时，使用的日期是[国务院公报](https://www.gov.cn/gongbao/content/2007/content_719880.htm)中的“二○○七年七月十一日”。另外在国务院网站上的[国务院公开文件页](https://www.gov.cn/zhengce/content/2008-03/28/content_6245.htm)上，标有“发布日期：2008年03月28日，成文日期：2007年07月11日“，如果按照gov.cn Policy.js现在的程序写法就会选择”2008年03月28日“，出现冲突。

“北大法宝”网站中，《[国际邮轮在中华人民共和国港口靠港补给的规定](https://www.pkulaw.com/chl/d6c46dcbe7166ff0bdfb.html?way=listView)》（法宝引证码：CLI.2.5192275），其“公布日期”等于[国务院网站对应文件](https://www.gov.cn/zhengce/content/202404/content_6947737.htm)的“成文日期”。

@zepinglee

**Comment by zepinglee** [comment]
感觉 gov.cn 应该将“成文日期”改为颁布日期。

**Comment by yfdyh000** [comment]
感觉成文和网站的发布日期都不准确，成文未印发不生效，网站发布日期是信息公开，可能晚。应该引用实际的印发（颁布，或首次正式公开）日期。

**Comment by jiaojiaodubai** [comment]
> 感觉 gov.cn 应该将“成文日期”改为颁布日期。

OK，网站上有的话我会完善的。

**Comment by doubanchan** [comment]
看了下《[教育部政府信息公开指南（试行）](http://www.moe.gov.cn/jyb_xxgk/xxgk/zhinan/)》，其中“生成日期”或“发布日期”可能是该文书在互联网上的公开日期，感觉Zotero上的"颁布日期"（Date Enacted）应该填写“成文日期”，不应该填写“生成日期”或“发布日期”。@zepinglee 

> 将“成文日期”改为颁布日期。

具体是指什么？

**Comment by zepinglee** [comment]
我的意思是[国务院公开文件页](https://www.gov.cn/zhengce/content/2008-03/28/content_6245.htm)的用词不够准确。
