### ISSUE TITLE
新版本的connector插件有调整(MV3), 好像不兼容之前的脚本(跪求一个旧版插件的安装包)

### ISSUE THREAD

**Issue by YaoLiMuMu** [l0o0/translators_CN#349]
**主要有以下两个问题** 
为线上图书馆写了一个脚本, 自动拉取标准信息和下载文件, 之前一直能用, 直到近期更新了connector插件和chrome浏览器, 
我回退了Chrome浏览版本, 才定位是插件问题, 主要发下问题有两个:
1. js脚本里面的document的对象无法直接使用, 比如"document.title", "document.querySelector"
2. js脚本下面无法使用XMLHttpRequest, 报告错误如下:
```
[JavaScript Error: "Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translateSandbox/searchStandard.do?action=searchPDFLanguage'.
``` 
**跪求一个旧版插件的安装包** 
浏览器: chrome, 平台: linux

**Comment by jiaojiaodubai** [comment]
- Connector 安装见 [Zotero-Chinese 的教程](https://zotero-chinese.com/user-guide/install#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%8F%92%E4%BB%B6-zotero-connector)
- Connector 的历史构建可见 [Connector仓库](https://github.com/zotero/zotero-connectors)
- translator 运行在沙箱中，直接操作 document 对象是不好的，但你可以使用 `doWeb()` 传入的 `doc` 或者使用 DOMPaser 构建一个类似的东西；
- translator中有自己的请求方案来代替原生的 `XMLHttpRequest`，详见[此处](https://github.com/zotero/translators/blob/master/index.d.ts)

**Comment by YaoLiMuMu** [comment]
Thank you for your help
