### ISSUE TITLE
The regexp in target contains the error

### ISSUE THREAD

**Issue by northword** [l0o0/translators_CN#351]
**背景** [必填]

以 bilibili.js 为例，目前其 target 为 `https?://(search|www).bilibili.com`， `new RegExp` 后为 `/https?:\/\/(search|www).bilibili.com/`，而期望中应该是 `/https?:\/\/(search|www)\.bilibili\.com/`

否则网址会匹配错误：

![image](https://github.com/l0o0/translators_CN/assets/44738481/1254ae7d-5f5f-4f28-9c1e-8df687841d33)

此外，第一个捕获组应该是 0-1 次，因此 target 应为 `https?://(search|www)?\.bilibili\.com`

此仓库有不少转换器都存在这个问题。

**你的想法** [必填]

参照官方格式修改，例如：https://github.com/zotero/translators/blob/master/ABC%20News%20Australia.js#L5

**Comment by jiaojiaodubai** [comment]
是的，这个点号是历史遗留问题，我会统一处理它们。
