### ISSUE TITLE
不使用 `----- XXXX YYYY-MM-DD HH:MM:SS ----`  的调试日志或及时更新其日期

### ISSUE THREAD

**Issue by northword** [l0o0/translators_CN#352]
**背景** [必填]

当前仓库大量转换器使用方便查找的 debug 日志，例如：

https://github.com/l0o0/translators_CN/blob/651a7b3a37cfe5a6d7347c84b218228c5becae5b/CNKI.js#L235

然而，一方面，官方并不提倡使用这种调试日志：https://github.com/zotero/translators/pull/2690#discussion_r714236159

另一方面，其时间经常与 translator info 中的 updated 不一致，造成困惑（日志中出现的旧时间导致以为运行的是官方库/缓存/旧的转换器）

**你的想法** [必填]

停止使用这种调试日志，或尽量确保更新转换器时也更新这里的日志（甚至写个脚本去检查）

**Comment by jiaojiaodubai** [comment]
此前，Connector “update translators”按钮并不强制更新缓存，而且日志中只记录当前使用什么转换器，而不包含其更新时间，为了在开发时（以及为用户排查问题时）确定用户下载的 translator 已经被 Connector 读取到缓存中，我们使用了这样的日志。

现在，“update translators” 按钮已经被移除，取而代之的“rest translators”将强制更新 Connector 中的缓存；此外 Connector 的输出日志中已经包含 lastUpdated。

确实是时候该移除这些日志了。
