### ISSUE TITLE
People's Daily Database/人民日报图文数据库 图书馆VPN访问

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#354]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目
- [x] 文章作者提取

**问题描述** [必填]
1、通过图书馆VPN系统访问人民日报图文数据库，网址前面的 http://data.people.com.cn 替换成了图书馆的代理网址，网页其他格式未变。
2、
（2.1）[2024-06-20第17版第1篇](http://data.people.com.cn/rmrb/20240620/pingLun/615e9cb1362d43b588d45411d80c573c)中含有作者，不过格式不是“【作者：本报评论员】”（此样式是原testcast中[2023-12-31第1版第5篇](http://data.people.com.cn/rmrb/20231231/1/32924b7882d94d80ad59562d52280fbb)），只有作者名称。
（2.2）[2024-06-20第1版第2篇](http://data.people.com.cn/rmrb/20240620/1/24c0fd81008447179e4e53127ac959d2)，作者是“李林蔚”，将末尾的“蔚”截掉了，是因为`slice(4, -1)`？
**你的预期结果**
正常识别。

**Comment by doubanchan** [comment]
页面识别个人临时解决办法：将targte对应为 `^https?://.*(data\\.people\\.com\\.cn)?/rmrb`

**Comment by jiaojiaodubai** [comment]
不建议更改`target`，正如 #347 提到的，应该使用 [Connector 的 Proxy](https://www.zotero.org/support/connector_preferences#proxies)来兼容 VPN，否则我们不可能用正则表达式涵盖所有机构的 VPN。

**Comment by doubanchan** [comment]
@jiaojiaodubai  深圳图书馆的VPN代理网址，每次登录都会更新后缀，似乎没办法添加到Proxy 中，如果代理地址是固定的，应该没可以。
