### ISSUE TITLE
CHINESE JOURNAL OF LAW/法学研究期刊

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#356]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目
- [x] 未去掉页码前的冒号（:）

**发生问题的链接** [必填]
[期刊主页](https://faxueyanjiu.ajcass.com/Home/Index)
[期刊论文](https://faxueyanjiu.ajcass.com/Magazine/Show?ID=94257)

**问题描述** [必填]
该期刊网址从[www.faxueyanjiu.com](http://www.faxueyanjiu.com)更换到[faxueyanjiu.ajcass.com](https://faxueyanjiu.ajcass.com)

**Comment by doubanchan** [comment]
不适配论文的话，target改为`^https?://(www\\.)?faxueyanjiu\\.(ajcass\\.)?com`应该即可。

**Comment by jiaojiaodubai** [comment]
旧网站将被弃用，而且新网站已经可用，所以不打算兼容旧网站
