### ISSUE TITLE
samsoncn.com/西安三才

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#358]
**你想申请哪个网站的翻译器？** [必填]
[西安三才](https://www.samsoncn.com)（名称未定）

**网站描述** [必填]
名称暂时未定，该期刊编辑系统的公司官网是samsoncn.com，但是不少期刊后缀使用的是paperonce.org，比如[自然灾害学报](https://zrzh.paperonce.org/#/digest?ArticleID=3268)，也有使用自己的域名比如[复旦学报（自然科学版）](https://www.jns.fudan.edu.cn/#/digest?ArticleID=1890)
（注1：在Chinaz.com查询过是正规公司，见[备案](https://icp.chinaz.com/paperonce.org)
    注2：西安三才的母公司是西安知先信息技术有限公司的，该公司的主要产品是NoteFirst也是一个较常见的文献管理软件；CNKI的导出格式中有NoteFirst。不知道是否可以直接解析网页到处的NoteFirst、EndNote等格式。
注3：三才出现在中文DOI的[合作伙伴列表](http://www.chinadoi.cn/portal/newsAction!partner.action?type=6)
注4：网页上未像玛格泰克/北大方正等一样提供可供MetaData使用的元数据
）

**条目类型**
- [x] 期刊

**Comment by jiaojiaodubai** [comment]
有待补充更多不同期刊的测试链接

**Comment by doubanchan** [comment]
[四川农业科技](http://www.scnykj.cn/#/)
[东南大学学报（自然科学版）](http://journal.seu.edu.cn/#/digest?ArticleID=7583)
[深圳大学学报理工版](https://journal.szu.edu.cn/#/digest?ArticleID=2613)
[弹道学报](http://ddxb.paperopen.com/#/digest?ArticleID=1288)
[陆军军医大学学报](https://aammt.tmmu.edu.cn/#/digest?ArticleID=21137)
[复旦学报（自然科学版）](https://www.jns.fudan.edu.cn/#/digest?ArticleID=1890)
[电机与控制学报](http://emc.hrbust.edu.cn/#/digest?ArticleID=6104)
[西安交通大学学报](https://zkxb.xjtu.edu.cn//#/digest?ArticleID=5033)
[应用力学学报](https://cjam.xjtu.edu.cn/#/digest?ArticleID=2674)（西安交通大学）
[邮电设计技术](http://ydsjjs.paperopen.com//#/digest?ArticleID=3472)
[中南林业科技大学学报](https://zkxb.csuft.edu.cn/#/digest?ArticleID=6910)
[东北林业大学学报](https://dlxb.nefu.edu.cn/#/digest?ArticleID=3916)
[纳米技术与精密工程（英文）](https://tjunpe.tju.edu.cn/#/)
[南开经济研究](https://nkes.nankai.edu.cn/#/digest?ArticleID=996)
[南京理工大学学报（社会科学版）](https://xbskb.njust.edu.cn/#/digest?ArticleID=3178)
