### ISSUE TITLE
Zhihu/知乎

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#360]
**目标链接** [必填]
[知乎](https://www2.zhihu.com/question/34867032)

**你想添加的功能** [必填]
- [x] 知乎target

** 其他
知乎target增加www2：	`"target": "^https?://(zhuanlan|www2?)\\.zhihu\\.com/",`

**Comment by jiaojiaodubai** [comment]
抱歉，上一次提交仅关注将网络请求最小化而未注意到 `requestDocument` 所获取的文档和页面上打开的文档有所不同。

**Comment by jiaojiaodubai** [comment]
@zepinglee 帖子和专栏文章在页面上默认显示的是最后一次编辑的时间，这个时间作为 `date` 合适吗？原先的转换器使用首次创建的时间，为了获取这个消息，不得不进行额外的网络请求，我认为最后一次编辑的时间或许更能区分网络资源的具体版本。

**Comment by jiaojiaodubai** [comment]
@zepinglee 帖子和专栏文章在页面上默认显示的是最后一次编辑的时间，这个时间作为 `date` 合适吗？原先的转换器使用首次创建的时间，为了获取这个消息，不得不进行额外的网络请求，我认为最后一次编辑的时间或许更能区分网络资源的具体版本。

**Comment by zepinglee** [comment]
> @zepinglee 帖子和专栏文章在页面上默认显示的是最后一次编辑的时间，这个时间作为 `date` 合适吗？原先的转换器使用首次创建的时间，为了获取这个消息，不得不进行额外的网络请求，我认为最后一次编辑的时间或许更能区分网络资源的具体版本。

问题不大。
