### ISSUE TITLE
Jd/京东

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#361]
**你想添加的功能** [必填]

- [x] 去除网址后的跟踪参数
- [x] 排除非书籍页面
- [x] 出版社未正确识别

**Comment by doubanchan** [comment]
（1）修改url代码	
`newItem.url = url;` 替换为 `newItem.url = attr(document, 'link[rel="canonical"]', 'href').replace(/^\/\//, 'https://');`

**Comment by jiaojiaodubai** [comment]
“非书籍页面”和“出版社未识别正确”可否提供案例？

**Comment by doubanchan** [comment]
> “非书籍页面”和“出版社未识别正确”可否提供案例？

（3）出版社未正确识别：
[例子](https://item.jd.com/13907311.html)，“品牌”覆盖了“出版社”
（2）非书籍页面
[例子](https://item.jd.com/10100007191846.html)，应该不需要匹配非书籍（虽然京东也有少量的CD）页面

**Comment by jiaojiaodubai** [comment]
其他问题已经解决，但是 creators 列表遇到一点问题。《计算机组成与设计：硬件/软件接口 MIPS版（第6版）》有多个作者、有译者、有版本，是很好的测试用例。

1. 如果使用 `#p-author > a` 获取，则在[页面1](https://item.jd.com/13272279.html)中获取不到完整的作者列表
2. 如果使用 `script[charset="gbk"]` 并用正则匹配其中的信息（注意，根据 Translator 的 lint 规则，不能使用 `eval()` 将它反序列化），则会丢失 creatorType

我暂时没有找到其他包含作者信息的请求，所以我们需要在这之中作出选择。（其实看到数据这么烂已经不太想维护京东了）
