### ISSUE TITLE
申请增加社会科学文献出版社旗下多个数据库的翻译器

### ISSUE THREAD

**Issue by EEEEgoose** [l0o0/translators_CN#362]
**你想申请哪个网站的翻译器？** [必填]
[一带一路数据库](https://www.ydylcn.com/)
[皮书数据库](https://www.pishu.com.cn/)
[国别区域与全球治理数据平台](https://www.crggcn.com/)
[集刊全文数据库](https://www.jikan.com.cn/)

**网站描述** [必填]
社会科学文献出版社成立于1985年，是直属于中国社会科学院的人文社会科学专业学术出版机构。成立以来，特别是1998年实施第二次创业以来，依托于中国社会科学院丰厚的学术出版和专家学者两大资源，坚持“创社科经典，出传世文献”的出版理念和“权威、前沿、原创”的产品定位，走学术产品的系列化、规模化、市场化经营道路，先后策划出版了著名的图书品牌和学术品牌皮书系列、《列国志》系列、“社科文献精品译库”“全球化译丛”“经济研究文库”“社会理论译丛”“CCIEE智库报告”等一大批既有学术影响又有市场价值的系列图书，使社会科学文献出版社的知名度和美誉度日益提高，确立了人文社会科学学术出版的权威地位。

2015年6月，为配合国家 “一带一路”倡议实施，社会科学文献出版社依托中国社会科学院丰厚的学术研究实力和研究成果，立足人文社科领域知名学术品牌“皮书”系列、国别国际问题研究系列“列国志”丛书、中国社会科学院“一带一路”研究系列、“阿拉伯国家文化研究”丛书等优质资源，全面整合国内外智库“一带一路”研究资源，策划构建“一带一路”数据库。

**条目类型**
- [x] 期刊
- [x] 图书
- [x] 报告
- [x] 皮书

**网站权限**
- [x] 需要注册帐号（仅下载需要）
- [x] 需要购买服务或使用机构帐号登录（仅下载需要）

**Comment by jiaojiaodubai** [comment]
皮书数据库的转换器已经有了，其他几个数据库我有在“友情链接”里面看到过，那几个确有必要制作转换器吗？
