### ISSUE TITLE
建议增加中国社会科学的翻译器

### ISSUE THREAD

**Issue by yzy1228682367** [l0o0/translators_CN#363]
**你想申请哪个网站的翻译器？** [必填]
[在此填写链接](http://sscp.cssn.cn/zgshkx/zgshkx202401/)

**网站描述** [必填]
中国社会科学，中国社科综合类顶刊，但是知网更新长期落后，在2024年第5期已经刊发的情形下，仍然还2023年

**条目类型**
- [x] 期刊
- [] 图书
- [] 专利
- [ ] ...

**网站权限**
- [] 需要注册帐号
- [ ] 需要购买服务或使用机构帐号登录

**Comment by doubanchan** [comment]
[维普](https://qikan.cqvip.com/Qikan/Journal/Summary?kind=1&gch=81908X&from=Qikan_Journal_Detail)上仅晚了一期，万方和知网一样到2023年，不知道是否和期刊编辑有关。。

**Comment by yzy1228682367** [comment]
> [维普](https://qikan.cqvip.com/Qikan/Journal/Summary?kind=1&gch=81908X&from=Qikan_Journal_Detail)上仅晚了一期，万方和知网一样到2023年，不知道是否和期刊编辑有关。。

好像是因为中国社会科学和知网闹掰了

**Comment by zepinglee** [comment]
> 好像是因为中国社会科学和知网闹掰了

大快所有人心的大好事

**Comment by jiaojiaodubai** [comment]
未给出页码，引用时可能必须以在线期刊来引用，如[此处](http://sscp.cssn.cn/zgshkx/zgshkx202405/202406/t20240611_5757971.html)

**Comment by yzy1228682367** [comment]
> 缺卷号、缺页码、未提供PDF，确有必要制作转换器吗？@yzy1228682367

多谢大佬！麻烦大佬了😭今天发现可以通过哲学社会科学文献中心获取最新的期刊，这个网址应该就不用了https://www.ncpssd.org/journal/details?gch=81908X&years=2024&num=5&nav=1&langType=1
