### ISSUE TITLE
E-Tiller

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#365]
**你遇到了什么问题？** [必填]
- [x] 无法识别条目
- [x] 识别成multiple

**发生问题的链接** [必填]
[含能材料](https://www.energetic-materials.org.cn/hncl/article/abstract/CJEM2024111) 识别成multiple
[气候与环境研究](http://www.dqkxqk.ac.cn/qhhj/qhhj/article/abstract/20200602?st=article_issue)识别成multiple
[生物化学与生物物理进展](https://www.pibb.ac.cn/pibbcn/article/abstract/20240109)未识别，默认Embedded Metadata
[微生物学通报](https://wswxtb.ijournals.cn/wswxtbcn/article/abstract/tb24061814) 未识别，默认Embedded Metadata
[重庆大学学报（社会科学版）](http://qks.cqu.edu.cn/cqdxskcn/article/abstract/20240315)，默认Embedded Metadata
[电子测量与仪器学报](http://jemi.cnjournals.com/jemi/article/abstract/B2306653?st=article_issue)
[水土保持通报](http://stbctb.alljournal.com.cn/stbctb/article/abstract/19860212?st=alljournals)未识别，默认Embedded Metadata
[哈尔滨工业大学学报](http://hit.alljournals.cn/hitxb_cn/ch/reader/view_abstract.aspx?file_no=20240718&flag=1)，识别DOI
[分子催化](https://www.jmcchina.org/ch/reader/view_abstract.aspx?file_no=20240307&flag=1)，识别成DOI，无结构化Metadata，或许可以放弃
[中国工业医学杂志](http://zggyyx.cnjournals.com/ch/reader/view_abstract.aspx?file_no=202403003&flag=1)未识别，可能是网页结构问题，无结构化Metadata（底部有“勤云科技”字样）

**问题描述** [必填]
以上多数的网页底部无“勤云科技”字样，但是不少网址或者部分网页元素中含有alljournal.com.cn、cnjournals.com、ijournals.cn、、cnjournals.net、、cnjournals.org、alljournals.cn（网页元素）等勤云所属域名。另外论文网址多数包含`reader/view_abstract`或`article/abstract`（article/abstract针对摘要）。

**Comment by doubanchan** [comment]
DIY的一些修改，可以修复含indomain域名且识别成Embedded Metadata的和[含能材料](https://www.energetic-materials.org.cn/hncl/article/abstract/CJEM2024111)的multiple，[生物化学与生物物理进展](https://www.pibb.ac.cn/pibbcn/article/abstract/20240109)未修复，[分子催化](https://www.jmcchina.org/ch/reader/view_abstract.aspx?file_no=20240307&flag=1)网页head部分无Metadata暂时放弃，哈尔滨工业大学学报似乎网页上存在一些设计问题，Google Chrome控制台一直输出错误。
https://github.com/l0o0/translators_CN/blob/2b4c399909d0a1398a1603582a8666c17fb9d2a7/E-Tiller.js#L38-L42
```
//E-Tiller期刊会用到的网址
const indomain = [
	'ijournals.cn',
	'alljournals.cn',
	'alljournal.com.cn',
	'alljournal.net',
	'cnjournals.com',
	'cnjournals.net',
	'cnjournals.org',
	'alljournalsystem.com',
	'journalsystem.net'
];
```
https://github.com/l0o0/translators_CN/blob/2b4c399909d0a1398a1603582a8666c17fb9d2a7/E-Tiller.js#L46-L57
```
	let inurl = indomain.some((element) => url.includes(element)) ;
	Z.debug(`insite: ${insite}`);
	if (!insite && !inurl) return false;
	if(paths.some((element) => url.includes(element)) && doc.querySelector('meta[name="citation_title"]')){
		return 'journalArticle';
	}
	else if (doc.querySelector('meta[name]') && getSearchResults(doc, true)) {
		return 'multiple';
	}
```

**Comment by doubanchan** [comment]
针对[生物化学与生物物理进展](https://www.pibb.ac.cn/pibbcn/article/abstract/20240109)的文章，暂时修复方法：
![Etiller-author-alljournal](https://github.com/user-attachments/assets/7d0f6637-0f42-4db8-8fdd-c88102375f36)

```
	let like = doc.querySelector('div[class*="fudong_ycc"]');	
	let inurl = indomain.some((element) => url.includes(element)) ;
	Z.debug(`insite: ${insite}`);
	if (!insite && !inurl && !like) return false;
```

**Comment by jiaojiaodubai** [comment]
可归类的我们可以写到勤云里面去，不可归类的特殊网址宜写专门的 Translator（优先级更高）

**Comment by jiaojiaodubai** [comment]
> 加入'article/html'，可以让其识别完整HTML页面，而不仅仅是摘要界面，比如[中国内镜杂志](http://www.zgnjzz.com/zgnjzz/article/html/202311001)

看了一下，页面布局有明显差异，不适合写到这个通用转换器里面

**Comment by jiaojiaodubai** [comment]
### tabel + sapn
- http://zhyxkygl.ijournals.com.cn/ch/index.aspx
- http://zkxb.hnust.edu.cn/ch/index.aspx
- https://znzk.scuec.edu.cn/ch/index.aspx
- https://xbsk.cqust.edu.cn/ch/index.aspx
- http://gdjyyjxb.nudt.edu.cn/ch/index.aspx
- http://bjxb.cessp.org.cn/ch/index.aspx
- http://kjglyj.ijournals.cn/ch/index.aspx
- http://www.rubbertire.com.cn/zh/jzy/ch/index.aspx
- https://xbzrb.fzu.edu.cn/index.jsp
- http://wkdxb.wust.edu.cn/wkd_sk/ch/index.aspx
- http://biomed.cnjournals.com/ch/index.aspx
- http://www.sjzyyzz.com/sjzyy/ch/index.aspx
- http://hjjcgl.cnjournals.net/ch/index.aspx
- http://zgys.cnjournals.org/ch/index.aspx
- http://jhe.ches.org.cn/jhe/ch/index.aspx
- http://jcta.cnjournals.com/cta_cn/ch/index.aspx
- http://www.cspine.org.cn/zgjzjszz/ch/index.aspx
- http://www.chinacjo.com/ch/author/login.aspx
- http://mode301.ijournals.cn/zhlndqgjbzz/ch/index.aspx
- https://jss.usst.edu.cn/ch/index.aspx
- http://www.yxyjzz.cn/ch/index.aspx
- http://wkdxb.wust.edu.cn/wkd_zr/ch/index.aspx
- http://zxs.ijournals.cn/zgkjzydk/ch/index.aspx
- http://wltb.ijournal.cn/ch/index.aspx
- http://www.wjhxxb.cn/wjhxxbcn/ch/index.aspx
- http://www.xnxbs.net/xbnlkjdxskb/ch/index.aspx
- http://hkfdj.ijournals.cn/hkfdj/ch/index.aspx
- http://www.yaoxueyanjiu.org.cn/ch/index.aspx
- http://bjzyxy.ijournals.cn/ch/index.aspx
- http://www.adge.edu.cn/ch/index.aspx

**Comment by jiaojiaodubai** [comment]
### table - span
- http://journal.nudt.edu.cn/gfkjdxxb/ch/index.aspx
- http://www.csejournal.com/zgbmgc/ch/index.aspx
- https://www.xdnykj.com/ch/index.aspx
- http://shht.ijournal.cn/ch/index.aspx
- http://scmj.sma.org.cn/ch/index.aspx
- http://gjjcgxyxb.ijournals.net.cn/ch/index.aspx
- http://www.jchla.com/ch/index.aspx
- http://www.xnxbz.net/xbnlkjdxzr/ch/index.aspx
- http://qdhys.ijournal.cn/hykxjk/ch/index.aspx
- http://www.hjjkyyj.com/hjjkyyj/ch/index.aspx
- http://www.lccscq.com/ch/index.aspx
- http://www.yaoxueyanjiu.com/ch/index.aspx
- http://tcmsj.ijournal.cn/ch/index.aspx
- https://www.zgxdzy.net/ch/index.aspx
