### ISSUE TITLE
   抓取AI辅读网站【https://papers.cool】

### ISSUE THREAD

**Issue by yeruoforever** [l0o0/translators_CN#368]
**你想申请哪个网站的翻译器？** [必填]
[Cool Paper](https://papers.cool)

**网站描述** [必填]
网站整理和抓取了Arxiv的每日论文，并使用AI进行辅助总结，帮助用户快速建立对论文内容的感知。

网站为每篇论文提供了单独的页面，如（ https://papers.cool/arxiv/2408.02672 ）可用于提取相关元信息。
**条目类型**
- [x] preprint
- [x] 期刊
- [x] 图书
- [x] 专利
- [x] ...

**网站权限**
- [ ] 需要注册帐号
- [ ] 需要购买服务或使用机构帐号登录

**Comment by jiaojiaodubai** [comment]
“条目类型”中你勾选了多个，请分别给出示例链接

**Comment by doubanchan** [comment]
从网站首页来看，有Arxiv的预印本和其他一些网站的会议（应该都是计算机类，Arxiv也是部分计算机科学类文章）。感觉必要性可能不是很大，怀疑是否会持续运营。

**Comment by jiaojiaodubai** [comment]
这个网站或许更适合插件用来获取AI摘要？因为它在网页中列出的条目信息并不多，还要再访问出版商网址并map转换器的话也是一键麻烦的事情
