### ISSUE TITLE
知网建议

### ISSUE THREAD

**Issue by yangtzech** [l0o0/translators_CN#37]
目前可以抓到论文EI、北大核心的信息，但是是放在其他栏里，能否自动加上EI、北大核心的标签

**Comment by l0o0** [comment]
这个我担心会有混乱。因为tags目前是优先考虑使用keyword来创建。这个加上标签的需求是用于后续的检索么？

**Comment by yangtzech** [comment]
是的

**Comment by l0o0** [comment]
我可以把代码给你，到时候你在自己的cnki.js上修改一下

**Comment by l0o0** [comment]
@yangtzech 在现在代码的[273行](https://github.com/l0o0/translators_CN/blob/c98e74f329c85f3af65004ef5a479df1297677fa/translators/CNKI.js#L273)添加下面代码，把核心期刊放到标签tag里
```javascript
if (pubType.length > 0) {
    pubType.map(ele => newItem.tags.push(ele.innerText));
}
```
![image](https://user-images.githubusercontent.com/2743744/126165912-ac6a83c2-6d35-44cb-a73a-e1b6c27c106f.png)
 文件修改后，记得更新翻译器

**Comment by yangtzech** [comment]
> @yangtzech 在现在代码的[273行](https://github.com/l0o0/translators_CN/blob/c98e74f329c85f3af65004ef5a479df1297677fa/translators/CNKI.js#L273)添加下面代码，把核心期刊放到标签tag里
> 
> ```js
> if (pubType.length > 0) {
>     pubType.map(ele => newItem.tags.push(ele.innerText));
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/2743744/126165912-ac6a83c2-6d35-44cb-a73a-e1b6c27c106f.png)
> 文件修改后，记得更新翻译器

谢谢大佬😆
