### ISSUE TITLE
CNKI/知网

### ISSUE THREAD

**Issue by doubanchan** [l0o0/translators_CN#375]
**你遇到了什么问题？** [必填]
- [x] 无法保存条目

**发生问题的链接** [必填]
[浙江省科技信息研究院](https://cnki.istiz.org.cn/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFQ)

**问题描述** [必填]
[浙江省科技信息研究院](https://cnki.istiz.org.cn/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFQ)的知网平台可以识别条目，但是抓取失败，同一篇论文在[台湾版](https://cnki.sris.com.tw/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFD)的可以正常抓取，猜测和IP地址有关系（Mainland参数）。最近发现知网对于格式`https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=QXKZ202302004`限制了访问，即需要登录才可访问此种格式（台版的不受限制，另外也许学校代理的也不用，未测试过）。

对于百度学术中来自[知网空间](www.cnki.com.cn)和kns.cnki.net的文献，因为网址格式同样符合上述格式，导致同样抓取错误。
https://github.com/l0o0/translators_CN/blob/fb48f2d3badfff1116b60e1d4120576a0a3856c3/Baidu%20Scholar.js#L128-L130

**你的预期结果**
不知道是否还有公开的接口，或者是不是必须有后面的`v=****`参数。

**Comment by jiaojiaodubai** [comment]
> [浙江省科技信息研究院](https://cnki.istiz.org.cn/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFQ)的知网平台可以识别条目，但是抓取失败，同一篇论文在[台湾版](https://cnki.sris.com.tw/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFD)的可以正常抓取

原则上说，CNKI.js 旨在抓取知网主站，`target` 本应该限定 `host`，然后用户通过[设置 Connector 的 Proxy](https://www.zotero.org/support/connector_preferences#Proxies) 来兼容 VPN 代理后的 URL，因此 着两个网站不在 CNKI.js 的处理范围内，应该写专门的转换器来适配。

> 对于百度学术中来自[知网空间](https://github.com/l0o0/translators_CN/issues/www.cnki.com.cn)和kns.cnki.net的文献，因为网址格式同样符合上述格式，导致同样抓取错误。

意思是现在把知网空间的 URL 替换成知网主站的 URL 已经不能在未登录过知网的的情况下用了对吗？这倒是个问题，因为百度学术有时给出知网空间的来源却不给出知网主站的来源。`v=*` 这样的格式里面，这个 `v` 的值是一个包含当前时间戳和文章定位参数的加密字符串，目前尚不清楚构造方法。向接口请求数据倒是不依赖文档的加载，但是纯纯请求接口的话就会有一点的信息丢失。

**Comment by doubanchan** [comment]
> CNKI.js 旨在抓取知网主站，target 本应该限定 host

不过KCMS/KNS似乎只有CNKI在使用，不限制在cnki.net主站感觉还好。分化出一个CNKI proxy也行，简便主站维护。代理版的应该不止是上面两个，像上面[台湾](https://cnki.sris.com.tw/kcms/detail/detail.aspx?recid=&FileName=QXKZ202302004&DbName=CJFDLAST2023&DbCode=CJFD)版也类似，感觉还是有不少机构内部使用代理版本的CNKI数据库。

> 意思是现在把知网空间的 URL 替换成知网主站的 URL 已经不能在未登录过知网的的情况下用了对吗？

暂时测试是即使已经登录应该也无法抓取。
