### ISSUE TITLE
麻烦问一下，zotero7导入专利的caj，没有办法自动生成条目是什么问题呢

### ISSUE THREAD

**Issue by Vrul** [l0o0/translators_CN#378]
zotero7导入专利的caj，没有办法自动生成条目
无法识别条目

**发生问题的链接** [必填]
https://kns.cnki.net/kcms2/article/abstract?v=6TwuVQQ8bf84mQU8ldpCdURaBCi-XzNpvmP-Sn-xmJYFiPCij5MmiXA5Ue0VFIFvk4G7BTVOH9_IQVL96XGN9dO4CuVywO0qNxaYOcJ89NijqS7czNOH5yT1tapOg8d3aTNLbtIxUg1Y4dSAhAa5xrjtPSI3WFyARTK8QIkcQzuqD6Z3NgORjugRRYaD7Qb4k1HRVZNNlqfhFqeHPlj1nzn_40tN7A87ShdWLs7zgPw=&uniplatform=NZKPT&language=CHS

**问题描述** [必填]
zotero7导入专利的caj，没有办法自动生成条目，显示抓取知网元数据失败

**你的预期结果**
文件能够自动生成条目

**浏览器**
Edge

**自查清单**
我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版

```

**Comment by jiaojiaodubai** [comment]
在 Zotero 客户端中，中文附件自动匹配元数据是 Jasminum 的功能，这个功能使用从文件名中拆分出来的标题作为关键词，在知网的高级搜索中进行搜索。搜不到专利是因为知网的高级检索范围不包括专利——这是可以理解的，因为专利作为引用源的频率比默认勾选的其他几种条目类型更少，如果每一次搜索都将数据库所有类型的蜀山是都检索一遍，开销是比较大的。

暂时的建议：自己在浏览器搜索后抓取条目。
长期：茉莉花以后可能将支持按条目类型匹配条目信息。

**Comment by Vrul** [comment]
好的，感谢感谢！
