### ISSUE TITLE
Publications Data Center - China.js似乎已经无法正常使用

### ISSUE THREAD

**Issue by mofangdasha** [l0o0/translators_CN#382]
**你遇到了什么问题？** [必填]
- [ x] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [] 缺少字段、字段错误
- [ ] 其他

**发生问题的链接** [必填]
https://pdc.capub.cn/search.html#/detail?id=tylvqwta35ru2qljfzyfhs4yuluugc2zgh7vf7i6x4bepxq7kgea&from=1&type=marc

**问题描述** [必填]
Publications Data Center - China.js似乎已经无法正常使用

**你的预期结果**

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [x] Edge
- [ ] Safari
- [ ] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [x ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [x ] 我使用校园网直接访问
- [ ] 我在海外访问

**附件**
如Connector报错记录（建议粘贴代码格式）：
[JavaScript Error: "manager.getWith is not a function
TypeError: manager.getWith is not a function
    at addFileds (Publications%20Data%20Center%20-%20China:367:24)
    at scrapeSingle (Publications%20Data%20Center%20-%20China:215:2)
    at doWeb (Publications%20Data%20Center%20-%20China:92:9)
    at Zotero.Translate.Web.rest (chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translation/translate.js:1379:49)
    at chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/translate/translation/translate.js:1363:39" {file: "[object Object]"}]

**Comment by mofangdasha** [comment]
试了一下，把Publications Data Center - China.js中的getWith更改为get就可以正常使用了。

**Comment by jiaojiaodubai** [comment]
抱歉，是之前重构疏忽所致
