### ISSUE TITLE
RHHZ.js中的target为空，是漏填了还是就应该留空？

### ISSUE THREAD

**Issue by realysy** [l0o0/translators_CN#385]
**你遇到了什么问题？** [必填]
- [ ] 无法识别条目
- [ ] 无法保存条目
- [ ] 无法下载附件
- [ ] 缺少字段、字段错误
- [x] 其他

**发生问题的链接** [必填]
[RHHZ.js](https://github.com/l0o0/translators_CN/blob/master/RHHZ.js)

**问题描述** [必填]
文件开头的target字段为空`"target": "",`

**你的预期结果**
一个字符串用于匹配目标网址

**浏览器**

- [ ] Chrome（谷歌浏览器）
- [ ] FireFox（火狐浏览器）
- [ ] Edge
- [ ] Safari
- [x] 其他

**自查清单**
- [x] 我已经按照[教程](https://zotero-chinese.com/user-guide/faqs/update-translators.html)将翻译器更新到最新版
- [ ] 我尝试过重启浏览器、Zotero或电脑
- [ ] 我使用VPN访问
- [ ] 我使用校园网直接访问
- [ ] 我在海外访问

**Comment by jiaojiaodubai** [comment]
留空，因为不必也无法给出所有适配网站的模式，详见[源码](https://github.com/zotero/translate/blob/93ff314aee4d07a5b04e8ddbdc1ba90dd376e952/src/translators.js#L104C3-L127C5)的处理
