### ISSUE TITLE
申请翻译器：UNESCO数字图书馆，ERIC教育学文摘数据库

### ISSUE THREAD

**Issue by Ben-Tirion** [l0o0/translators_CN#389]
**你想申请哪个网站的翻译器？** [必填]
[联合国教科文组织数字图书馆](https://unesdoc.unesco.org)
[ERIC教育学文摘数据库](https://eric.ed.gov)
**网站描述** [必填]
1.联合国教科文组织数字图书馆
教科文组织数字图书馆是教科文组织机构记忆的宝库，也是有关教科文组织活动（教育、自然科学、社会科学及人文科学、文化、传播与信息）的高质量信息来源，拥有可追溯到 1945 年的 350,000 多份文件。 它包括教科文组织图书馆、教科文组织总部外办事处和研究所的几个文献中心以及教科文组织档案馆的藏书。 教科文组织数字图书馆的基本宗旨是分享知识并将知识传授给后代。
2.ERIC教育学文摘数据库
ERIC是由美国教育资源信息中心整理的已出版的和未出版的教育方面文献的一个指南，涵盖数千个教育专题，提供了最完备的教育书刊的书目信息，包括对发表在Resources in Education (RIE) 月刊上的非期刊资料与每个月发表在Current Index to Journals in Education (CIJE) 上的期刊文章的注释参考，涵盖了从1966年到现在的有关教育方面的几乎所有资料。ERIC收录了1,000多种的期刊和其它资料，共有记录188万多条，包括一个ERIC叙词表，可免费阅读约24万篇全文文章。主题有成人教育、职业教育、教育评估、残疾与天才教育、小学与幼儿教育、高等教育、城市教育、教育管理、信息与技术、语言学与语音学、阅读与交流、教师与教师教育等。该数据库每月更新一次。
**条目类型**
- [x] 期刊
- [x] 图书
- [x] 法律
- [x] 报告
- [x] 会议论文
- [x] 网页

**网站权限**
联合国教科文组织数字图书馆公开权限，Eric需要梯子
- [ ] 需要注册帐号
- [ ] 需要购买服务或使用机构帐号登录

**Comment by jiaojiaodubai** [comment]
[#3372](https://github.com/zotero/translators/issues/3372)
