### ISSUE TITLE
需要翻译器

### ISSUE THREAD

**Issue by bubuhao** [l0o0/translators_CN#390]
**你想申请哪个网站的翻译器？** [必填]
[在此填写链接](https://www.cnki.net/)

**网站描述** [必填]
国家知识基础设施（National Knowledge Infrastructure，NKI）的概念由世界银行《1998年度世界发展报告》提出。1999年3月，以全面打通知识生产、传播、扩散与利用各环节信息通道，打造支持全国各行业知识创新、学习和应用的交流合作平台为总目标，中国知网启动了中国知识基础设施工程（China National Knowledge Infrastructure，CNKI），得到了全国学术界、教育界、出版界、图书情报界的大力支持和密切配合。

**条目类型**
- [x] 期刊
- [x] 图书
- [x] 专利
- [ ] ...

**网站权限**
- [x] 需要注册帐号
- [ ] 需要购买服务或使用机构帐号登录

**Comment by jiaojiaodubai** [comment]
所以你需要哪个网站的转换器，请对照模板认真填写申请信息

**Comment by fanzhen1** [comment]
你想申请哪个网站的翻译器？ [必填]
https://zh.annas-archive.org/search

网站描述 [必填]
安娜档案保存书籍、论文、漫画、杂志等资料，将这些资料从各种[影子图书馆](https://en.wikipedia.org/wiki/Shadow_library)、官办图书馆、其他收藏集等集中到一处。通过简化批量复制的过程——利用BT种子，这些数据在世界各处就能有多份副本，从而得以永久保存。有些影子图书馆自身已采用这种方式（如 Sci-Hub、Library Genesis），而安娜的档案还“解放”了其他不提供批量分发的影子图书馆（如 Z-Library）、无法称为影子图书馆的图书馆（如 Internet Archive、读秀）的馆藏数据。

条目类型

图书为主

网站权限

无需权限

补一个理由
纯粹因为懒，在安娜下了书之后不想再打开读秀或其他网站了。安娜和zlib的题录信息和结构可能不是很规范，尽量就好。另外，由于安娜档案的文件下载是强验证的，可不必做文件抓取功能。
