### ISSUE TITLE
请求增加安娜档案（annas-archive.org）的翻译器

### ISSUE THREAD

**Issue by fanzhen1** [l0o0/translators_CN#393]
**你想申请哪个网站的翻译器？** [必填]
https://zh.annas-archive.org/

**网站描述** [必填]
安娜档案保存书籍、论文、漫画、杂志等资料，将这些资料从各种[影子图书馆](https://en.wikipedia.org/wiki/Shadow_library)、官办图书馆、其他收藏集等集中到一处。通过简化批量复制的过程——利用BT种子，这些数据在世界各处就能有多份副本，从而得以永久保存。有些影子图书馆自身已采用这种方式（如 Sci-Hub、Library Genesis），而安娜的档案还“解放”了其他不提供批量分发的影子图书馆（如 Z-Library）、无法称为影子图书馆的图书馆（如 Internet Archive、读秀）的馆藏数据。

**条目类型**
- [x] 期刊
- [x] 图书

**网站权限**
无需权限

**plus**
安娜档案的题录信息和题录结构可能有点乱，看能否尽量自动化抓取。它的下载是强验证的，可不必提供文件抓取功能。

**Comment by jiaojiaodubai** [comment]
国际站点请到[官方仓库](https://github.com/zotero/translators)提交申请，出于一些法律风险，请求可能不会被通过
