### ISSUE TITLE
Mac上无法自动保存pdf/抓取知网附件

### ISSUE THREAD

**Issue by AnYu124** [l0o0/translators_CN#394]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0
**Jasminum 插件版本**：1.0.0-16

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

**非官方转换器下载异常**

非官方转换器下载出现异常，请在这里说明

**其他功能异常**
浏览器插件可以保存题录数据，但自动下载PDF失败。
（转换器已全
<img width="401" alt="截屏2024-09-12 11 06 01" src="https://github.com/user-attachments/assets/a13f8986-2dd9-4fd2-aa7c-a4706d9deed1">
<img width="592" alt="截屏2024-09-12 11 06 20" src="https://github.com/user-attachments/assets/0e4aebb5-ab1f-4cad-9fa6-52d7ca93e03e">
部更新。）
插件设置中未找到如何绑定知网用户，右键知网助手也无“下载知网附件”选项。
pdf server路径显示异常（已确认在此路径无误）。

请详细说明操作步骤，出现的错误提示信息等

**Comment by jiaojiaodubai** [comment]
见 #252
