### ISSUE TITLE
ZETERO7无法抓取知网PDF

### ISSUE THREAD

**Issue by yy22yy22** [l0o0/translators_CN#396]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0.3
**Jasminum 插件版本**：1.0.0-16

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

**非官方转换器下载异常**

非官方转换器下载出现异常，请在这里说明

**其他功能异常**
知网上无法抓取PDF，右键知网助手也没有办法使用
<img width="1703" alt="屏幕截图 2024-09-03 121950" src="https://github.com/user-attachments/assets/addde5d2-bd75-4e5e-9e96-5a430694e95c">

请详细说明操作步骤，出现的错误提示信息等
<img width="730" alt="屏幕截图 2024-09-03 122456" src="https://github.com/user-attachments/assets/68119e71-a3d6-4eb9-a106-55a8918b7a90">

**Comment by jiaojiaodubai** [comment]
见 #252
