### ISSUE TITLE
zotero 无法导入 ScienceDirect文献[BUG]

### ISSUE THREAD

**Issue by ZhaoZelin2000** [l0o0/translators_CN#397]
**BUG说明**
使用 ScienceDirect 保存时发生错误。改为尝试用 Embedded Metadata 保存。
请填写下面的版本信息
**Zotero 7*：
**Jasminum 1.0.0-16**：

** ScienceDirect 元数据识别失败**
https://www.sciencedirect.com/science/article/pii/S0735193322005462
![image](https://github.com/user-attachments/assets/fae09c41-d65b-4c82-a506-c1f9e4d0fb5e)

**Comment by jiaojiaodubai** [comment]
Science Direct 的抓取由[官方仓库](https://github.com/zotero/translators)维护
