### ISSUE TITLE
无法抓取sciencedirect上的文章

### ISSUE THREAD

**Issue by lishuiwkp** [l0o0/translators_CN#402]
Zotero 版本：6.0.30
Jasminum 插件版本：0.2.8

如图，打开sciencedirect文章的PDF页无法正常抓取。

<img width="235" alt="Snipaste_2024-02-27_15-11-57" src="https://github.com/l0o0/translators_CN/assets/52102381/a516bc64-52c1-4cb9-aad1-75df67f97db7">

**Comment by jiaojiaodubai** [comment]
同 #397
