### ISSUE TITLE
希望添加丁香园平台的支持

### ISSUE THREAD

**Issue by yuzuan** [l0o0/translators_CN#407]
丁香园有很多医疗届大佬分享笔记，希望支持丁香园，导入 zotero 做笔记

**Comment by jiaojiaodubai** [comment]
@yuzuan 可以给具体的链接吗

**Comment by yuzuan** [comment]
丁香园_医疗领域的连接者_丁香园生物医药科技网dxy.cn主链接是这个，谢谢！发自我的 iPhone在 2024年10月28日，16:01，jiaojiaodubai ***@***.***> 写道：﻿
@yuzuan 可以给具体的链接吗

**Comment by jiaojiaodubai** [comment]
你需要列出想抓取的网页、它的条目类型、你想抓取的信息
