### ISSUE TITLE
🛠功能建议[Feature]：抓取专利网站incopat的内容到zotero

### ISSUE THREAD

**Issue by linfengtongxue70** [l0o0/translators_CN#408]
相比于高校实验室工作发表的论文，研究并跟进同行申请的专利被认为是企业研发岗的重要工作。

遗憾的是，zotero目前只能抓取google patent上的内容，但google patent的检索能力较为落后，可供选择的维度不够多，因此研发人员往往会去一些专业网站进行专利的检索。其中，【incopat】网站是最热门的一个专利检索网站，具有强大的功能，检索界面如下PDF所示。且不少大城市的图书馆都购买了相关服务，只要使用当地的ip，市民就可以免费访问该网站。比如，深圳。

[CN115000371A合享专利.pdf](https://github.com/user-attachments/files/17518010/CN115000371A.pdf)

目前，有一个低效且繁琐的工作流：打开incopat检索专利，粘贴感兴趣的专利的专利号到google patent，用zotero进行抓取主要信息，会导zotero中将一些英文内容还原为中文。比如google patent中受让人是“NINGBO SHANSHAN NEW MATERILA TECHNOLOGY Co Ltd, Shanghai Shanshan Technology Co Ltd”实际上其中文名是“宁波杉杉新材料科技有限公司，上海杉杉科技有限公司”。再回到incopat找到下一个专利，重复以上操作。

基于此，请求茉莉花的开发者能考虑抓取incopat的内容到zotero。

祝开发者身体健康，万事顺意。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

**Comment by jiaojiaodubai** [comment]
同 #135
