### ISSUE TITLE
我不能下载pdf，只能收集信息

### ISSUE THREAD

**Issue by zhl111** [l0o0/translators_CN#41]
[JavaScript Error: "Inject: Timed out 614 - https://kns.cnki.net/kns/brief/default_result.aspx?txt_1_value1=%E4%BB%81%E4%B9%89%E4%B9%8B%E8%BE%A9%20%E4%B9%89%E5%88%A9%E4%B9%8B%E8%BE%A8&dbPrefix=SCDB&db_opt=CJFQ%2CCJFN%2CCDFD%2CCMFD%2CCPFD%2CIPFD%2CCCND%2CCCJD%2CHBRD&singleDB=SCDB&action=scdbsearch after 10000ms

**Comment by l0o0** [comment]
同学，我看你这网址，是旧版。新版翻译器是适合新版知网的。

**Comment by dsclub** [comment]
之前工作好好的，近些天来一直出错。今天来此更新了cnki.js到最新版，但是保存到zotero时提示：`保存此条目时发生错误。查看 排除翻译人员问题 获取更多信息。`

请赐教！

**Comment by dsclub** [comment]
> 同学，我看你这网址，是旧版。新版翻译器是适合新版知网的。

我访问的页面是：

https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=MYSY202103008&v=XG2t7I3j51E0b%25mmd2BWLaUsF%25mmd2BkuzUudPRpJg1vfo1KwIFLHd7H64NMdmYZP1jTS%25mmd2FZNEA

这是新版吗？

**Comment by l0o0** [comment]
我看这个是知网阅读的页面，我回去测试下

**Comment by l0o0** [comment]
同学，这个是正常的。这是全文阅读页面，没有pdf下载的链接。在这种页面上是可以下载PDF的
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=MYSY202103008&v=  

![image](https://user-images.githubusercontent.com/2743744/126166645-9bfdca4d-5121-455f-846f-d9b37056937b.png)
