### ISSUE TITLE
全国标准信息公共服务平台抓取时，可否将标准号附在条目标题后面？

### ISSUE THREAD

**Issue by js-fisher** [l0o0/translators_CN#411]
#### 目标链接
[(https://std.samr.gov.cn/)](https://www.cnki.net/)

#### 你想添加的功能

- [x] 将标准号附在条目标题后面，这样更符合国人对标准文件命名的习惯

**Comment by jiaojiaodubai** [comment]
规范填写字段是确保 CSL Style 正确输出的关键，因此我们不会通过向“标题”字段追加标准号来实现客制化的需求（即使这种需求可能是普遍的）。

1. 如果你只是想在看到标题的同时也能看到标准号，应该在任意列标题处右键勾选“号码”列并置于“标题”列后面；
![image](https://github.com/user-attachments/assets/a8908d67-4c71-4b7b-9410-41bec74383e5)

2. 如果你想让附件的文件名重命名为标题后带标准号的形式，可以在“编辑—设置—常规—自定义文件名格式”中参考以下代码进行设置：

```
{{ if {{ itemType =="standard" }} }}
{{ title }}{{ number suffix="-" }}
{{ else }}
{{ firstCreator suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="100" }}
{{ endif }}
```

**Comment by js-fisher** [comment]
收到，十分感谢指教！很受用！
