### ISSUE TITLE
国家知识产权局 专利检索系统 批量抓取条目元数据

### ISSUE THREAD

**Issue by Mctalos** [l0o0/translators_CN#416]
#### 目标链接 [必填]
国家知识产权局 专利检索系统
https://pss-system.cponline.cnipa.gov.cn/conventionalSearch

#### 你想添加的功能（在方框内输入字母“x”表示勾选） [必填]

- [x] 检索结果页面，批量抓取条目元数据
- [ ] 增加网页快照
- [ ] 抓取引用数
- [ ] …

#### 详细说明如下：
希望能在国家知识产权局 专利检索系统的检索结果页面，批量抓取条目的元数据（只抓取专利名称、专利号、申请号、申请日期、摘要等即可，详细如图所示）。
不需要下载附件、网页截图，只需要建立条目并填充元数据即可。一方面是这个网站下载附件需要进入验证页面输入验证码；另一方面，用抓取插件批量下载附件，限制很多、容易被封号（我的专利之星账号就被封了o(╥﹏╥)o）。

目前是只能点击条目，进入条目详情页面抓取单个元数据。

关于附件下载，我倒是有其他付费平台（智慧芽之类的）可以批量下载附件，但是考虑付费平台做翻译器不太好做，故请求做国知局这个公开免费网站的翻译器。
烦请开发大大们帮帮忙。

<img width="948" alt="20241225_10-44-17 抓取内容" src="https://github.com/user-attachments/assets/98184311-2dd8-4fdc-982b-b88b99aa79be" />

**Comment by jiaojiaodubai** [comment]
“著录项目”内的必要信息也是网站JS代码自行维护的，网站启用了反调试工具，强行逆向有法律风险。

**Comment by Mctalos** [comment]
> “著录项目”内的必要信息也是网站JS代码自行维护的，网站启用了反调试工具，强行逆向有法律风险。你可以向他们反馈要求提供一个导出文献交换格式（RIS、Endnote之类）的API，这样能兼顾网站当前的信息安全需求。

好吧，看样子不好实现。
国知局这个系统不支持导出著录项。支持导出的检索平台还都是收费的，而且收费很贵，这点比较难以理解，专利本来就是付费公开换取法律保护的模式。为啥检索平台还要搞这么多限制。。。

最近开始尝试用zotero管理、分析、跟踪专利文件，发现超级方便。但是前几天在专利之星上，一口气抓取了近100个条目，然后账号就被禁封了😭。。。。

我再想其他办法，考虑其他方式建立工作流吧。。
