### ISSUE TITLE
希望有开发经验的大佬搞一个适配WPS的Zotero插件

### ISSUE THREAD

**Issue by lon91ong** [l0o0/translators_CN#43]
不清楚为什么WPS官方论坛关闭了, 找到不反馈问题的渠道
目前WPS和MS Office的功能基本上完全看齐了, 甚至VBA脚本都很少需要改动就能完美运行.
只有插件这块儿适配的不太好, Zotero的Word插件可以加载到WPS中,如下图
![WPS加载Zotero插件](https://user-images.githubusercontent.com/16462258/122636763-89239780-d11d-11eb-90a7-8413da497536.png)
在插入引用时可以成功调用Zotero, 但是最后一步总是报错
![报错](https://user-images.githubusercontent.com/16462258/122636801-ba9c6300-d11d-11eb-8d53-ba87f7ce390d.png)

目前能在WPS中使用的文献管理工具只有NoteExpress, 使用体验实在是一言难尽
![NoteExpress](https://user-images.githubusercontent.com/16462258/122636838-e1f33000-d11d-11eb-9690-4aa05984a068.png)

希望开发大佬出手适配一下, 可能有用的参考[在WPS下开发JS插件说明](http://resource.wpseco.cn/testjsplugins/js_help.html)

**Comment by l0o0** [comment]
这个目前超纲了，我也是刚学JS没多久的新人。

**Comment by Lemmingh** [comment]
造一个 Zotero WPS Integration，确实超纲。

---

[Zotero Word for Windows Integration](https://github.com/zotero/zotero-word-for-windows-integration) 是一个跟 JavaScript 几乎没有关系的古董。

`Zotero.dotm` 是用 VBA 写的 Word Template，仅实现 Ribbon 菜单以及从 Word 发消息到 Zotero。

而主体是一个用 Visual C++/MFC 写的库，调用 Word Interop API 来实现引文管理功能。

这导致它不能在 WPS 上正常工作。

---

如果要支持 WPS，则需调用 [WPS 文字 API](https://open.wps.cn/docs/office)。文档在 WPS 开放平台 > 开发文档 > WPS 客户端开发 > WPS 基础接口 > 文字 API 参考。

简单翻了一下 [Zotero Connector](https://github.com/zotero/zotero-connectors) 以及[其他 Zotero integration plugin](https://github.com/zotero/zotero-google-docs-integration)，感觉 WPS 加载项确实可以实现相关功能。

从 Zotero 拉取数据是大头。

* Zotero 桌面应用有 [Zotero Connector Server](https://www.zotero.org/support/dev/client_coding/connector_http_server)。它自带一套 RPC 风格的 [HTTP Citing Protocol](https://www.zotero.org/support/dev/client_coding/http_integration_protocol)。

* [Better BibTeX for Zotero (BBT)](https://retorque.re/zotero-better-bibtex/) ([GitHub](https://github.com/retorquere/zotero-better-bibtex)) 示范了如何扩展 Connector Server。不过，不太清楚 [Zotero 5.0.71](https://www.zotero.org/support/changelog#changes_in_5071_july_17_2019) 的更改

  > Additional protections to prevent visited webpages from triggering actions in Zotero plugins

  会产生什么阻碍。

目前就找到这么多。

如果哪位有兴趣，可以试一下。

---

如果不行，那么只好也走 OLE Automation。搜到几篇古老的文章，或许可参考：

* [Visual Studio 兼容开发 WPS 和 Office](https://blog.csdn.net/yanpengliumin/article/details/50344855)
* [操作 WPS Office 2013 实例](https://blog.csdn.net/luozhuang/article/details/43196681)
* [WPS Office 的二次开发](http://blog.sina.com.cn/s/blog_469ff3450102wnxd.html)

**Comment by lon91ong** [comment]
> 造一个 Zotero WPS Integration，确实超纲。
> 
> [Zotero Word for Windows Integration](https://github.com/zotero/zotero-word-for-windows-integration) 是一个跟 JavaScript 几乎没有关系的古董。
> 
> `Zotero.dotm` 是用 VBA 写的 Word Template，仅实现 Ribbon 菜单以及从 Word 发消息到 Zotero。
> 
> 而主体是一个用 Visual C++/MFC 写的库，调用 Word Interop API 来实现引文管理功能。
> 
> 
> 从 Zotero 拉取数据是大头。
> 

` 从 Zotero 拉取数据是大头`, 这个`大头`感觉不太准确, 从Zotero取数据毕竟VBA都已经实现了, 直接照着用JS重写即可, 真正的`大头`应该是用JS解析数据并实现`用 Visual C++/MFC 写的库`的功能

**Comment by lon91ong** [comment]
刚刚试着看看Zotero.dotm中的VBA代码, 用Word2016打开提示"功能锁定"-"工程不可查看", 换WPS2019打开, 直接随便看
注明了使用GNU共享协议, 有两个模块, Zotero和ZoteroRibbon, 代码超简单:

```
' Zotero功能的精华

Sub ZoteroCommand(cmd As String, bringToFront As Boolean)
    Dim cds As COPYDATASTRUCT
    #If VBA7 Then
        Dim ThWnd As LongPtr
    #Else
        Dim ThWnd As Long
    #End If
    Dim a$, args$, name$
    Dim i As Long
    Dim ignore As Long
    Dim sBuffer$
    Dim lLength As Long
    Dim buf() As Byte
    
    ' Try various names for Firefox
    Dim appNames(5)
    appNames(1) = "Zotero"
    appNames(2) = "Firefox"
    appNames(3) = "Browser"
    appNames(4) = "firefox-dev"
    For i = 1 To 4
        ThWnd = FindWindow(appNames(i) & "MessageWindow", vbNullString)
        If ThWnd <> 0 Then
            Exit For
        End If
    Next
    If ThWnd = 0 Then
        MsgBox ("Word could not communicate with Zotero. Please ensure Zotero is running and try again. If this problem persists, see https://www.zotero.org/support/word_processor_plugin_troubleshooting")
        Exit Sub
    End If
    
    ' Allow Firefox to bring a window to the front
    If bringToFront Then Call SetForegroundWindow(ThWnd)
    
    ' Get path to active document
    If ActiveDocument.Path <> "" Then
        name$ = ActiveDocument.Path & Application.PathSeparator & ActiveDocument.name
    Else
        name$ = ActiveDocument.name
    End If
    
    ' Set up command line arguments
    name$ = Replace(name$, """", """""")
    args$ = "-silent -ZoteroIntegrationAgent WinWord -ZoteroIntegrationCommand " & cmd & " -ZoteroIntegrationDocument """ & name$ & """"
    a$ = "firefox.exe " & args$ & Chr$(0) & "C:\"
    
    ' Do some UTF-8 magic
    lLength = WideCharToMultiByte(CP_UTF8, 0, StrPtr(a$), -1, ByVal 0, 0, 0, 0)
    ReDim buf(lLength) As Byte
    Call WideCharToMultiByte(CP_UTF8, 0, StrPtr(a$), -1, buf(1), lLength, 0, 0)
    
    ' Send message to Firefox
    cds.dwData = 1
    cds.cbData = lLength
    cds.lpData = VarPtr(buf(1))
    i = SendMessage(ThWnd, WM_COPYDATA, 0, cds)
    
    ' Handle error
    If Err.LastDllError = 5 Then
        If Dir("C:\Program Files\Mozilla Firefox\firefox.exe") <> "" Then
            Call Shell("""C:\Program Files\Mozilla Firefox\firefox.exe"" " & args$, vbNormalFocus)
        ElseIf Dir("C:\Program Files (x86)\Mozilla Firefox\firefox.exe") <> "" Then
            Call Shell("""C:\Program Files (x86)\Mozilla Firefox\firefox.exe"" " & args$, vbNormalFocus)
        End If
    End If
End Sub
```

用JS重写的话, 就卡在了`FindWindow`这种系统API的操作函数, 需要用另外的工具实现

**Comment by Lemmingh** [comment]
Zotero Word for Windows Integration 的那个 `Zotero.dotm` 仅仅是个 Ribbon，点一下就向 Zotero 发个指令，其他什么功能都没有。

所有逻辑都是在 Zotero 中实现的。

我理解的它的架构：

``````
+------------------+    +------------------+
|  Microsoft Word  |    |      Zotero      |
|                  |    |                  |
| +-------------+  |    | +-------------+  |
| | Zotero.dotm |-------->|   Citation  |  |
| +-------------+  |    | |   handler   |  |
|                  |    | +-------------+  |
|                  |    |        ↕         |
| +-------------+  |    | +-------------+  |
| |   Document  |  |    | |   Glue JS   |  |
| +-------------+  |    | +-------------+  |
|        ↕         |    |        ↕         |
| +-------------+  |    | +-------------+  |
| | Interop API |<------->|    Native   |  |
| +-------------+  |    | +-------------+  |
|                  |    |                  |
+------------------+    +------------------+
``````

"Zotero" pulls from and pushes to "Microsoft Word".

---

而做 WPS Integration，我认为应当采取这种方案：

``````
+------------------+    +------------------+
|       WPS        |    |      Zotero      |
|                  |    |                  |
| +-------------+  |    | +-------------+  |
| |   Ribbon    |  |    | |   Citation  |  |
| |      /      |  |    | |   handler   |  |
| |   TaskPane  |  |    | +-------------+  |
| +-------------+  |    |        ↕         |
|        ↑         |    | +-------------+  |
|        |         |    | |   Custom    |  |
|        ↓         |    | |   endpoint  |  |
| +-------------+  |    | |   handler   |  |
| | Plugin host |<---+  | +-------------+  |
| +-------------+  | |  |        ↕         |
|        ↕         | |  | +-------------+  |
| +-------------+  | +--->|  Connector  |  |
| |   Document  |  |    | |   server    |  |
| +-------------+  |    | +-------------+  |
|                  |    |                  |
+------------------+    +------------------+
``````

"WPS" pulls from "Zotero".

**Comment by lon91ong** [comment]
@Lemmingh 是我理解的肤浅了, 刚刚用WPS打开Zotero.dotm查看源代码, 确实如你所言
但是用这种方案的话, 许多Zotero已经实现的工作必须都用JS加载项重做了, 比如: 丰富的引文格式, 工作量不是一般的大

**Comment by Lemmingh** [comment]
> 丰富的引文格式

关键在 Custom endpoint handler 能做什么。

上面提到了 BBT，它在 Connector Server 上实现了许多 endpoint。按这个思路，利用 Zotero plugin，仍然可以让 Zotero 完成排版，最后 WPS 加载项这边拉取呈现和 metadata，再嵌入文档。（在 Word 上，是 Zotero 走 IA 把这些东西写进文档。）

但我不清楚 Zotero 5.0.71 增加的安全限制是怎么回事。如果是测 UA，可以想办法绕过。

* Electron 似乎不受影响。因为一个基于 BBT 开发的产品 (<https://github.com/mblode/vscode-zotero/blob/0a0298cf1b6c0f3685d74a67263d3dcbe69735b8/extension.js#L8>) 仍能工作。

* 根据文档，WPS plugin host 是个 Chromium，那么，网络通信能用 XHR 或者 Fetch，我不知道它会被 Zotero 当成什么东西。Chrome 好像有个什么毛病，我想不起来。

**Comment by l0o0** [comment]
目前有同学向wps发邮件，希望开发插件。wps也回应了，希望能早点出来

**Comment by bigben446** [comment]
建了一个zotero-wps插件开发项目，感兴趣的同学一起去那边交流吧，争取早日搞定zotero的wps插件。zotero-wps插件开发的交流QQ群：1029775161，https://github.com/l0o0/Zotero-WPS

**Comment by jiaojiaodubai** [comment]
WPS 的 Windows 端已主动兼容 Zotero，详见 [2023-04 的更新](https://bbs.wps.cn/topic/12477)，以及[手动安装教程](https://p.kdocs.cn/s/ZPIJCBAABE)，至于 macOS，已经在[画饼](https://bbs.wps.cn/topic/40731)了。
