### ISSUE TITLE
专利之星patent star 和 soopat两个专利网站现在不能识别

### ISSUE THREAD

**Issue by leonsong09** [l0o0/translators_CN#44]
专利之星patent star 和 soopat两个专利网站现在不能识别

**Comment by wanyzh** [comment]
> 专利之星patent star 和 soopat两个专利网站现在不能识别

你好。专利之星我这边看了下没问题阿，麻烦给个不能识别的网址看看。

**Comment by leonsong09** [comment]
https://cprs.patentstar.com.cn/Search/Detail?ANE=6AEA9FEA6DBA9EEA9GHF9GDA9HAA9BDB7ABA9AFE8FBA7CDA

**Comment by leonsong09** [comment]
目前多刷新了几次已经能够使用
