### ISSUE TITLE
文件名识别出错，请检查文件名识别模板与实际抓取文件名

### ISSUE THREAD

**Issue by LvShuaiChao** [l0o0/translators_CN#47]
抓取知网数据，但是弹出对话框，“文件名识别出错，请检查文件名识别模板与实际抓取文件名”该如何处理呢？

![image](https://user-images.githubusercontent.com/35528109/128693212-b67b7bbb-0ac5-42d4-89f3-654f49e44386.png)

**Comment by Sciroccogti** [comment]
请查看 *首选项*->*茉莉花*->*中文插件设置* 中 *文件名格式设置*。

默认是 `{%t}_{%g}`，即文件名须为 **标题_作者** 格式，正如你其它的一些文件一样。

可以在添加前手动修改文件名，加上作者后缀。不知道能不能设置多种格式。

**Comment by l0o0** [comment]
@LvShuaiChao 同学，截图上的文件是只包括标题，可以修改识别模板为{%t}。后期我们会考虑针对{%t}_{%g} 和{%t} 做一个优化，尽量实现模糊搜索的功能。知网下载的文件一般是这两种命名格式
