### ISSUE TITLE
不支持旧版的知网吗

### ISSUE THREAD

**Issue by LvShuaiChao** [l0o0/translators_CN#48]
我使用的旧版知网的搜索页面是这个https://kns.cnki.net/kns/brief/default_Result.aspx?code=SCDB&&korder=0&sel=1#
但是发现Zotero的插件却无法变成文件夹进行下载
![image](https://user-images.githubusercontent.com/35528109/128700778-a26996d8-550c-44df-bee5-e7581f85a5e9.png)

**Comment by l0o0** [comment]
旧版的你可以参考代码库里的历史版本 [1d5a68c198904e5fa94d9ea0943e3029d0dee517](https://github.com/l0o0/translators_CN/blob/a29ee07f88f9b7ff1221992ae9c22460228f4b21/translators/CNKI.js)
