### ISSUE TITLE
如何抓取全国图书馆参考咨询联盟的图书信息？

### ISSUE THREAD

**Issue by rainmisty** [l0o0/translators_CN#5]
全国图书馆参考咨询联盟（http://www.ucdrs.superlib.net/）的图书信息是相对较全的，如何抓取呢？

**Comment by kuulu** [comment]
链接：https://pan.baidu.com/s/16d3CXjQmzSzvpulGBmwRfQ
提取码：itvy

**Comment by kuulu** [comment]
收费的东西，我想找人破解一下
