### ISSUE TITLE
能否支持 https://chkd.cnki.net/

### ISSUE THREAD

**Issue by lucifr** [l0o0/translators_CN#51]
医院用的是知网的中国医院知识总库（CHKD）版本，能否在插件中支持一下呢，或者提供一下自行修改的思路，谢谢！

**Comment by wanyzh** [comment]
初步看了下代码，目前的知网翻译器可以支持部分CHKD库的抓取。
你浏览器里显示connector无效的原因是detectWeb函数没有正常返回，但是直接执行doWeb是可以正常抓取报纸和部分期刊的。
修改思路是看看getTypeFromDBName函数中dbcode和对应的文献类型。
下边是我测试的时候修改的：
`function getTypeFromDBName(dbname) {
	var dbType = {
		CJFQ: "journalArticle",
		CJFD: "journalArticle",
		CAPJ: "journalArticle",
		SJES: "journalArticle",
		SJPD: "journalArticle",
		SSJD: "journalArticle",
		CCJD: "journalArticle",
		CDMD: "journalArticle",
		CYFD: "journalArticle",
		CDFD: "thesis",
		CMFD: "thesis",
		CLKM: "thesis",
		CCND: "newspaperArticle",
		CPFD: "conferencePaper",
		IPFD: "conferencePaper",
		SCPD: "patent",
		CHKN: "newspaperArticle",
		CHKJ: "journalArticle",
		CDMH: "thesis"
		
	};`

### 最后三行是我添加的分别对应着CHKD总库中的报纸、期刊论文和学位论文，其中前两个测试了几个是成功的，但学位论文不成功。
供参考。

**Comment by lucifr** [comment]
我修改一下试试，感谢！

**Comment by l0o0** [comment]
#125 同样的问题

**Comment by jiaojiaodubai** [comment]
@lucifr  已经在 c0eabf6ae6a101bc17d80bf407b43b9780e779c6 完成。
