### ISSUE TITLE
万方数据搜索页面出错

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#55]
在万方数据的搜索页面提示 **“保存此条目时发生错误。查看 [排除翻译人员问题](https://www.zotero.org/support/troubleshooting_translator_issues) 获取更多信息。”**

在单篇论文页面，可以正常保存。

**Comment by l0o0** [comment]
@pixiandouban 万方的搜索页面上HTML的信息应该是加密了，我很难获取真实的信息。不过单个页面的查询接口还可以使用。所以就出现了你说的那个问题。解密对我来说太难了。。。希望有同学可以试试

**Comment by pixiandouban** [comment]
@l0o0 是否可以模拟点击标题获取到网址/href，然后再做抓取的动作？

**Comment by l0o0** [comment]
@pixiandouban 这个好像有点难度啊，translator的代码环境不支持这样的办法

**Comment by Lemmingh** [comment]
没有加密，`$store` 里都是明文。

**万方数据知识服务平台** 在向 SPA 发展，前端用 Vue，通信用 gRPC-Web，Local Storage 里也存数据。

理论上可以抓取搜索页 (`s.wanfangdata.com.cn`)，但是，开发和维护的成本 **很不合算**。更何况 Zotero translator 只是一段 `eval` 进去的脚本，不是 DevTools。

**Comment by l0o0** [comment]
@Lemmingh 谢谢老哥的提醒。之前我一直不理解这种页面是怎么生成的，以为是加密呢。看到这几个名词，感觉又学到知识了。不过如你所说，像这种隐藏起来的信息，用 translator 来抓取，是比较麻烦且费事
