### ISSUE TITLE
知网搜索包含CNKI Scholar外文期刊

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#56]
假如知网搜索的内容包含外文期刊（收录在 scholar.cnki.net ），如果抓取保存外文期刊，则会出现 **“保存此条目时发生错误。查看 [排除翻译人员问题](https://www.zotero.org/support/troubleshooting_translator_issues) 获取更多信息。”**

**Comment by pixiandouban** [comment]
第二、知网中的报刊📰是否要加上CN刊号？

**Comment by l0o0** [comment]
@pixiandouban 能否提供一个外文期刊的链接

**Comment by pixiandouban** [comment]
举例，在知网检索外文期刊 [Zotero: A Guide for Librarians, Researchers and Educators](https://kns.cnki.net/kns8/defaultresult/index?korder=TI&kw=Zotero%3A%20A%20Guide%20for%20Librarians%2C%20Researchers%20and%20Educators)。

在知网搜索结果页面，有 [Zotero: A Guide for Librarians, Researchers and Educators, 2nd ed. ](https://kns.cnki.net/KNS8/Detail/RedirectScholar?flag=TitleLink&tablename=GARJ2018&filename=SPQDB236A9CE4454A2DC1D6AC6E8C09B3CC0)，这个外文期刊（CNKI Scholar）的链接会跳转到 [schlr.cnki.net](https://schlr.cnki.net/zn/Detail/index/GARJ2018/SPQDB236A9CE4454A2DC1D6AC6E8C09B3CC0)

**Comment by l0o0** [comment]
用接口获取外文期刊引用格式时，出现问题，看看有没有新接口

**Comment by l0o0** [comment]
中文和英文的期刊参数还不一样。不过确实可以正常获取，等什么时候有空更新一下

**Comment by pixiandouban** [comment]
@l0o0 看到你之前在 Zotero 的 translators上提到过类似的issues，https://github.com/zotero/translators/issues/2134 。

**Comment by l0o0** [comment]
现在已经不一样了，原来的链接都已经更新也新的外文链接。旧链接的话，只要添加一个匹配的数据库字段就可以了，现在不行了。

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/227887286-a965d413-af48-4744-8125-84965e8866c1.png)
知网外文搜索抓取异常

**Comment by jiaojiaodubai** [comment]
@pixiandouban 已经在 6471e94727e56744ac06fa266437d3e25cf189db 中完成。

**Comment by doubanchan** [comment]
@l0o0 @jiaojiaodubai [CNKI Scholar](https://scholar.cnki.net/home/search?sw=1&sw-input=we)似乎未识别，比如[testcase](https://scholar.cnki.net/zn/Detail/index/GARJ2021_4/SJESC1B29038F19D150B6527A7D18A6611BB)。

似乎知网对未全文收录的外刊（特别是无CN刊号的）在CNKI.net已经搜索不到了（以前应该是可以统一检索的），只能在scholar.cnki.net检索，或许适合把 CNKI Scholar独立出来？

**Comment by jiaojiaodubai** [comment]
***@***.***的意见。---Original---
@l0o0 @jiaojiaodubai CNKI Scholar似乎未识别，比如testcase。
似乎知网对未全文收录的外刊（特别是无CN刊号的）在CNKI.net已经搜索不到了（以前应该是可以统一检索的），只能在scholar.cnki.net检索，或许适合把 CNKI Scholar独立出来？

**Comment by doubanchan** [comment]
> 似乎知网对未全文收录的外刊（特别是无CN刊号的）在CNKI.net已经搜索不到了（以前应该是可以统一检索的），只能在scholar.cnki.net检索，或许适合把 CNKI Scholar独立出来？

不是搜索不到，如果从主页（CNKI.net）进入搜索页面，系统默认只检索中文文献（也符号用户期望和减少资源浪费），选择“总库”或“外文”即可检索到上文提到的[testcae](https://scholar.cnki.net/zn/Detail/index/GARJ2021_4/SJESC1B29038F19D150B6527A7D18A6611BB)。
