### ISSUE TITLE
微信公众号的链接

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#57]
微信公众号是用的长链接，是不是保持原始地址栏的短链接比较好？

**Comment by Lemmingh** [comment]
微信的链接取自页面的 metadata。理论上，这是最可靠的，不会过期。

<https://github.com/l0o0/translators_CN/blob/ef7f259a134af5869f55c77d64fadb54fa46c773/translators/Weixin.js#L42>

如果要用其他的形式，恐怕需要向腾讯的员工请教公众号文章的链接格式。

不知道哪位能联系上？

**Comment by pixiandouban** [comment]
@Lemmingh 网页源代码里面的长链接和地址栏里的短链接应该都是永久链接。

我自己是改成了下面这个
`item.url = url;`

**Comment by Lemmingh** [comment]
这事很难说。我曾碰到过期链接。

建议还是去请一位腾讯内部人员。

/cc @l0o0

**Comment by l0o0** [comment]
@Lemmingh 这个我很难了解相关信息，建议按照自己理解修改代码好了
