### ISSUE TITLE
知网、万方DOI

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#59]
知网和万方的DOI不能通过添加DOI的方式，直接从Zotero抓取文章信息。

举例，知网文章  [10.13671/j.hjkxxb.2012.02.011](https://www.cnki.net/kcms/doi/10.13671/j.hjkxxb.2012.02.011.html)，通过 [doi.org](https://www.doi.org/)、[中文DOI](http://www.chinadoi.cn/portal/index.htm)、[知网DOI](http://doi.cnki.net/) 可以跳转到知网对应文章页面，但是不能提取文章信息。

可以和这个项目无关，先在这提一下，或者可能需要Zotero解决？

附上 Zotero 论坛上的帖子，[Can not Resolve a DOI of a Chinese database CNKI](https://forums.zotero.org/discussion/comment/322412)

**Comment by Lemmingh** [comment]
当你使用 DOI 抓取时，Zotero 通过 CrossRef 查询 metadata。

没有中文刊物算是情理之中吧。至少我还没有听说过哪个国内的出版机构在 CrossRef 注册。

知网、万方本身就是 DOI Registration Agency (RA)，跟 CrossRef 平级。或许你可以请他们与 CrossRef 共享数据。

**Comment by l0o0** [comment]
如上同学所说，doi抓取对中文支持较差
