### ISSUE TITLE
抓取知乎页面 

### ISSUE THREAD

**Issue by DansYU** [l0o0/translators_CN#6]
抓取的知乎页面 打开后会一直刷新

**Comment by l0o0** [comment]
我试了一下，发现离线保存的网页，打开后会出现一些问题
![图片](https://user-images.githubusercontent.com/2743744/83352263-e155f300-a37c-11ea-87c3-5410e7880bde.png)

估计可能是知乎那边做了一些跨域请求的限制。
目前我这边没有相关zhihu的抓取插件，负责现在的抓取插件应该是在官方那边负责的。

**Comment by DansYU** [comment]
这个功能是否可以做？
知乎上有些比较有用的技术贴，想用zotero来管理。

**Comment by l0o0** [comment]
对于这个功能如何做，我不是很清楚。因为不知道如何保存这个东西。我觉得是否可以通过禁用某些js就可以了。不过需要进行测试。等我有空，可以试试

**Comment by Lemmingh** [comment]
> 可能是知乎那边做了一些跨域请求的限制

我认为这不是知乎的问题。

CORS （现在是 Fetch 标准的一部分）本身非常严格。CORS 请求是 HTTP 请求（只能使用 HTTP / HTTPS 协议），标准规定了必须和允许的 header，还跟着其他一堆约束条件。此外，某些浏览器还会自己添加标准之外的限制。

那张图显然是直接打开了本地 HTML 文件，协议是 file （本地资源，会导致没有 `Origin`），这肯定不可以。试试搭个 HTTP 服务器。

---

> 这个功能如何做

前些阵子，牛岱[发布了 Zhihu On VSCode](https://zhuanlan.zhihu.com/p/106057556)，其中实现了浏览知乎的功能。那么，抓取知乎页面肯定是可行的。

不妨参考他的办法，访问知乎的 API：

* [/src/const/URL.ts](https://github.com/niudai/VSCode-Zhihu/blob/master/src/const/URL.ts)
* [/src/service/collection.service.ts](https://github.com/niudai/VSCode-Zhihu/blob/master/src/service/collection.service.ts)

网上也有其他人研究过，比如

* [知乎 API v4 整理](https://www.jianshu.com/p/86139ab70b86)
* [随手找到的知乎的 API](https://zhuanlan.zhihu.com/p/87029765)

**Comment by l0o0** [comment]
@Lemmingh 谢谢这位同学提供的这么详细的资料，我抽空看一下

**Comment by l0o0** [comment]
@DansYU 同学，你这边的需求是什么，把回答离线保存下来么？

**Comment by DansYU** [comment]
我的需要就是能把知乎的专栏网页 和 回答保存下载，要是能实现酒非常感谢了！！

**Comment by luohc2004** [comment]
> 
> 
> @DansYU 同学，你这边的需求是什么，把回答离线保存下来么？

哇噻，还在积极开发。zotero开源生态真不错。owner真强。以后能自己动手就好了~项目README.MD最后的链接很有帮助

**Comment by l0o0** [comment]
有空也一起开发呀。这知乎不知道怎么弄😂


FrenzyBoy <notifications@github.com>于2020年7月13日 周一08:22写道：

**Comment by Lemmingh** [comment]
```typescript
// Prototype of Zotero web translator for 知乎 (Zhihu)

async function doWeb(doc: Document, url: string): Promise<void> {
    let newZoteroItem = new Zotero.Item('document');

    // TODO: Reduce `url`, such as removing unnecessary query string, before performing other operations.

    // If there is any exception, let it propagate to terminate the process.
    const res: ZhihuItem = await invokeApi(url);

    // Generate the snapshot of the Zhihu item.
    const snapshot: HTMLDocument = getSnapshot(res);
    newZoteroItem.attachments.push({
        title: 'Snapshot',
        document: snapshot
    });

    // TODO: Set metadata.

    // Save.
    newZoteroItem.complete();
}


/**
 * Sends an HTTP request to Zhihu API, and returns response body in a `Promise<ZhihuItem>`.
 * @param {string} url - URL of the answer or Zhuanlan article.
 */
function invokeApi(url: string): Promise<ZhihuItem> {

    // ! Warning:
    // ! RegExp lookbehind assertions are not available until ECMAScript 2018.
    // ! https://github.com/tc39/proposal-regexp-lookbehind

    // Zhuanlan article URL examples:
    // https://zhuanlan.zhihu.com/p/59589298
    // https://zhuanlan.zhihu.com/p/35295235
    //// const ZhuanlanArticleUrlBase = 'https://zhuanlan.zhihu.com/p/';
    const ZhuanlanArticleIdRegexp = /(?<=p\/)\d+/;

    // Answer URL examples:
    // https://www.zhihu.com/answer/984072342
    // https://www.zhihu.com/question/24952084/answer/984072342
    // https://www.zhihu.com/question/392313958/answer/1198915276
    const AnswerIdRegexp = /(?<=answer\/)\d+/;

    let apiUrl: string;
    let id: string;

    // Construct API URL.
    let m: RegExpMatchArray | null;
    if ((m = url.match(ZhuanlanArticleIdRegexp))) {
        id = m[0];
        apiUrl = `https://zhuanlan.zhihu.com/api/articles/${id}`;
    } else if ((m = url.match(AnswerIdRegexp))) {
        id = m[0];
        apiUrl = `https://www.zhihu.com/api/v4/answers/${id}?include=content,excerpt`;
    } else {
        throw new Error("Not supported");
    }

    // Important:
    // Many Zhihu services, including API, lack cross-origin headers.
    // Well, it doesn't seem to matter, since Zotero web translator should run in the same context as the active document in the browser.

    // ! `Promise` may throw exceptions that can only be caught by try-catch.
    return fetch(apiUrl).then(res => res.json());
}


/**
 * Generates the snapshot of a Zhihu answer or Zhuanlan article.
 * @param {ZhihuItem} item
 */
function getSnapshot(item: ZhihuItem): HTMLDocument {
    let doc = new HTMLDocument();

    // Assuming that response from Zhihu is safe.
    doc.body.innerHTML = item.content;

    // TODO: Inject other elements if necessary.

    return doc;
}


// Below are not exhausted.
// The type annotations are not carefully crafted, because Zhihu APIs are really awful.

interface ZhihuItem {
    id: number;
    type: string;
    author: ZhihuAuthor;

    /**
     * Content.
     * An HTML string.
     */
    content: string;

    /**
     * Abstract.
     * A plain text string or HTML string.
     */
    excerpt: string | HTMLElement;
}


interface ZhihuAnswer extends ZhihuItem {
    answer_type: string;
    question: ZhihuQuestion;
    excerpt: string;

    /**
     * API URL.
     */
    url: string;
}


interface ZhihuArticle extends ZhihuItem {
    title: string;
    // excerpt_title: string;
    excerpt: HTMLElement;
    share_text: string;

    /**
     * Article URL.
     */
    url: string;
}


interface ZhihuQuestion {
    id: number;
    type: string;
    title: string;
    question_type: string;
    excerpt: string;
    detail: HTMLElement;

    /**
     * API URL.
     */
    url: string;
}


interface ZhihuAuthor {
    id: string;
    name: string;
    type: string;
}
```

**Comment by Lemmingh** [comment]
**专栏文章**的 `<head>` 有 Open Graph 元数据。**回答**的 `div.ContentItem.AnswerItem` 中有 Microdata 元数据。这些也能用，而且应该比走 API 方便。

**Comment by l0o0** [comment]
@Lemmingh 我不是很明白，这个snapshot的item是哪个translator控制的？

**Comment by Lemmingh** [comment]
是指这个吗：
`function getSnapshot(item: ZhihuItem): HTMLDocument`

这是我自己捏的函数。

`item` 的数据格式是 `ZhihuItem`，定义在下面那一团里。

整个原型都用 TypeScript 写，图方便。

**Comment by l0o0** [comment]
@Lemmingh 这样啊，不过现在Zotero好像不能自定义item type。我现在还不大确定知乎这个要做成哪种的 item type。或者直接使用webpage这个类型。

**Comment by Lemmingh** [comment]
你是不是没用过 [TypeScript](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)。😅

TypeScript 可以理解为加了**静态检查**的 JavaScript，要编译成 JavaScript 才能运行。

---

知乎的 Zotero type 取 `document` 即可：
`let newZoteroItem = new Zotero.Item('document');`

`snapshot` 的类型是 `HTMLDocument`，虽然 Zotero 的文档没有明说，但可以观察出来。其他的对象类型也可以推导。

**Comment by l0o0** [comment]
我js都是现学的，为了应付处理这些translator。你说的这些我会好好参考的，我先试试看

Lemmingh <notifications@github.com>于2020年7月15日 周三22:00写道：

**Comment by liuxsdev** [comment]
> 我的需要就是能把知乎的专栏网页 和 回答保存下载，要是能实现酒非常感谢了！！

我觉得可以用其他一些工具来保存页面，zotero只负责元数据的提取，最后将附件和zotero关联即可。

利用一些chrome插件，像**简悦**对知乎有适配，可以保存为离线markdown，pdf，html之类的；
**SingleFile**可以完美的保存离线HTML。

我最近在管理B站视频就是这种思路，手动下载视频，再关联条目。

**Comment by l0o0** [comment]
@Lemmingh 参考了你前面给的API链接。我测试了下，可以把知乎上的内容保存到笔记中，图片，链接以及具体格式的显示效果都挺好。
![image](https://user-images.githubusercontent.com/2743744/108731634-b4c7b400-7567-11eb-87fe-f3413e970082.png)
