### ISSUE TITLE
当当网图书

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#60]
当当网图书可能因为需要登录，似乎无法解析

**Comment by pixiandouban** [comment]
`"target": "^http?://(product|search)\\.dangdang\\.com/",`

需要改成（原[dangdang.js](https://github.com/l0o0/translators_CN/blob/master/translators/Dangdang.js) target中少了一个`s`；另外不确定是否还会出现需要登录的情况）

`"target": "^https?://(product|search)\\.dangdang\\.com/",`

**Comment by l0o0** [comment]
我这边测试的时候，不需要登录。不知道同学你需要登录是指什么页面。
确实如果是https的话，是识别不了的。这个翻译器不是我写的，需要到道格学社提issue https://github.com/gezhongran/DougSociety

**Comment by pixiandouban** [comment]
@l0o0  现在感觉登录的问题不大，现在只要把 target 后天添加个 s 就可以了。

**Comment by pixiandouban** [comment]
@l0o0 道格那边更新了。可以同步更新过来。
