### ISSUE TITLE
玛格泰克、仁和汇智、勤云科技等期刊自建平台

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#64]
Magtech/[玛格泰克](https://www.magtech.com.cn)、[仁和汇智](https://rhhz.net/)、[勤云科技](http://e-tiller.com/et/home)，看起来是不少期刊网站的服务提供商，期刊网站底层应该是差不多的。期刊官网比知网等聚合平台的好处在，不少期刊自建平台官网提供免费下载的。

例，Magtech 部分期刊列表
https://www.magtech.com.cn/CN/column/column6.shtml

看了几个期刊网站，大概可以识别成 [Embeded Metadata.js](https://github.com/zotero/translators/blob/master/Embedded%20Metadata.js) ，少数不规范的可能需要手动复制参考文献。

**Comment by l0o0** [comment]
我简单了解了下，上面提到的3个提供商，协助开发了许多学术期刊的网站。然后可以利用底层差不多的关系，开发一个翻译器。我觉得你的想法没有问题。就是实践起来应该挺麻烦。因为目前zotero connector 还是依赖 URL 的匹配来识别的。如果不同期刊网站的网址不同，需要针对不同的期刊来创建不同的翻译器。这样虽然信息抓取可能精确些，不过开发量还是挺大的。

像你之前说的，用 Embeded Metadata 这个翻译器，应该是最通用的。

**Comment by pixiandouban** [comment]
@l0o0 官方库里面有套用 Embeded Metada 翻译器的[例子](https://github.com/pixiandouban/translators/blob/master/BBC.js)。只需要把缺失的元素补上就可以。

**Comment by l0o0** [comment]
同学的意思是把缺失的信息，从网页上抓取再补上么？如果是这样的话，因为不同期刊网站样式各不相同。如果要把信息补全，对不同的网站，要使用不同的查找规则来完成信息的查找与补全。难度不大，就是开发适配的工作量比较大

**Comment by jiaojiaodubai** [comment]
我做了一点调查，MagTech的系统只有代际之间的差别，同代际网页之间的导出接口是一样的，虽然它们期刊的网页主站点不一样，但中间参数是有规律的，调整合适的优先级即可应用于不同期刊的网页，我已经在制作MagTech的翻译器了。

**Comment by doubanchan** [comment]
顺便说一下玛格泰克（Magtech）参与了国标[期刊文章标签集：GB/T 40959-2021](https://std.samr.gov.cn/gb/search/gbDetailed?id=D1E86BE73A97430EE05397BE0A0A206B)的编写
