### ISSUE TITLE
万方/知网中文名格式问题

### ISSUE THREAD

**Issue by actforjason** [l0o0/translators_CN#66]
`translators.zhnamesplit=true`设置后抓取的中文名是这样，后边还带个`,(名)`
![image](https://user-images.githubusercontent.com/57058325/147313154-84b6972a-313f-4066-b923-f3e240cdd8b3.png)
能不能改成这样
![image](https://user-images.githubusercontent.com/57058325/147313328-fd8d1d81-ace5-4068-ba69-013f04b1f1d1.png)

**Comment by pixiandouban** [comment]
@actforjason 这个应该可以通过安装 [jasminum ](https://github.com/l0o0/jasminum)插件来解决这个问题。
![image](https://user-images.githubusercontent.com/50656651/147524660-61228f2b-2e69-4395-9a42-63e76b0e67f7.png)

**Comment by l0o0** [comment]
> 

后面带的那个名，应该是 Zotero 在姓名栏这里的占位符，其实是空的，只是展示成这样
