### ISSUE TITLE
不能找到pDF文件

### ISSUE THREAD

**Issue by ylrace** [l0o0/translators_CN#67]
CNKIPDF=true的时候，无法抓取pdf文件，抓取的都是caj文件

**Comment by l0o0** [comment]
默认抓取都是PDF文件，同学是不是在浏览器那里的高级设置做了更改？

**Comment by ylrace** [comment]
只在插件的高级设置那里更新了一下翻译器，没有设置别的选项

**Comment by l0o0** [comment]
浏览器的设置里，有没有点击过 update translastor。如果没有可以看一下更新的视频

**Comment by ylrace** [comment]
我已经是按照视频操作的，点过更新翻译器。

**Comment by l0o0** [comment]
这个浏览器更新翻译器，我也不敢保证一定能起效果。我只是建议多试试几次。或者换个浏览器再试试

**Comment by ylrace** [comment]
好的，谢谢
