### ISSUE TITLE
Baidu Scholar

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#68]
脚本里面的测试用例的网址感觉可以用比较简单的网址。另外，第一个测试用例的已经发生了网页跳转，第二个测试用例的网址失效了。

**Comment by l0o0** [comment]
是的，我最近在用scaffold 进行测试的时候，发现这个百度学术的翻译器，测试时老是超时，不能返回结果。反而在实际抓取的时候是正常的。不知道同学你用scaffold进行测试的时候正常不？

**Comment by pixiandouban** [comment]
@l0o0 脚本里面的测试用例替换一下应该就好了。其他的脚本出现过 scaffold 正常，浏览器插件不正常的情况。

**Comment by l0o0** [comment]
@pixiandouban 就是我在更新测试用例的时候经常出现超时的情况，我不知道是不是scaffold的问题。不知道你那边点测试页面那个update 按键的时候，能正常更新不？

**Comment by pixiandouban** [comment]
@l0o0 Baidu Scholar 似乎不支持对期刊文章以外的出版物抓取的元素不全，比如 Zotero 论坛上的这个专利issue ["Baidu Scholar" translator report error](https://forums.zotero.org/discussion/96786/baidu-scholar-translator-report-error#latest)。另外好像会议也是，举例[某个会议](https://xueshu.baidu.com/usercenter/paper/show?paperid=99d353b9677f0d0287e051e400aea729&site=xueshu_se)，会议名称和会议地点没有正常抓取。

**Comment by pixiandouban** [comment]
在  #105 统一反馈
