### ISSUE TITLE
建议支持从中国国家图书馆抓取图书信息

### ISSUE THREAD

**Issue by Reveanime** [l0o0/translators_CN#7]
[中国国家图书馆](http://www.nlc.cn/)网页提供了[文津搜索](http://find.nlc.cn/)，该搜索引擎可以查找到在国内出版的图书信息

**Comment by l0o0** [comment]
@Reveanime 好的，加入计划了

**Comment by l0o0** [comment]
[文津搜索](https://github.com/l0o0/translators_CN/blob/master/translators/Wenjin.js)已添加
