### ISSUE TITLE
WeiPu.js 无ISSN

### ISSUE THREAD

**Issue by pixiandouban** [l0o0/translators_CN#70]
[WeiPu.js](https://github.com/l0o0/translators_CN/blob/master/translators/WeiPu.js) 的 testcase 中无ISSN，实际抓取也没有获得。

**Comment by pixiandouban** [comment]
@yfdyh000  有无ISSN问题不大，只是此处提到了

https://github.com/l0o0/translators_CN/blob/54ae8ff876fa46d1d56fd10813e849fbdc698c30/translators/WeiPu.js#L152-L155

**Comment by yfdyh000** [comment]
这个ISSN是`getRefByID`从搜索结果的“导出题录”中获取，响应中有ISSN。但功能或许有问题了。

**Comment by pixiandouban** [comment]
[Refworks 格式导出页](https://qikan.cqvip.com/Qikan/Search/Export)？

**Comment by jiaojiaodubai** [comment]
原来的接口似乎已经失效了，我重写了整个脚本，包括ISSN在内的基本信息已经可以正常抓取了，但是我没有维普的帐号，希望 @yfdyh000 可以完善一下。
我重写的分支：
[WeiPu.js](https://github.com/jiaojiaodubai/translators_CN/blob/WeiPu/WeiPu.js)

**Comment by yfdyh000** [comment]
> 原来的接口似乎已经失效了，我重写了整个脚本，包括ISSN在内的基本信息已经可以正常抓取了，但是我没有维普的帐号，希望 @yfdyh000 可以完善一下。 我重写的分支： [WeiPu.js](https://github.com/jiaojiaodubai/translators_CN/blob/WeiPu/WeiPu.js)

https://github.com/yfdyh000/translators_CN/commit/485a6eb4f60ee1d29bd1cf29c25a7a8e1250e607 完成，可以下载PDF了。

**Comment by jiaojiaodubai** [comment]
@hujie12306 @56125a @yzy1228682367 @l0o0  

经测试，(#173 ) (#90) 有关的问题已经在 485a6eb4f60ee1d29bd1cf29c25a7a8e1250e607  解决。

不过有一点需要注意，维普的网页打开后长时间没有操作（实测大概是10分钟），服务器会拒绝导出条目信息的POST请求，估计跟Record、LogBehavior这两个请求有关，要在Translator中模拟相应的过程太困难了，推荐的做法是：

### 如果抓取到的条目在`extra`字段有`debugMsg`，请刷新网页后重新抓取。
