### ISSUE TITLE
增加对期刊网址的支持

### ISSUE THREAD

**Issue by fredericky123** [l0o0/translators_CN#71]
https://navi.cnki.net/knavi/journals/LKGP/detail
例如目前这样的期刊网址，插件是不支持的，请问能加入支持吗？非常感谢！

**Comment by fredericky123** [comment]
https://github.com/l0o0/jasminum/issues/61#issuecomment-1035932748

**Comment by fredericky123** [comment]
提供一个思路来获取文章的引文信息，通过文章的英文版获取到文章的id，然后利用id定位到文章的中文版
[英文文章](https://oversea.cnki.net/kcms/detail/14.1221.F.20220107.1119.002.html) -> [中文文章](https://t.cnki.net/kcms/detail/14.1221.F.20220107.1119.002.html)

以上是同一篇

**Comment by Lemmingh** [comment]
> https://navi.cnki.net/knavi/journals/LKGP/detail

我不理解之前的讨论。你们打算从这个页面中抓取什么？

---

> 获取文章的引文信息

其实，所有 文献知网节 (Knowledge Network Node) 页面的结构都是一样的，用
<https://github.com/l0o0/translators_CN/issues/61#issuecomment-981361654>
的方法即可获取参数。

真正的难点是：

一般来说，存在多个参数组合可以到达同一篇文献。我也不知道哪个是“最规范的”。其中，网络首发稿的参数组合更是奇奇怪怪，有时甚至 `ShowExport` 接口返回的值无效。

**Comment by fredericky123** [comment]
> 
是想要导入首发稿的这些文章信息
<img width="708" alt="image" src="https://user-images.githubusercontent.com/13982749/153803433-186f8822-91d1-4616-99e5-85b63b42fe2d.png">

**Comment by fredericky123** [comment]
> 一般来说，存在多个参数组合可以到达同一篇文献。我也不知道哪个是“最规范的”。其中，网络首发稿的参数组合更是奇奇怪怪，有时甚至 `ShowExport` 接口返回的值无效。

我发现，在英文网页版的知网直接输入中文标题检索，打开的链接包含一个id，这个文章id好像是最简洁且具有唯一性的标识

**Comment by fredericky123** [comment]
> 一般来说，存在多个参数组合可以到达同一篇文献。我也不知道哪个是“最规范的”。其中，网络首发稿的参数组合更是奇奇怪怪，有时甚至 ShowExport 接口返回的值无效
具体步骤请看这里：
https://github.com/DIYgod/RSSHub/pull/8877#issuecomment-1038720512
需要在https://oversea.cnki.net/ 检索

**Comment by jiaojiaodubai** [comment]
@fredericky123  已在 6471e94727e56744ac06fa266437d3e25cf189db 完成
