### ISSUE TITLE
知网空间的支持

### ISSUE THREAD

**Issue by l0o0** [l0o0/translators_CN#72]
知网空间在网页上部有不同数据库类型，需要匹配对应的dbcode，dbname为对应dbcode + temp
![图片](https://user-images.githubusercontent.com/2743744/153737461-6b53f608-43f8-4a2d-831e-e8846a1b0616.png)

以下有学位论文的一个示例，实际在新版知网查询后为 https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1021126936.nh&uniplatform=NZKPT&v=whH-u26mAhw41JHIEdgrudS2Y5jLa96KGJUllvwD3Z-oHe48pKHpeMwPuSXFzs7o。 dbcode 由 CDMD -> CDFD。 filename为知网空间网址后面的一串数字。
https://cdmd.cnki.com.cn/Article/CDMD-10141-1021126936.htm

以上只是其中一个的示例，可能还有其他情况，待补充

**Comment by Lemmingh** [comment]
规律似乎比较好找。“学位论文”的变换略微复杂，不清楚第 1 串数字（下文用 `${_}` 表示）是什么东西。



| 类型     | 网址格式                                                          |
| -------- | ----------------------------------------------------------------- |
| 期刊全文 | `www.cnki.com.cn/Article/CJFDTOTAL-${FileName}.htm`               |
| 学位论文 | `cdmd.cnki.com.cn/Article/CDMD-${_}-${FileName.slice(0, -3)}.htm` |
| 会议论文 | `cpfd.cnki.com.cn/Article/CPFDTOTAL-${FileName}.htm`              |



| 类型     | 知网空间                     | FileName           | DbName (s)     | DbName (x) |
| -------- | ---------------------------- | ------------------ | -------------- | ---------- |
| 期刊全文 | `CJFDTOTAL-JLJS201205002`    | `JLJS201205002`    | `CJFDTEMP`     | `CJFQTEMP` |
| 期刊全文 | `CJFDTOTAL-SJCG201802027`    | `SJCG201802027`    | `CJFDTEMP`     | `CJFQTEMP` |
| 学位论文 | `CDMD-10141-1021137130`      | `1021137130.nh`    | `CDFDTEMP`     | `CDFDTEMP` |
| 学位论文 | `CDMD-80000-1021010363`      | `1021010363.nh`    | `CDFDTEMP`     | `CDFDTEMP` |
| 会议论文 | `CPFDTOTAL-ZGWI202104001001` | `ZGWI202104001001` | `CPFDTEMP`     | `CPFDTEMP` |
| 会议论文 | `CPFDTOTAL-SHFX202112003022` | `SHFX202112003022` | `CPFDLAST2022` | `CPFD2022` |



`DbName` 的来源：

* `(s)` 取自通过检索到达的 文献知网节 页面上的 `<input>` 元素。

* `(x)` 取自 `https://kns.cnki.net/kns8/manage/ShowExport` 接口返回的数据。

---

题外话：
不知为何，我的浏览器打开知网空间时，CPU 会持续满载，很吓人。

**Comment by l0o0** [comment]
@Lemmingh 你上面给的，是一个一个点开获取的么?

我觉得到时候可以先部分支持，等有识别不了的情况，等大家反馈更新就可以了。我们也不可能完全遍历。

我这边打开知网空间，没有CPU高负载的情况

**Comment by jiaojiaodubai** [comment]
已在 6471e94727e56744ac06fa266437d3e25cf189db 支持
