### ISSUE TITLE
统一题录的语言格式

### ISSUE THREAD

**Issue by fredericky123** [l0o0/translators_CN#73]
目前从知网等导入，显示的language为"中文"，不符合后端csl的语言规范，能否统一为“zh”或“zh-CN”？英文则统一为"en"

**Comment by fredericky123** [comment]
对于中文文献的语言格式，感觉各位大佬在csl中写的不统一，斗胆建议各位大佬商量出一致的标准（zh,zh-CN等），供大家明确统一
@l0o0 
@redleafnew 
@zepinglee 
@qnscholar

**Comment by fredericky123** [comment]
@zepinglee

**Comment by zepinglee** [comment]
Zetero 的参考文献生成工具 CSL 要求 `language` 为 ISO 639-1 的语言代码，比如 “en”, “zh” 或者 “de-DE”, “de-AT”（ <https://docs.citationstyles.org/en/stable/specification.html#standard-variables>）。
<img width="699" alt="Screen Shot 2022-02-19 at 20 37 31" src="https://user-images.githubusercontent.com/12290822/154801066-65408df0-446b-4a52-a72e-4949b79925fb.png">

大陆地区的中文论文使用 `zh-CN` 比较合适。

**Comment by fredericky123** [comment]
这个其实同样存在于英文文献，不同期刊网址导入的有的显示en，有的显示en-US，还有English，总需要花些额外时间来处理

**Comment by zepinglee** [comment]
> 这个其实同样存在于英文文献，不同期刊网址导入的有的显示en，有的显示en-US，还有English，总需要花些额外时间来处理

`en` 和 `en-US` 影响不大，CSL 有一套 locale fallback 的机制（<https://docs.citationstyles.org/en/stable/specification.html#locale-fallback>）。由于 `en-US` 是 `en` 的 primary dialect，这两种设置方式其实都是调用 `locales-en-US`。

**Comment by fredericky123** [comment]
> > 这个其实同样存在于英文文献，不同期刊网址导入的有的显示en，有的显示en-US，还有English，总需要花些额外时间来处理
> 
> `en` 和 `en-US` 影响不大，CSL 有一套 locale fallback 的机制（https://docs.citationstyles.org/en/stable/specification.html#locale-fallback）。由于 `en-US` 是 `en` 的 primary dialect，这两种设置方式其实都是调用 `locales-en-US`。

明白了，在Zotero中文社区，尤其是tanslators_CN能统一，就足够了

**Comment by l0o0** [comment]
好的，我和能联系上的朋友说明下，统一我们使用的语言格式

**Comment by l0o0** [comment]
> 
我后续把 翻译器和插件中文里的语言栏都会更新为`zh-CN`。

**Comment by l0o0** [comment]
> Zetero 的参考文献生成工具 CSL 要求 `language` 为 ISO 639-1 的语言代码，比如 “en”, “zh” 或者 “de-DE”, “de-AT”（ https://docs.citationstyles.org/en/stable/specification.html#standard-variables）。 <img alt="Screen Shot 2022-02-19 at 20 37 31" width="699" src="https://user-images.githubusercontent.com/12290822/154801066-65408df0-446b-4a52-a72e-4949b79925fb.png">
> 
> 大陆地区的中文论文使用 `zh-CN` 比较合适。

我后面会把中文翻译器里的语言更新为`zh-CN`

**Comment by zepinglee** [comment]
简单搜了一下，目前还有一些 translator 的语言设置没有统一，尤其是知网和万方。这个语言的格式其实是 <https://en.wikipedia.org/wiki/IETF_language_tag>，也叫 BCP 47，简体中文只能设置 `zh` 和 `zh-CN`。`zh_CN` 是不合规范的，可能会导致问题。

https://github.com/l0o0/translators_CN/blob/c4efe03b58cc63a9470a0c800b9a870bec730603/translators/CNKI.js#L58

https://github.com/l0o0/translators_CN/blob/006b7983d782a6fd6ea628eacebc09e81f8c7f42/translators/Wanfang%20Data.js#L229

需要我发个 PR 吗？
