### ISSUE TITLE
CNKI检索页pdf抓取失败

### ISSUE THREAD

**Issue by sammo3182** [l0o0/translators_CN#74]
首先非常感谢translator_CN和 jasminum 实现了很多可能，极大增强文献收集效率！

最近在使用最新translator情况下出现在检索页可以正常识别文献meta data并导入Zotero，但pdf下载失败情况。系统为Win11, Edge浏览器，校园网。translator在本地和connect均updated。不知是网站问题还是设置问题，如是后者，烦劳赐教！不胜感谢！

**Comment by tianxuanzhizi** [comment]
+1，能出现full text选项，但是是叉号下载失败

**Comment by wuhao12325** [comment]
我的问题是使用个人账户登录时，也能出现full text选项，但是同样是叉号下载失败

**Comment by 18846194690** [comment]
检索页无法实现批量下载pdf

**Comment by JasonX2140** [comment]
> 我的问题是使用个人账户登录时，也能出现full text选项，但是同样是叉号下载失败
一样的情况，个人账号登陆，显示了“full text”样式，但一会之后提示叉号和下载失败

**Comment by l0o0** [comment]
在这里和大家说明一下，知网下载PDF，不同学校网络环境不同。同时知网那边在下载PDF和CAJ时 ，需要越来越多的要求，已经不是几天前那样，只要简单提供一个下载的链接就可以直接下载。
如今知网下载可能会有跳转，验证码或加密的情况。在Zotero 的网页抓取环境中可能处理不了这么复杂的情况，会有下载失败的情况发生
