### ISSUE TITLE
无法抓取知乎回答

### ISSUE THREAD

**Issue by exusiaiwei** [l0o0/translators_CN#75]
使用最新版的知乎翻译器，无法抓取知乎回答；在抓取知乎回答的时候显示如下：
![image](https://user-images.githubusercontent.com/91778467/155966088-d2890c98-2532-4c82-a297-95e9f7790006.png)

在我的测试中，知网、国外学术网站、知乎文章的抓取是正常的

**Comment by l0o0** [comment]
应该是接口失效了

**Comment by exusiaiwei** [comment]
那请问有办法修复吗，抓取知乎回答的功能在搭建网络收藏夹的时候非常有用，真的很希望能够解决这个问题，麻烦维护小组的诸位了！

**Comment by l0o0** [comment]
我在找可用的api接口

**Comment by wzh4464** [comment]
是不是还是不行，
![zotero_tran_CN](https://user-images.githubusercontent.com/32484940/188054887-cb16ba32-cc95-4651-9146-2bd53ba60f84.PNG)
