### ISSUE TITLE
万方数据无法抓取文献题录

### ISSUE THREAD

**Issue by Liwt0** [l0o0/translators_CN#78]
使用 Wanfang Data保存时发生错误。尝试使用 DOI 保存。

**Comment by Liwt0** [comment]
Wanfang Data.js文件点开显示404了

**Comment by eb307130227** [comment]
万方数据无法抓取题录信息

**Comment by l0o0** [comment]
上面两位同学 @Liwt0 @eb307130227 麻烦提供一下URL，我测试一下

**Comment by Liwt0** [comment]
https://github.com/l0o0/translators_CN/blob/master/translators/WanFang/Data.js，这个链接显示404

**Comment by l0o0** [comment]
> https://github.com/l0o0/translators_CN/blob/master/translators/WanFang/Data.js

https://github.com/l0o0/translators_CN/blob/master/translators/Wanfang%20Data.js  应该是这个链接，中间有个空格

不过万方把之前的接口禁用了，所以原来的翻译器不能用了。等我更新下代码吧
