### ISSUE TITLE
旧版知网入口不能导入PDF的问题原因找到了

### ISSUE THREAD

**Issue by zhengtao-777** [l0o0/translators_CN#79]
大佬，非常感谢您的translator，爬中文的容易好多。两天试用中发现翻译器对CNKI旧版高级检索不支持自动下载PDF，新版的就可以。之所以用旧版的，是因为旧版的搜索栏不会没事儿折叠（新版搜索了就给折叠），文献来源的点击、时间范围的设定要比新版简洁直观好用。看了下CNKI.js，发现里面确实没有对旧版高级检索的支持，自己也不会写，希望大佬能帮忙补充一下。

旧版高级检索地址：https://kns.cnki.net/kns/brief/result.aspx?dbprefix=CJFQ
新版高级检索地址（kns8）：https://kns.cnki.net/kns8/AdvSearch?dbprefix=CFLS&&crossDbcodes=CJFQ%2CCDMD%2CCIPD%2CCCND%2CCISD%2CSNAD%2CBDZK%2CCCJD%2CCCVD%2CCJFN

**Comment by jiaojiaodubai** [comment]
@zhengtao-777  已在 6471e94727e56744ac06fa266437d3e25cf189db 完成。
