### ISSUE TITLE
万方抓取错误

### ISSUE THREAD

**Issue by hope2002399** [l0o0/translators_CN#8]
万方www.wanfangdata.com.cn抓取似乎不行，不知道其他人是否也这样？

**Comment by l0o0** [comment]
@hope2002399 好的，我近期会测试下。

**Comment by l0o0** [comment]
万方的网站改进了，一些数据传输也更加隐蔽了，把关键信息都放到cookie里面了。这无疑给我写翻译器增加了许多难度。

**Comment by l0o0** [comment]
@hope2002399 已经更新了，你试试看，现在还不能自动拉取PDF文件。能读取信息了

**Comment by hope2002399** [comment]
正常了，非常感谢



发件人： Linxzh
发送时间： 2020-10-06 15:47
收件人： l0o0/translators_CN
抄送： hope2002399; Mention
主题： Re: [l0o0/translators_CN] 万方抓取错误 (#8)
@hope2002399 已经更新了，你试试看，现在还不能自动拉取PDF文件。能读取信息了
