### ISSUE TITLE
豆瓣出版社抓取错误

### ISSUE THREAD

**Issue by moleng09** [l0o0/translators_CN#85]
总是会将出版社与副标题一起抓下来
<img width="228" alt="image" src="https://user-images.githubusercontent.com/54031747/160286098-d5d68cb5-5036-4def-a168-d905c30472ec.png">
如图

**Comment by zhl111** [comment]
嗯，是个问题

**Comment by pixiandouban** [comment]
应该是已经修复了。https://github.com/l0o0/translators_CN/pull/91
