### ISSUE TITLE
更换translator后，万方仍然报错

### ISSUE THREAD

**Issue by rrcic** [l0o0/translators_CN#86]
“保存此条目时发生错误。查看“排除翻译人员问题”获取更多信息。”
只有在使用万方时遇到了这个问题，百度文库和知网等能够正常使用。

**Comment by tughv** [comment]
刚用了下最新的，确实报错
使用 Wanfang Data保存时发生错误。尝试使用 DOI 保存。

**Comment by tughv** [comment]
试了下作者的源码，doPost时返回status 0，不知道是不是这个原因

**Comment by l0o0** [comment]
@tughv 是呢。万方接口不能用了。新接口好像用了protobuf之类的东西，我觉得直接抓取HTML会简单些。

**Comment by tughv** [comment]
作者好像是不论是multiple还是具体网页都由zotero发起网页请求，但是这样的结果就是具体页也啥都拿不到。

**Comment by tughv** [comment]
@rrcic 我在作者的基础上尽力改了下，目前能够抓取具体也的期刊文章，你要是需要的话先用这个，万方的链接是加密后传输的，我现在还没搞明白加密代码，所以没法批量抓取。

**Comment by l0o0** [comment]
@tughv 你目前自己修改的，是用万方的接口么？还是其他什么方式？

**Comment by tughv** [comment]
@l0o0 在详情页的情况下不需要再对网页发起请求，只需要使用xpath提取出里面的信息，但是批量抓取就要发起请求，我还没搞定那个加密和解密的东西，所以目前我的只能够对详情页进行信息抓取，至少有得用吧。

**Comment by l0o0** [comment]
@tughv 详情页的我也已经更新了。我稍后再推送一下

**Comment by realzsy** [comment]
> @tughv 详情页的我也已经更新了。我稍后再推送一下

是不是还没更新，“保存此条目时发生错误。查看“排除翻译人员问题”获取更多信息。”，还是这个报错信息。

**Comment by tughv** [comment]
@realzsy  你需要 把数据库translators里面的wanfangData.js删掉，然后把我的wanfangData-my.js放进去，不然的话匹配时会匹配到两个翻译器。

**Comment by tughv** [comment]
你要是急着用可以先试试我的，不过要把作者的那个删掉，不然两者会冲突

**Comment by tughv** [comment]
@realzsy 你要是急着用可以先试试我的，不过要把作者的那个删掉，不然两者会冲突

**Comment by choyy** [comment]
这个问题还存在吗？我在详情页面仍然报错

**Comment by tughv** [comment]
@choyy 我自己的写的能抓取详情页，在我的库里面wanfangdata-my.js,你把原来的那个删掉，我的放进去就行了

**Comment by tughv** [comment]
@choyy 能用啊，重启几次zotero和浏览器试试

**Comment by choyy** [comment]
> @choyy 能用啊，重启几次zotero和浏览器试试

感谢！多重启了几次就好了
