### ISSUE TITLE
维普抓取错误

### ISSUE THREAD

**Issue by hujie12306** [l0o0/translators_CN#90]
![image](https://user-images.githubusercontent.com/61086637/162690802-b69dcb39-bbc8-437a-bce6-67a8327d69c3.png)
网址：http://qikan.cqvip.com/Qikan/Article/Detail?id=7106652486

**Comment by hujie12306** [comment]
万方也不行啦
![image](https://user-images.githubusercontent.com/61086637/162691968-a93a0392-99e1-43c3-a6c2-c4c80b0453e5.png)

**Comment by pixiandouban** [comment]
> ![image](https://user-images.githubusercontent.com/61086637/162690802-b69dcb39-bbc8-437a-bce6-67a8327d69c3.png) 网址：http://qikan.cqvip.com/Qikan/Article/Detail?id=7106652486

维普这边用着没问题，重新刷新一下试试？只是现在没有抓到ISSN编号。
