### ISSUE TITLE
有没有人写一个anobii.com的translator，书籍非常全。繁体、简体都很好。

### ISSUE THREAD

**Issue by myjeshurun** [l0o0/translators_CN#99]

**Comment by l0o0** [comment]
我看了一下，自带的Embeded Metadata 也能抓取部分数据。专门的translator 可能抓取质量更好一些

**Comment by myjeshurun** [comment]
没事，后来我找到了台湾的：全国图书资讯网http://nbinet3.ncl.edu.tw/screens/opacmenu_cht.html，然后用zotero
connect来抓取书籍信息，响应完美。


Blessings in Christ,

*Jeshurun*
*我的仆人雅各，我所拣选的耶书崙哪，不要害怕！*
*Don’t be afraid, Jacob my servant; and you, Jeshurun, whom I have chosen.*
